import { AgencyGroupRepository } from "../../../agency/ports/AgencyGroupRepository";
import { AgencyRepository } from "../../../agency/ports/AgencyRepository";
import { DelegationContactRepository } from "../../../agency/ports/DelegationContactRepository";
import { AssessmentRepository } from "../../../convention/ports/AssessmentRepository";
import { ConventionExternalIdRepository } from "../../../convention/ports/ConventionExternalIdRepository";
import { ConventionQueries } from "../../../convention/ports/ConventionQueries";
import { ConventionRepository } from "../../../convention/ports/ConventionRepository";
import { ConventionsToSyncRepository } from "../../../convention/ports/ConventionsToSyncRepository";
import { NpsRepository } from "../../../convention/ports/NpsRepository";
import { DeletedEstablishmentRepository } from "../../../establishment/ports/DeletedEstablishmentRepository";
import { DiscussionRepository } from "../../../establishment/ports/DiscussionRepository";
import { EstablishmentAggregateRepository } from "../../../establishment/ports/EstablishmentAggregateRepository";
import { EstablishmentLeadQueries } from "../../../establishment/ports/EstablishmentLeadQueries";
import { EstablishmentLeadRepository } from "../../../establishment/ports/EstablishmentLeadRepository";
import { FormEstablishmentRepository } from "../../../establishment/ports/FormEstablishmentRepository";
import { GroupRepository } from "../../../establishment/ports/GroupRepository";
import { SearchMadeRepository } from "../../../establishment/ports/SearchMadeRepository";
import { EstablishmentMarketingRepository } from "../../../marketing/ports/EstablishmentMarketingRepository";
import { ApiConsumerRepository } from "../../api-consumer/ports/ApiConsumerRepository";
import { OngoingOAuthRepository } from "../../authentication/inclusion-connect/port/OngoingOAuthRepositiory";
import { UserRepository } from "../../authentication/inclusion-connect/port/UserRepository";
import { ConventionFranceTravailAdvisorRepository } from "../../authentication/pe-connect/port/ConventionFranceTravailAdvisorRepository";
import { OutboxQueries } from "../../events/ports/OutboxQueries";
import { OutboxRepository } from "../../events/ports/OutboxRepository";
import { FeatureFlagRepository } from "../../feature-flags/ports/FeatureFlagRepository";
import { NotificationRepository } from "../../notifications/ports/NotificationRepository";
import { RomeRepository } from "../../rome/ports/RomeRepository";
import { BroadcastFeedbacksRepository } from "../../saved-errors/ports/BroadcastFeedbacksRepository";
import { ShortLinkQuery } from "../../short-link/ports/ShortLinkQuery";
import { ShortLinkRepository } from "../../short-link/ports/ShortLinkRepository";
import { StatisticQueries } from "../../statistics/ports/StatisticQueries";

export type UnitOfWork = {
  agencyGroupRepository: AgencyGroupRepository;
  agencyRepository: AgencyRepository;
  apiConsumerRepository: ApiConsumerRepository;
  assessmentRepository: AssessmentRepository;
  conventionExternalIdRepository: ConventionExternalIdRepository;
  conventionPoleEmploiAdvisorRepository: ConventionFranceTravailAdvisorRepository;
  conventionQueries: ConventionQueries;
  conventionRepository: ConventionRepository;
  conventionsToSyncRepository: ConventionsToSyncRepository;
  delegationContactRepository: DelegationContactRepository;
  deletedEstablishmentRepository: DeletedEstablishmentRepository;
  discussionRepository: DiscussionRepository;
  broadcastFeedbacksRepository: BroadcastFeedbacksRepository;
  establishmentAggregateRepository: EstablishmentAggregateRepository;
  establishmentLeadQueries: EstablishmentLeadQueries;
  establishmentLeadRepository: EstablishmentLeadRepository;
  establishmentMarketingRepository: EstablishmentMarketingRepository;
  featureFlagRepository: FeatureFlagRepository;
  formEstablishmentRepository: FormEstablishmentRepository;
  groupRepository: GroupRepository;
  notificationRepository: NotificationRepository;
  npsRepository: NpsRepository;
  ongoingOAuthRepository: OngoingOAuthRepository;
  outboxQueries: OutboxQueries;
  outboxRepository: OutboxRepository;
  romeRepository: RomeRepository;
  searchMadeRepository: SearchMadeRepository;
  shortLinkQuery: ShortLinkQuery;
  shortLinkRepository: ShortLinkRepository;
  statisticQueries: StatisticQueries;
  userRepository: UserRepository;
};
