import { ApiConsumerRepository } from "../../auth/ports/ApiConsumerRepository";
import { AgencyGroupRepository } from "../../convention/ports/AgencyGroupRepository";
import { AgencyRepository } from "../../convention/ports/AgencyRepository";
import { AssessmentRepository } from "../../convention/ports/AssessmentRepository";
import { ConventionExternalIdRepository } from "../../convention/ports/ConventionExternalIdRepository";
import { ConventionQueries } from "../../convention/ports/ConventionQueries";
import { ConventionRepository } from "../../convention/ports/ConventionRepository";
import { ConventionsToSyncRepository } from "../../convention/ports/ConventionsToSyncRepository";
import { InclusionConnectedUserRepository } from "../../dashboard/port/InclusionConnectedUserRepository";
import { AuthenticatedUserRepository } from "../../generic/OAuth/ports/AuthenticatedUserRepositiory";
import { OngoingOAuthRepository } from "../../generic/OAuth/ports/OngoingOAuthRepositiory";
import { DeletedEstablishmentRepository } from "../../offer/ports/DeletedEstablishmentRepository";
import { DiscussionAggregateRepository } from "../../offer/ports/DiscussionAggregateRepository";
import { EstablishmentAggregateRepository } from "../../offer/ports/EstablishmentAggregateRepository";
import { EstablishmentLeadQueries } from "../../offer/ports/EstablishmentLeadQueries";
import { EstablishmentLeadRepository } from "../../offer/ports/EstablishmentLeadRepository";
import { FormEstablishmentRepository } from "../../offer/ports/FormEstablishmentRepository";
import { GroupRepository } from "../../offer/ports/GroupRepository";
import { SearchMadeRepository } from "../../offer/ports/SearchMadeRepository";
import { ConventionPoleEmploiAdvisorRepository } from "../../peConnect/port/ConventionPoleEmploiAdvisorRepository";
import { RomeRepository } from "../../rome/ports/RomeRepository";
import { OutboxQueries } from "../events/ports/OutboxQueries";
import { OutboxRepository } from "../events/ports/OutboxRepository";
import { NotificationRepository } from "../notifications/ports/NotificationRepository";
import { ShortLinkQuery } from "../short-link/ports/ShortLinkQuery";
import { ShortLinkRepository } from "../short-link/ports/ShortLinkRepository";
import { ErrorRepository } from "./ErrorRepository";
import { FeatureFlagRepository } from "./FeatureFlagRepository";

export type UnitOfWork = {
  agencyRepository: AgencyRepository;
  agencyGroupRepository: AgencyGroupRepository;
  apiConsumerRepository: ApiConsumerRepository;
  authenticatedUserRepository: AuthenticatedUserRepository;
  conventionPoleEmploiAdvisorRepository: ConventionPoleEmploiAdvisorRepository;
  conventionExternalIdRepository: ConventionExternalIdRepository;
  conventionQueries: ConventionQueries;
  conventionRepository: ConventionRepository;
  conventionsToSyncRepository: ConventionsToSyncRepository;
  deletedEstablishmentRepository: DeletedEstablishmentRepository;
  discussionAggregateRepository: DiscussionAggregateRepository;
  errorRepository: ErrorRepository;
  establishmentAggregateRepository: EstablishmentAggregateRepository;
  establishmentLeadRepository: EstablishmentLeadRepository;
  groupRepository: GroupRepository;
  featureFlagRepository: FeatureFlagRepository;
  formEstablishmentRepository: FormEstablishmentRepository;
  assessmentRepository: AssessmentRepository;
  inclusionConnectedUserRepository: InclusionConnectedUserRepository;
  notificationRepository: NotificationRepository;
  ongoingOAuthRepository: OngoingOAuthRepository;
  outboxQueries: OutboxQueries;
  outboxRepository: OutboxRepository;
  romeRepository: RomeRepository;
  searchMadeRepository: SearchMadeRepository;
  shortLinkQuery: ShortLinkQuery;
  shortLinkRepository: ShortLinkRepository;
  establishmentLeadQueries: EstablishmentLeadQueries;
};

export interface UnitOfWorkPerformer {
  perform: <T>(cb: (uow: UnitOfWork) => Promise<T>) => Promise<T>;
}
