import { AddressDto } from "shared";

export const seedAddresses: AddressDto[] = [
  {
    city: "Bourg-en-Bresse",
    postcode: "01000",
    streetNumberAndAddress: "323 Avenue de Parme",
    departmentCode: "01",
  },
  {
    city: "Montmerle-sur-Saône",
    postcode: "01090",
    streetNumberAndAddress: "1 Rue de Lyon",
    departmentCode: "01",
  },
  {
    city: "Soissons",
    postcode: "02200",
    streetNumberAndAddress: "18 Rue Richebourg",
    departmentCode: "02",
  },
  {
    city: "Saint-Quentin",
    postcode: "02100",
    streetNumberAndAddress: "83 Boulevard Jean Bouin",
    departmentCode: "02",
  },
  {
    city: "Cusset",
    postcode: "03300",
    streetNumberAndAddress: "13 Rue de la Constitution",
    departmentCode: "03",
  },
  {
    city: "Villefranche-d'Allier",
    postcode: "03430",
    streetNumberAndAddress: "18 Avenue du 8 Mai 1945",
    departmentCode: "03",
  },
  {
    city: "Barcelonnette",
    postcode: "04400",
    streetNumberAndAddress: "Avenue Watton de Ferry",
    departmentCode: "04",
  },
  {
    city: "Digne-les-Bains",
    postcode: "04000",
    streetNumberAndAddress: "",
    departmentCode: "04",
  },
  {
    city: "Ancelle",
    postcode: "05260",
    streetNumberAndAddress: "",
    departmentCode: "05",
  },
  {
    city: "Cannes",
    postcode: "06150",
    streetNumberAndAddress: "4 Rue des Frères Manina",
    departmentCode: "06",
  },
  {
    city: "Aiglun",
    postcode: "06910",
    streetNumberAndAddress: "1 Rue Mont Saint-Martin",
    departmentCode: "06",
  },
  {
    city: "Antibes",
    postcode: "06600",
    streetNumberAndAddress: "Première Avenue",
    departmentCode: "06",
  },
  {
    city: "Ajoux",
    postcode: "07000",
    streetNumberAndAddress: "",
    departmentCode: "07",
  },
  {
    city: "Annonay",
    postcode: "07100",
    streetNumberAndAddress: "6 Allée Nicolas Copernic",
    departmentCode: "07",
  },
  {
    city: "Bogny-sur-Meuse",
    postcode: "08120",
    streetNumberAndAddress: "84 Rue Maurice Louis",
    departmentCode: "08",
  },
  {
    city: "Carignan",
    postcode: "08110",
    streetNumberAndAddress: "6 Rue de Froide Fontaine",
    departmentCode: "08",
  },
  {
    city: "Albiès",
    postcode: "09310",
    streetNumberAndAddress: "Route Nationale 20",
    departmentCode: "09",
  },
  {
    city: "Bézac",
    postcode: "09100",
    streetNumberAndAddress: "Rue de Tremege",
    departmentCode: "09",
  },
  {
    city: "Bar-sur-Aube",
    postcode: "10200",
    streetNumberAndAddress: "9 Rue du Collège",
    departmentCode: "10",
  },
  {
    city: "Auxon",
    postcode: "10130",
    streetNumberAndAddress: "Rue du Péage",
    departmentCode: "10",
  },
  {
    city: "Bar-sur-Aube",
    postcode: "10200",
    streetNumberAndAddress: "55 Rue du Général de Gaulle",
    departmentCode: "10",
  },
  {
    city: "Berriac",
    postcode: "11000",
    streetNumberAndAddress: "62bis Avenue des Pyrénées",
    departmentCode: "11",
  },
  {
    city: "Bram",
    postcode: "11150",
    streetNumberAndAddress: "5 Rue Joliot Curie",
    departmentCode: "11",
  },
  {
    city: "Argences en Aubrac",
    postcode: "12420",
    streetNumberAndAddress: "Rue des Barrages",
    departmentCode: "12",
  },
  {
    city: "Baraqueville",
    postcode: "12160",
    streetNumberAndAddress: "Impasse du Sablas",
    departmentCode: "12",
  },
  {
    city: "Marseille",
    postcode: "13014",
    streetNumberAndAddress: "19 Rue Vacon",
    departmentCode: "13",
  },
  {
    city: "Aix-en-Provence",
    postcode: "13090",
    streetNumberAndAddress: "Avenue de l'Europe",
    departmentCode: "13",
  },
  {
    city: "10e Arrondissement",
    postcode: "13010",
    streetNumberAndAddress: "85 Avenue de la Capelette",
    departmentCode: "13",
  },
  {
    city: "12e Arrondissement",
    postcode: "13012",
    streetNumberAndAddress: "10 Rue du Docteur Cauvin",
    departmentCode: "13",
  },
  {
    city: "Argences",
    postcode: "14370",
    streetNumberAndAddress: "",
    departmentCode: "14",
  },
  {
    city: "Bayeux",
    postcode: "14400",
    streetNumberAndAddress: "2 Boulevard Maréchal Montgomery",
    departmentCode: "14",
  },
  {
    city: "Albepierre-Bredons",
    postcode: "15300",
    streetNumberAndAddress: "",
    departmentCode: "15",
  },
  {
    city: "Aurillac",
    postcode: "15000",
    streetNumberAndAddress: "Impasse Blaise Pascal",
    departmentCode: "15",
  },
  {
    city: "Angoulême",
    postcode: "16000",
    streetNumberAndAddress: "55 Boulevard de Bury",
    departmentCode: "16",
  },
  {
    city: "Aigre",
    postcode: "16140",
    streetNumberAndAddress: "21 Route de Tusson",
    departmentCode: "16",
  },
  {
    city: "Angoulême",
    postcode: "16000",
    streetNumberAndAddress: "Rue des Agriers",
    departmentCode: "16",
  },
  {
    city: "Aigrefeuille-d'Aunis",
    postcode: "17290",
    streetNumberAndAddress: "1 Rue du Fief Girard",
    departmentCode: "17",
  },
  {
    city: "Aytré",
    postcode: "17440",
    streetNumberAndAddress: "7 Rue Newton",
    departmentCode: "17",
  },
  {
    city: "Arcomps",
    postcode: "18200",
    streetNumberAndAddress: "",
    departmentCode: "18",
  },
  {
    city: "Aubigny-sur-Nère",
    postcode: "18700",
    streetNumberAndAddress: "27 Avenue de la Gare",
    departmentCode: "18",
  },
  {
    city: "Argentat-sur-Dordogne",
    postcode: "19400",
    streetNumberAndAddress: "14 Avenue Raymond Poincaré",
    departmentCode: "19",
  },
  {
    city: "Bassignac-le-Bas",
    postcode: "19430",
    streetNumberAndAddress: "Rue de la Borie Basse",
    departmentCode: "19",
  },
  {
    city: "Arcenant",
    postcode: "21700",
    streetNumberAndAddress: "Chemin du Prieuré",
    departmentCode: "21",
  },
  {
    city: "Arnay-le-Duc",
    postcode: "21230",
    streetNumberAndAddress: "1 Rue de la Première Armée Française",
    departmentCode: "21",
  },
  {
    city: "Bobital",
    postcode: "22100",
    streetNumberAndAddress: "19 Rue de la Corbinais",
    departmentCode: "22",
  },
  {
    city: "Lannion",
    postcode: "22300",
    streetNumberAndAddress: "Rue de l'Aérodrome",
    departmentCode: "22",
  },
  {
    city: "Guéret",
    postcode: "23000",
    streetNumberAndAddress: "Avenue Charles de Gaulle",
    departmentCode: "23",
  },
  {
    city: "Aubusson",
    postcode: "23200",
    streetNumberAndAddress: "27 Rue des Fusillés",
    departmentCode: "23",
  },
  {
    city: "Aubusson",
    postcode: "23200",
    streetNumberAndAddress: "Espace Charles de Gaulle",
    departmentCode: "23",
  },
  {
    city: "Antonne-et-Trigonant",
    postcode: "24420",
    streetNumberAndAddress: "37 Route de Limoges",
    departmentCode: "24",
  },
  {
    city: "Baneuil",
    postcode: "24150",
    streetNumberAndAddress: "700 Route de Bergerac",
    departmentCode: "24",
  },
  {
    city: "Arc-sous-Cicon",
    postcode: "25520",
    streetNumberAndAddress: "24 Rue des Combes",
    departmentCode: "25",
  },
  {
    city: "Montbéliard",
    postcode: "25200",
    streetNumberAndAddress: "15 Rue de la Petite Hollande",
    departmentCode: "25",
  },
  {
    city: "Alixan",
    postcode: "26300",
    streetNumberAndAddress: "Avenue de la Gare",
    departmentCode: "26",
  },
  {
    city: "Beaumont-lès-Valence",
    postcode: "26760",
    streetNumberAndAddress: "Route de Valence",
    departmentCode: "26",
  },
  {
    city: "Bernay",
    postcode: "27300",
    streetNumberAndAddress: "28 Rue Guillaume de la Tremblaye",
    departmentCode: "27",
  },
  {
    city: "Bernay",
    postcode: "27300",
    streetNumberAndAddress: "Rue du Bois du Cours",
    departmentCode: "27",
  },
  {
    city: "Arcisses",
    postcode: "28400",
    streetNumberAndAddress: "Avenue de Paris",
    departmentCode: "28",
  },
  {
    city: "Auneau-Bleury-Saint-Symphorien",
    postcode: "28700",
    streetNumberAndAddress: "Avenue Gambetta",
    departmentCode: "28",
  },
  {
    city: "Audierne",
    postcode: "29770",
    streetNumberAndAddress: "94 Rue du 14 Juillet",
    departmentCode: "29",
  },
  {
    city: "Audierne",
    postcode: "29770",
    streetNumberAndAddress: "",
    departmentCode: "29",
  },
  {
    city: "Quimper",
    postcode: "29000",
    streetNumberAndAddress: "43 Rue du Président Sadate",
    departmentCode: "29",
  },
  {
    city: "Ajaccio",
    postcode: "20000",
    streetNumberAndAddress: "5 Boulevard du Roi Jérôme",
    departmentCode: "2A",
  },
  {
    city: "Ajaccio",
    postcode: "20000",
    streetNumberAndAddress: "Alzo-di-leva",
    departmentCode: "2A",
  },
  {
    city: "Bastia",
    postcode: "20297",
    streetNumberAndAddress: "11 Boulevard Benoîte Danesi",
    departmentCode: "2B",
  },
  {
    city: "Bastia",
    postcode: "20200",
    streetNumberAndAddress: "10bis Avenue Emile Sari",
    departmentCode: "2B",
  },
  {
    city: "Nîmes",
    postcode: "30900",
    streetNumberAndAddress: "281 Chemin du Mas Coquillard",
    departmentCode: "30",
  },
  {
    city: "Aigues-Mortes",
    postcode: "30220",
    streetNumberAndAddress: "10 Avenue des Artisans",
    departmentCode: "30",
  },
  {
    city: "Alès",
    postcode: "30100",
    streetNumberAndAddress: "84 Chemin des Fours à Chaux",
    departmentCode: "30",
  },
  {
    city: "Toulouse",
    postcode: "31100",
    streetNumberAndAddress: "8 Rue Paul Mesple",
    departmentCode: "31",
  },
  {
    city: "Ausson",
    postcode: "31210",
    streetNumberAndAddress: "1 Rue des Serres",
    departmentCode: "31",
  },
  {
    city: "Aucamville",
    postcode: "31140",
    streetNumberAndAddress: "33 Route de Paris",
    departmentCode: "31",
  },
  {
    city: "Auch",
    postcode: "32000",
    streetNumberAndAddress: "Impasse de l'Arçon",
    departmentCode: "32",
  },
  {
    city: "Auch",
    postcode: "32000",
    streetNumberAndAddress: "",
    departmentCode: "32",
  },
  {
    city: "Abzac",
    postcode: "33230",
    streetNumberAndAddress: "1 Rue du Docteur Texier",
    departmentCode: "33",
  },
  {
    city: "Canéjan",
    postcode: "33610",
    streetNumberAndAddress: "Chemin de la House",
    departmentCode: "33",
  },
  {
    city: "Ambès",
    postcode: "33810",
    streetNumberAndAddress: "Route du Burck",
    departmentCode: "33",
  },
  {
    city: "Montpellier",
    postcode: "34000",
    streetNumberAndAddress: "355 Rue Vendémiaire",
    departmentCode: "34",
  },
  {
    city: "Agde",
    postcode: "34300",
    streetNumberAndAddress: "Boulevard Maurice Pacull",
    departmentCode: "34",
  },
  {
    city: "Agde",
    postcode: "34300",
    streetNumberAndAddress: "Boulevard du Soleil",
    departmentCode: "34",
  },
  {
    city: "Acigné",
    postcode: "35690",
    streetNumberAndAddress: "",
    departmentCode: "35",
  },
  {
    city: "Argentré-du-Plessis",
    postcode: "35370",
    streetNumberAndAddress: "21 bis Rue du Général Leclerc",
    departmentCode: "35",
  },
  {
    city: "Ardentes",
    postcode: "36120",
    streetNumberAndAddress: "23bis Rue de la Gare",
    departmentCode: "36",
  },
  {
    city: "Ardentes",
    postcode: "36120",
    streetNumberAndAddress: "23bis Rue de la Gare",
    departmentCode: "36",
  },
  {
    city: "Amboise",
    postcode: "37400",
    streetNumberAndAddress: "Avenue Léonard de Vinci",
    departmentCode: "37",
  },
  {
    city: "Amboise",
    postcode: "37400",
    streetNumberAndAddress: "7bis Rue Jean-jacques Rousseau",
    departmentCode: "37",
  },
  {
    city: "Tours",
    postcode: "37550",
    streetNumberAndAddress: "Rue Schiller",
    departmentCode: "37",
  },
  {
    city: "Aoste",
    postcode: "38490",
    streetNumberAndAddress: "14 Passage des Géraniums",
    departmentCode: "38",
  },
  {
    city: "Assieu",
    postcode: "38150",
    streetNumberAndAddress: "91 Rue de la Charinas",
    departmentCode: "38",
  },
  {
    city: "Dole",
    postcode: "39100",
    streetNumberAndAddress: "24 Place Nationale Charles de Gaulle",
    departmentCode: "39",
  },
  {
    city: "Sellières",
    postcode: "39230",
    streetNumberAndAddress: "Rue d'Osse",
    departmentCode: "39",
  },
  {
    city: "Arinthod",
    postcode: "39240",
    streetNumberAndAddress: "15 Rue des Tilleuls",
    departmentCode: "39",
  },
  {
    city: "Aromas",
    postcode: "39240",
    streetNumberAndAddress: "",
    departmentCode: "39",
  },
  {
    city: "Aire-sur-l'Adour",
    postcode: "40800",
    streetNumberAndAddress: "Avenue de Bordeaux",
    departmentCode: "40",
  },
  {
    city: "Aire-sur-l'Adour",
    postcode: "40800",
    streetNumberAndAddress: "17 Rue Carnot",
    departmentCode: "40",
  },
  {
    city: "Vendôme",
    postcode: "41100",
    streetNumberAndAddress: "1 Rue Charles Péguy",
    departmentCode: "41",
  },
  {
    city: "Azé",
    postcode: "41100",
    streetNumberAndAddress: "3 Rue de Buissay",
    departmentCode: "41",
  },
  {
    city: "Bauzy",
    postcode: "41250",
    streetNumberAndAddress: "4 Route de Vernou",
    departmentCode: "41",
  },
  {
    city: "Andrézieux-Bouthéon",
    postcode: "42160",
    streetNumberAndAddress: "2 Rue Georges Guynemer",
    departmentCode: "42",
  },
  {
    city: "Andrézieux-Bouthéon",
    postcode: "42160",
    streetNumberAndAddress: "Rond-Point Auguste Colonna",
    departmentCode: "42",
  },
  {
    city: "Brioude",
    postcode: "43100",
    streetNumberAndAddress: "30 Avenue de Lamothe",
    departmentCode: "43",
  },
  {
    city: "Brives-Charensac",
    postcode: "43700",
    streetNumberAndAddress: "10 Rue des Dentellieres",
    departmentCode: "43",
  },
  {
    city: "Abbaretz",
    postcode: "44170",
    streetNumberAndAddress: "8 Place de l'Église",
    departmentCode: "44",
  },
  {
    city: "Aigrefeuille-sur-Maine",
    postcode: "44140",
    streetNumberAndAddress: "36 Avenue de la Vendée",
    departmentCode: "44",
  },
  {
    city: "Amilly",
    postcode: "45200",
    streetNumberAndAddress: "1419 Route de Viroy",
    departmentCode: "45",
  },
  {
    city: "Amilly",
    postcode: "45200",
    streetNumberAndAddress: "488 Rue du Chesnoy",
    departmentCode: "45",
  },
  {
    city: "Cahors",
    postcode: "46000",
    streetNumberAndAddress: "252 Avenue Jean Jaurès",
    departmentCode: "46",
  },
  {
    city: "Cahors",
    postcode: "46000",
    streetNumberAndAddress: "Riviere de Saint Mary",
    departmentCode: "46",
  },
  {
    city: "Agen",
    postcode: "47000",
    streetNumberAndAddress: "70 Boulevard Sylvain Dumon",
    departmentCode: "47",
  },
  {
    city: "Agen",
    postcode: "47000",
    streetNumberAndAddress: "7 Cours du 14 Juillet",
    departmentCode: "47",
  },
  {
    city: "Agen",
    postcode: "47000",
    streetNumberAndAddress: "1 Rue Tapie",
    departmentCode: "47",
  },
  {
    city: "Fournels",
    postcode: "48310",
    streetNumberAndAddress: "",
    departmentCode: "48",
  },
  {
    city: "Hures-la-Parade",
    postcode: "48150",
    streetNumberAndAddress: "",
    departmentCode: "48",
  },
  {
    city: "Angers",
    postcode: "49100",
    streetNumberAndAddress: "39 Boulevard Pierre de Coubertin",
    departmentCode: "49",
  },
  {
    city: "Angers",
    postcode: "49100",
    streetNumberAndAddress: "34 Boulevard des Deux Croix",
    departmentCode: "49",
  },
  {
    city: "Agneaux",
    postcode: "50180",
    streetNumberAndAddress: "14 Rue Jacques Prévert",
    departmentCode: "50",
  },
  {
    city: "Agon-Coutainville",
    postcode: "50230",
    streetNumberAndAddress: "70 Avenue du Passous",
    departmentCode: "50",
  },
  {
    city: "Avenay-Val-d'Or",
    postcode: "51160",
    streetNumberAndAddress: "1 Avenue Pierre Dubois",
    departmentCode: "51",
  },
  {
    city: "Aÿ-Champagne",
    postcode: "51160",
    streetNumberAndAddress: "Place Henri Martin",
    departmentCode: "51",
  },
  {
    city: "Langres",
    postcode: "52200",
    streetNumberAndAddress: "Ruelle de la Poterne",
    departmentCode: "52",
  },
  {
    city: "Bourbonne-les-Bains",
    postcode: "52400",
    streetNumberAndAddress: "Rue Maurice Constantin Weyer",
    departmentCode: "52",
  },
  {
    city: "Chalindrey",
    postcode: "52600",
    streetNumberAndAddress:
      "rue des Moulières - zone industrielle Les Moulières",
    departmentCode: "52",
  },
  {
    city: "Andouillé",
    postcode: "53240",
    streetNumberAndAddress: "5 Rue de l'Hôtel de Ville",
    departmentCode: "53",
  },
  {
    city: "Bonchamp-lès-Laval",
    postcode: "53960",
    streetNumberAndAddress: "",
    departmentCode: "53",
  },
  {
    city: "Val de Briey",
    postcode: "54150",
    streetNumberAndAddress: "40 Rue Carnot",
    departmentCode: "54",
  },
  {
    city: "Auboué",
    postcode: "54580",
    streetNumberAndAddress: "18 Rue des Martyrs",
    departmentCode: "54",
  },
  {
    city: "Baccarat",
    postcode: "54120",
    streetNumberAndAddress: "41 Rue Adrien Michaut",
    departmentCode: "54",
  },
  {
    city: "Bar-le-Duc",
    postcode: "55000",
    streetNumberAndAddress: "Place de la République",
    departmentCode: "55",
  },
  {
    city: "Bar-le-Duc",
    postcode: "55000",
    streetNumberAndAddress: "77 Rue Ernest Bradfer",
    departmentCode: "55",
  },
  {
    city: "Plouharnel",
    departmentCode: "56",
    postcode: "56340",
    streetNumberAndAddress: "5 Kerhueno",
  },
  {
    city: "Allaire",
    postcode: "56350",
    streetNumberAndAddress: "14 Rue de la Libération",
    departmentCode: "56",
  },
  {
    city: "Auray",
    postcode: "56400",
    streetNumberAndAddress: "22 Place du Maréchal Joffre",
    departmentCode: "56",
  },
  {
    city: "Amnéville",
    postcode: "57360",
    streetNumberAndAddress: "1 Rue du Tigre",
    departmentCode: "57",
  },
  {
    city: "Amnéville",
    postcode: "57360",
    streetNumberAndAddress: "Rue du Vieil Amnéville",
    departmentCode: "57",
  },
  {
    city: "Châtillon-en-Bazois",
    postcode: "58110",
    streetNumberAndAddress: "Place de l'Église",
    departmentCode: "58",
  },
  {
    city: "Chevenon",
    postcode: "58160",
    streetNumberAndAddress: "Les Rondes",
    departmentCode: "58",
  },
  {
    city: "Lille",
    departmentCode: "59",
    postcode: "59000",
    streetNumberAndAddress: "299 Boulevard de Leeds",
  },
  {
    city: "Aniche",
    postcode: "59580",
    streetNumberAndAddress: "7 Bd Paul Vaillant Couturier",
    departmentCode: "59",
  },
  {
    city: "Aniche",
    postcode: "59580",
    streetNumberAndAddress: "128 Rue du General Delestraint",
    departmentCode: "59",
  },
  {
    city: "Beauvais",
    postcode: "60000",
    streetNumberAndAddress: "",
    departmentCode: "60",
  },
  {
    city: "Beauvais",
    postcode: "60000",
    streetNumberAndAddress: "18 Impasse Bernard Palissy",
    departmentCode: "60",
  },
  {
    city: "Alençon",
    postcode: "61000",
    streetNumberAndAddress: "Rue de l'Abbé Letacq",
    departmentCode: "61",
  },
  {
    city: "Alençon",
    postcode: "61000",
    streetNumberAndAddress: "",
    departmentCode: "61",
  },
  {
    city: "Acquin-Westbécourt",
    postcode: "62380",
    streetNumberAndAddress: "Chemin des Bois",
    departmentCode: "62",
  },
  {
    city: "Aire-sur-la-Lys",
    postcode: "62120",
    streetNumberAndAddress: "9 Rue du Général Leclerc",
    departmentCode: "62",
  },
  {
    city: "Ambert",
    postcode: "63600",
    streetNumberAndAddress: "2 Allée du Parc",
    departmentCode: "63",
  },
  {
    city: "Aubière",
    postcode: "63170",
    streetNumberAndAddress: "Rue des Varennes",
    departmentCode: "63",
  },
  {
    city: "Pau",
    departmentCode: "64",
    postcode: "64000",
    streetNumberAndAddress: "Rue Vincent Auriol",
  },
  {
    city: "Anglet",
    postcode: "64600",
    streetNumberAndAddress: "96 Avenue de l' Adour",
    departmentCode: "64",
  },
  {
    city: "Anglet",
    postcode: "64600",
    streetNumberAndAddress: "1 Rue du Moulin de Brindos",
    departmentCode: "64",
  },
  {
    city: "Argelès-Gazost",
    postcode: "65400",
    streetNumberAndAddress: "Avenue Adrien Hébrard",
    departmentCode: "65",
  },
  {
    city: "Aureilhan",
    postcode: "65800",
    streetNumberAndAddress: "2 Avenue du Bois",
    departmentCode: "65",
  },
  {
    city: "Alénya",
    postcode: "66200",
    streetNumberAndAddress: "Rue Louis Noguères",
    departmentCode: "66",
  },
  {
    city: "Argelès-sur-Mer",
    postcode: "66700",
    streetNumberAndAddress: "Chemin del Pas de las Baques",
    departmentCode: "66",
  },
  {
    city: "Barr",
    postcode: "67140",
    streetNumberAndAddress: "43 Avenue des Vosges",
    departmentCode: "67",
  },
  {
    city: "Benfeld",
    postcode: "67230",
    streetNumberAndAddress: "4 Rue de Suède",
    departmentCode: "67",
  },
  {
    city: "Altkirch",
    postcode: "68130",
    streetNumberAndAddress: "8 Place des 3 Rois",
    departmentCode: "68",
  },
  {
    city: "Altkirch",
    postcode: "68130",
    streetNumberAndAddress: "5 Place de la République",
    departmentCode: "68",
  },
  {
    city: "Anse",
    postcode: "69480",
    streetNumberAndAddress: "Avenue de Lossburg",
    departmentCode: "69",
  },
  {
    city: "Beaujeu",
    postcode: "69430",
    streetNumberAndAddress: "",
    departmentCode: "69",
  },
  {
    city: "Arc-lès-Gray",
    postcode: "70100",
    streetNumberAndAddress: "Rue de Rigny -ZI Les Giranaux",
    departmentCode: "70",
  },
  {
    city: "Avrigney-Virey",
    postcode: "70150",
    streetNumberAndAddress: "Route de Marnay",
    departmentCode: "70",
  },
  {
    city: "Autun",
    postcode: "71400",
    streetNumberAndAddress: "Rue des Pierres",
    departmentCode: "71",
  },
  {
    city: "Autun",
    postcode: "71400",
    streetNumberAndAddress: "Boulevard Bernard Giberstein",
    departmentCode: "71",
  },
  {
    city: "Allonnes",
    postcode: "72700",
    streetNumberAndAddress: "14 Rue Albert Einstein",
    departmentCode: "72",
  },
  {
    city: "Allonnes",
    postcode: "72700",
    streetNumberAndAddress: "10 Rue des Acacias",
    departmentCode: "72",
  },
  {
    city: "Aime-la-Plagne",
    postcode: "73210",
    streetNumberAndAddress: "540 Avenue de la Tarentaise",
    departmentCode: "73",
  },
  {
    city: "Aiton",
    postcode: "73220",
    streetNumberAndAddress: "Chemin du Clos",
    departmentCode: "73",
  },
  {
    city: "Annecy",
    postcode: "74000",
    streetNumberAndAddress: "4 Avenue de Genève",
    departmentCode: "74",
  },
  {
    city: "Annecy",
    postcode: "74940",
    streetNumberAndAddress: "Route de Thônes",
    departmentCode: "74",
  },
  {
    city: "Paris",
    departmentCode: "75",
    postcode: "75001",
    streetNumberAndAddress: "1 rue de Rivoli",
  },
  {
    city: "Paris",
    postcode: "75018",
    streetNumberAndAddress: "189 Rue d'Aubervilliers",
    departmentCode: "75",
  },
  {
    city: "Paris",
    postcode: "75012",
    streetNumberAndAddress: "Rue Abel",
    departmentCode: "75",
  },
  {
    city: "Paris",
    postcode: "75017",
    streetNumberAndAddress: "21 Rue Biot",
    departmentCode: "75",
  },
  {
    city: "Elbeuf",
    postcode: "76500",
    streetNumberAndAddress: "39 Rue Poussin",
    departmentCode: "76",
  },
  {
    city: "Allouville-Bellefosse",
    postcode: "76190",
    streetNumberAndAddress: "Rue Michel Simon",
    departmentCode: "76",
  },
  {
    city: "Arelaune-en-Seine",
    postcode: "76940",
    streetNumberAndAddress: "Route des Maraichers",
    departmentCode: "76",
  },
  {
    city: "Bouleurs",
    postcode: "77580",
    streetNumberAndAddress: "Rue de Montpichet",
    departmentCode: "77",
  },
  {
    city: "Bussy-Saint-Georges",
    postcode: "77600",
    streetNumberAndAddress: "1 Rue Raoul Follereau",
    departmentCode: "77",
  },
  {
    city: "Achères",
    postcode: "78260",
    streetNumberAndAddress: "Lieudit Chemin Neuf",
    departmentCode: "78",
  },
  {
    city: "Achères",
    postcode: "78260",
    streetNumberAndAddress: "Allée Marivaux",
    departmentCode: "78",
  },
  {
    city: "Airvault",
    postcode: "79600",
    streetNumberAndAddress: "16T Rue Emmanuel Bonnet",
    departmentCode: "79",
  },
  {
    city: "Argentonnay",
    postcode: "79150",
    streetNumberAndAddress: "38 Avenue du Général de Gaulle",
    departmentCode: "79",
  },
  {
    city: "Dury",
    postcode: "80480",
    streetNumberAndAddress: "Allée des Fleurs - Oasis",
    departmentCode: "80",
  },
  {
    city: "Abbeville",
    postcode: "80100",
    streetNumberAndAddress: "30 Chaussée Marcadé",
    departmentCode: "80",
  },
  {
    city: "Abbeville",
    postcode: "80100",
    streetNumberAndAddress: "Grande Rue de Thuison",
    departmentCode: "80",
  },
  {
    city: "Albi",
    postcode: "81000",
    streetNumberAndAddress: "152 Avenue Maréchal de Lattre de Tassigny",
    departmentCode: "81",
  },
  {
    city: "Albi",
    postcode: "81000",
    streetNumberAndAddress: "2 Rue Francisco Goya",
    departmentCode: "81",
  },
  {
    city: "Albias",
    postcode: "82350",
    streetNumberAndAddress: "2901 Route de Cos",
    departmentCode: "82",
  },
  {
    city: "Castelsarrasin",
    postcode: "82100",
    streetNumberAndAddress: "9 Rue de la Paix",
    departmentCode: "82",
  },
  {
    city: "Aups",
    postcode: "83630",
    streetNumberAndAddress: "Z.A. Les Uchanes Route de Salernes",
    departmentCode: "83",
  },
  {
    city: "Barjols",
    postcode: "83670",
    streetNumberAndAddress: "Chemin de Saint-Lazare",
    departmentCode: "83",
  },
  {
    city: "Althen-des-Paluds",
    postcode: "84210",
    streetNumberAndAddress: "83 Route des Gaffins",
    departmentCode: "84",
  },
  {
    city: "Apt",
    postcode: "84400",
    streetNumberAndAddress: "Place de la Bouquerie",
    departmentCode: "84",
  },
  {
    city: "Aizenay",
    postcode: "85190",
    streetNumberAndAddress: "Avenue de Verdun",
    departmentCode: "85",
  },
  {
    city: "Aizenay",
    postcode: "85190",
    streetNumberAndAddress: "146 Rue de la roche",
    departmentCode: "85",
  },
  {
    city: "Adriers",
    postcode: "86430",
    streetNumberAndAddress: "2 Rue Garestier Lapierre",
    departmentCode: "86",
  },
  {
    city: "Béruges",
    postcode: "86190",
    streetNumberAndAddress: "24 Route des Cours",
    departmentCode: "86",
  },
  {
    city: "Aixe-sur-Vienne",
    postcode: "87700",
    streetNumberAndAddress: "28 Avenue Jean Rebier",
    departmentCode: "87",
  },
  {
    city: "Aixe-sur-Vienne",
    postcode: "87700",
    streetNumberAndAddress: "57 Avenue du Président Wilson",
    departmentCode: "87",
  },
  {
    city: "Anould",
    postcode: "88650",
    streetNumberAndAddress: "37 Rue de Saint-dié",
    departmentCode: "88",
  },
  {
    city: "Charmes",
    postcode: "88130",
    streetNumberAndAddress: "Place Henri Breton",
    departmentCode: "88",
  },
  {
    city: "Appoigny",
    postcode: "89380",
    streetNumberAndAddress: "60 Route d'Auxerre",
    departmentCode: "89",
  },
  {
    city: "Auxerre",
    postcode: "89000",
    streetNumberAndAddress: "5 Avenue Gambetta",
    departmentCode: "89",
  },
  {
    city: "Bavilliers",
    postcode: "90800",
    streetNumberAndAddress: "",
    departmentCode: "90",
  },
  {
    city: "Bavilliers",
    postcode: "90800",
    streetNumberAndAddress: "47 Grande Rue François Mitterrand",
    departmentCode: "90",
  },
  {
    city: "Athis-Mons",
    postcode: "91200",
    streetNumberAndAddress: "4 Rue G Anthonioz de Gaulle",
    departmentCode: "91",
  },
  {
    city: "Athis-Mons",
    postcode: "91200",
    streetNumberAndAddress: "50 Avenue François Mitterrand",
    departmentCode: "91",
  },
  {
    city: "Antony",
    postcode: "92160",
    streetNumberAndAddress: "Rue Alexis de Tocqueville",
    departmentCode: "92",
  },
  {
    city: "Antony",
    postcode: "92160",
    streetNumberAndAddress: "Rue Luigi Galvani",
    departmentCode: "92",
  },
  {
    city: "Villetaneuse",
    postcode: "93430",
    streetNumberAndAddress: "6 RUE RAYMOND BROSSE",
    departmentCode: "93",
  },
  {
    city: "Aubervilliers",
    postcode: "93300",
    streetNumberAndAddress: "161 Avenue Victor Hugo",
    departmentCode: "93",
  },
  {
    city: "Aubervilliers",
    postcode: "93300",
    streetNumberAndAddress: "99 Rue Heurtault",
    departmentCode: "93",
  },
  {
    city: "Alfortville",
    postcode: "94140",
    streetNumberAndAddress: "4 Quai Blanqui",
    departmentCode: "94",
  },
  {
    city: "Arcueil",
    postcode: "94110",
    streetNumberAndAddress: "",
    departmentCode: "94",
  },
  {
    city: "Beauchamp",
    postcode: "95250",
    streetNumberAndAddress: "Chaussée Jules César",
    departmentCode: "95",
  },
  {
    city: "Cergy",
    postcode: "95000",
    streetNumberAndAddress: "3 Allée de l'Etoile",
    departmentCode: "95",
  },
  {
    city: "Anse-Bertrand",
    postcode: "97121",
    streetNumberAndAddress: "",
    departmentCode: "971",
  },
  {
    city: "Baie-Mahault",
    postcode: "97122",
    streetNumberAndAddress: "Impasse Augustin Fresnel",
    departmentCode: "971",
  },
  {
    city: "Ducos",
    postcode: "97224",
    streetNumberAndAddress: "ZI de Champigny",
    departmentCode: "972",
  },
  {
    city: "Fort-de-France",
    postcode: "97200",
    streetNumberAndAddress: "10 Avenue des Arawaks",
    departmentCode: "972",
  },
  {
    city: "Cayenne",
    postcode: "97300",
    streetNumberAndAddress: "Place de l'Esplanade",
    departmentCode: "973",
  },
  {
    city: "Cayenne",
    postcode: "97300",
    streetNumberAndAddress: "30 Rue Albert Darnal",
    departmentCode: "973",
  },
  {
    city: "Cayenne",
    postcode: "97300",
    streetNumberAndAddress: "Rocade de Zéphir",
    departmentCode: "973",
  },
  {
    city: "Bras-Panon",
    postcode: "97412",
    streetNumberAndAddress: "1bis Rue Roberto",
    departmentCode: "974",
  },
  {
    city: "Bras-Panon",
    postcode: "97412",
    streetNumberAndAddress: "7 Rue des Goyaviers",
    departmentCode: "974",
  },
  {
    city: "Chiconi",
    postcode: "97670",
    streetNumberAndAddress: "204 Chemin de la Joie",
    departmentCode: "976",
  },
  {
    city: "Bandrélé",
    postcode: "97660",
    streetNumberAndAddress: "117 Rue Tourne Dos",
    departmentCode: "976",
  },
];
