const frontPort = 3000;

export const e2eBackendEnv = {
  NODE_ENV: "local",
  NOTIFICATION_GATEWAY: "IN_MEMORY",
  ESTABLISHMENT_MARKETING_GATEWAY: "IN_MEMORY",
  ADDRESS_API_GATEWAY: "OPEN_CAGE_DATA",
  PRO_CONNECT_GATEWAY: "HTTPS",
  PRO_CONNECT_CLIENT_ID: "449e24c6-b5aa-4435-bb8c-728d4a3c1c94",
  PRO_CONNECT_BASE_URI: "https://fca.integ01.dev-agentconnect.fr/api/v2",
  POLE_EMPLOI_GATEWAY: "IN_MEMORY",
  LA_BONNE_BOITE_GATEWAY: "IN_MEMORY",
  PASS_EMPLOI_GATEWAY: "IN_MEMORY",
  PDF_GENERATOR_GATEWAY: "IN_MEMORY",
  SHORT_LINK_ID_GENERATOR_GATEWAY: "NANO_ID",
  JWT_PRIVATE_KEY:
    "-----BEGIN PRIVATE KEY-----\nMIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgevZzL1gdAFr88hb2\nOF/2NxApJCzGCEDdfSp6VQO30hyhRANCAAQRWz+jn65BtOMvdyHKcvjBeBSDZH2r\n1RTwjmYSi9R/zpBnuQ4EiMnCqfMPWiZqB4QdbAd0E7oH50VpuZ1P087G\n-----END PRIVATE KEY-----",
  JWT_PUBLIC_KEY:
    "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEEVs/o5+uQbTjL3chynL4wXgUg2R9\nq9UU8I5mEovUf86QZ7kOBIjJwqnzD1omageEHWwHdBO6B+dFabmdT9POxg==\n-----END PUBLIC KEY-----\n",
  API_JWT_PRIVATE_KEY:
    "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIPnK7kOKC6VqJwmsXCcCgNfVEAMyt0IFm68g/dwg3/iVoAoGCCqGSM49\nAwEHoUQDQgAEXNo97BD4w2huuAYsmINnn/+TPolxYUexkcD49YyxsjJPA2d91B2r\nDzteUKnEsloNYDTeYW88oLPMdgmbzm+sQg==\n-----END EC PRIVATE KEY-----",
  API_JWT_PUBLIC_KEY:
    "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEXNo97BD4w2huuAYsmINnn/+TPolx\nYUexkcD49YyxsjJPA2d91B2rDzteUKnEsloNYDTeYW88oLPMdgmbzm+sQg==\n-----END PUBLIC KEY-----",
  DOMAIN: `localhost:${frontPort}`,
  REPOSITORIES: "PG",
  INBOUND_EMAIL_ALLOWED_IPS: "::ffff:127.0.0.1",
  SIRENE_REPOSITORY: "ANNUAIRE_DES_ENTREPRISES",
  SIRENE_INSEE_ENDPOINT: "https://api.insee.fr/api-sirene/prive/3.11",
  EVENT_CRAWLER_PERIOD_MS: "600",
  EXTERNAL_AXIOS_TIMEOUT: "30000",
  CACHE: "NONE",
};

export { frontPort };
