const frontPort = 3000;
const backPort = 1234;

export const e2eBackendEnv = {
  NODE_ENV: "local",
  NOTIFICATION_GATEWAY: "IN_MEMORY",
  ESTABLISHMENT_MARKETING_GATEWAY: "IN_MEMORY",
  ADDRESS_API_GATEWAY: "OPEN_CAGE_DATA",
  PRO_CONNECT_GATEWAY: "HTTPS",
  PRO_CONNECT_CLIENT_ID: "449e24c6-b5aa-4435-bb8c-728d4a3c1c94",
  PRO_CONNECT_BASE_URI: "https://fca.integ01.dev-agentconnect.fr/api/v2",
  POLE_EMPLOI_GATEWAY: "IN_MEMORY",
  LA_BONNE_BOITE_GATEWAY: "IN_MEMORY",
  PASS_EMPLOI_GATEWAY: "IN_MEMORY",
  PDF_GENERATOR_GATEWAY: "IN_MEMORY",
  SHORT_LINK_ID_GENERATOR_GATEWAY: "NANO_ID",
  DOMAIN: `localhost:${frontPort}`,
  REPOSITORIES: "PG",
  INBOUND_EMAIL_ALLOWED_IPS: "::ffff:127.0.0.1",
  SIRENE_REPOSITORY: "ANNUAIRE_DES_ENTREPRISES",
  SIRENE_INSEE_ENDPOINT: "https://api.insee.fr/api-sirene/prive/3.11",
  EVENT_CRAWLER_PERIOD_MS: "600",
  EXTERNAL_AXIOS_TIMEOUT: "30000",
  CACHE: "NONE",
};

export { backPort, frontPort };
