immersion_bi:
  target: db
  outputs:
    db:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      user: "{{ env_var('DBT_USER', 'immersion') }}"
      password: "{{ env_var('DBT_PASSWORD', 'pg_password') }}"
      port: "{{ env_var('DBT_PORT', 5432) | as_number }}"
      dbname: "{{ env_var('DBT_DATABASE', 'immersion-db') }}"
      schema: public
      threads: 4
