version: 2

models:
  - name: most_frequent_searches
    description: "Top 1000 most frequent searches per day (last year). Passthrough from stats table."
    columns:
      - name: day
        description: "Date of the searches"
        tests:
          - not_null
      - name: appellation_code
        description: "Appellation code searched"
      - name: address
        description: "Search address"
      - name: department_code
        description: "Department code"
      - name: count
        description: "Number of searches for this combination"
        tests:
          - not_null
