export const fakeCompaniesLaBonneBoite = [
  {
    address: "3 PLACE EDOUARD BRANLY, 57070 METZ",
    alternance: false,
    boosted: true,
    city: "METZ",
    contact_mode: "Envoyez votre candidature par mail",
    distance: 3.5,
    headcount_text: "3 à 5 salariés",
    lat: 49.1051,
    lon: 6.21908,
    matched_rome_code: "M1607",
    matched_rome_label: "Secrétariat",
    matched_rome_slug: "secretariat",
    naf: "8559A",
    naf_text: "Formation continue d'adultes",
    name: "A.F.LOR",
    siret: "53755201000036",
    social_network: "",
    stars: 2.5,
    url: "https://labonneboite.pole-emploi.fr/53755201000036/details?rome_code=M1607&utm_medium=web&utm_source=api__emploi_store_dev&utm_campaign=api__emploi_store_dev__limmersionfacile",
    website: "",
  },
  {
    address:
      "Service des ressources humaines,  IMPASSE FENDERIE, 57290 SEREMANGE-ERZANGE",
    alternance: false,
    boosted: false,
    city: "SEREMANGE-ERZANGE",
    contact_mode: "Envoyer un CV et une lettre de motivation",
    distance: 23.6,
    headcount_text: "50 à 99 salariés",
    lat: 49.3225,
    lon: 6.08067,
    matched_rome_code: "M1607",
    matched_rome_label: "Secrétariat",
    matched_rome_slug: "secretariat",
    naf: "8810C",
    naf_text: "Aide par le travail",
    name: "BLANCHISSERIE LA FENSCH",
    siret: "77561959600155",
    social_network: "",
    stars: 4.5,
    url: "https://labonneboite.pole-emploi.fr/77561959600155/details?rome_code=M1607&utm_medium=web&utm_source=api__emploi_store_dev&utm_campaign=api__emploi_store_dev__limmersionfacile",
    website: "",
  },
  {
    address:
      "Service des ressources humaines, 4 BOULEVARD DU PONTIFFROY, 57000 METZ",
    alternance: true,
    boosted: false,
    city: "METZ",
    contact_mode: "Envoyer un CV et une lettre de motivation",
    distance: 0.9,
    headcount_text: "250 à 499 salariés",
    lat: 49.1268,
    lon: 6.17762,
    matched_rome_code: "M1607",
    matched_rome_label: "Secrétariat",
    matched_rome_slug: "secretariat",
    naf: "8430C",
    naf_text: "Distribution sociale de revenus",
    name: "CAISSE D ALLOCATIONS FAMILIALES MOSELL",
    siret: "78000403200022",
    social_network: "",
    stars: 4.5,
    url: "https://labonneboite.pole-emploi.fr/78000403200022/details?rome_code=M1607&utm_medium=web&utm_source=api__emploi_store_dev&utm_campaign=api__emploi_store_dev__limmersionfacile",
    website: "",
  },
  {
    address: "Service des ressources humaines, 5 RUE D ANJOU, 57070 METZ",
    alternance: false,
    boosted: false,
    city: "METZ",
    contact_mode: "Envoyer un CV et une lettre de motivation",
    distance: 3.8,
    headcount_text: "100 à 199 salariés",
    lat: 49.1176,
    lon: 6.228,
    matched_rome_code: "M1607",
    matched_rome_label: "Secrétariat",
    matched_rome_slug: "secretariat",
    naf: "8810C",
    naf_text: "Aide par le travail",
    name: "ASSOCIATION METZ-POLE-SERVICES",
    siret: "43404758500030",
    social_network: "",
    stars: 4.5,
    url: "https://labonneboite.pole-emploi.fr/43404758500030/details?rome_code=M1607&utm_medium=web&utm_source=api__emploi_store_dev&utm_campaign=api__emploi_store_dev__limmersionfacile",
    website: "",
  },
  {
    address: " AVENUE DE LATTRE DE TASSIGNY, 57000 METZ",
    alternance: false,
    boosted: false,
    city: "METZ",
    contact_mode: "Envoyer un CV et une lettre de motivation",
    distance: 1.2,
    headcount_text: "",
    lat: 49.1102,
    lon: 6.16722,
    matched_rome_code: "M1607",
    matched_rome_label: "Secrétariat",
    matched_rome_slug: "secretariat",
    naf: "8422Z",
    naf_text: "Défense",
    name: "CENTRE MINISTERIEL DE GESTION DE METZ",
    siret: "15300003900377",
    social_network: "",
    stars: 4.5,
    url: "https://labonneboite.pole-emploi.fr/15300003900377/details?rome_code=M1607&utm_medium=web&utm_source=api__emploi_store_dev&utm_campaign=api__emploi_store_dev__limmersionfacile",
    website: "",
  },
  {
    address: "Service des ressources humaines, 1 RUE DES JARDINS, 57365 ENNERY",
    alternance: false,
    boosted: false,
    city: "ENNERY",
    contact_mode: "Envoyer un CV et une lettre de motivation",
    distance: 12.3,
    headcount_text: "20 à 49 salariés",
    lat: 49.2259,
    lon: 6.21902,
    matched_rome_code: "M1607",
    matched_rome_label: "Secrétariat",
    matched_rome_slug: "secretariat",
    naf: "8810A",
    naf_text: "Aide à domicile",
    name: "ALYS",
    siret: "78341433700213",
    social_network: "",
    stars: 4.5,
    url: "https://labonneboite.pole-emploi.fr/78341433700213/details?rome_code=M1607&utm_medium=web&utm_source=api__emploi_store_dev&utm_campaign=api__emploi_store_dev__limmersionfacile",
    website: "",
  },
  {
    address:
      "Service des ressources humaines, 2 ALLEE DU CHATEAU DU GASSION, 57100 THIONVILLE",
    alternance: true,
    boosted: false,
    city: "THIONVILLE",
    contact_mode: "Se présenter spontanément",
    distance: 24.8,
    headcount_text: "20 à 49 salariés",
    lat: 49.3421,
    lon: 6.15931,
    matched_rome_code: "M1607",
    matched_rome_label: "Secrétariat",
    matched_rome_slug: "secretariat",
    naf: "4511Z",
    naf_text: "Commerce de voitures et de véhicules automobiles légers",
    name: "DIETTERT GASSION SAS",
    siret: "78899515700013",
    social_network: "",
    stars: 4.4,
    url: "https://labonneboite.pole-emploi.fr/78899515700013/details?rome_code=M1607&utm_medium=web&utm_source=api__emploi_store_dev&utm_campaign=api__emploi_store_dev__limmersionfacile",
    website: "",
  },
  {
    address: "Service des ressources humaines, 1 RUE DE COURCELLES, 57070 METZ",
    alternance: false,
    boosted: false,
    city: "METZ",
    contact_mode: "Envoyer un CV et une lettre de motivation",
    distance: 5.3,
    headcount_text: "200 à 249 salariés",
    lat: 49.0926,
    lon: 6.23618,
    matched_rome_code: "M1607",
    matched_rome_label: "Secrétariat",
    matched_rome_slug: "secretariat",
    naf: "8621Z",
    naf_text: "Activité des médecins généralistes",
    name: "AGIR ENSEMBLE POUR LA SANTE AU TRAVAIL",
    siret: "87875821800027",
    social_network: "",
    stars: 4.6,
    url: "https://labonneboite.pole-emploi.fr/87875821800027/details?rome_code=M1607&utm_medium=web&utm_source=api__emploi_store_dev&utm_campaign=api__emploi_store_dev__limmersionfacile",
    website: "",
  },
  {
    address: "Service des ressources humaines, 11 RUE GASTON RAMON, 57050 METZ",
    alternance: false,
    boosted: false,
    city: "METZ",
    contact_mode: "Se présenter spontanément",
    distance: 2.4,
    headcount_text: "50 à 99 salariés",
    lat: 49.1404,
    lon: 6.17903,
    matched_rome_code: "M1607",
    matched_rome_label: "Secrétariat",
    matched_rome_slug: "secretariat",
    naf: "4799A",
    naf_text: "Vente à domicile",
    name: "BOFROST*FRANCE",
    siret: "41803776800177",
    social_network: "",
    stars: 4.4,
    url: "https://labonneboite.pole-emploi.fr/41803776800177/details?rome_code=M1607&utm_medium=web&utm_source=api__emploi_store_dev&utm_campaign=api__emploi_store_dev__limmersionfacile",
    website: "",
  },
  {
    address: "Service des ressources humaines,  PLACE DE MAUD HUY, 57000 METZ",
    alternance: false,
    boosted: false,
    city: "METZ",
    contact_mode: "Envoyer un CV et une lettre de motivation",
    distance: 1.3,
    headcount_text: "20 à 49 salariés",
    lat: 49.1089,
    lon: 6.16772,
    matched_rome_code: "M1607",
    matched_rome_label: "Secrétariat",
    matched_rome_slug: "secretariat",
    naf: "8531Z",
    naf_text: "Enseignement secondaire général",
    name: "LYCEE  GEN TECHNOLOG  GEORGES DE LA TO",
    siret: "19572757300014",
    social_network: "",
    stars: 4.4,
    url: "https://labonneboite.pole-emploi.fr/19572757300014/details?rome_code=M1607&utm_medium=web&utm_source=api__emploi_store_dev&utm_campaign=api__emploi_store_dev__limmersionfacile",
    website: "",
  },
  {
    address:
      "Service des ressources humaines, 2 AVENUE JULIEN ABSALON, 57970 YUTZ",
    alternance: true,
    boosted: false,
    city: "YUTZ",
    contact_mode: "Envoyer un CV et une lettre de motivation",
    distance: 25.7,
    headcount_text: "100 à 199 salariés",
    lat: 49.35,
    lon: 6.19898,
    matched_rome_code: "M1607",
    matched_rome_label: "Secrétariat",
    matched_rome_slug: "secretariat",
    naf: "8610Z",
    naf_text: "Activités hospitalières",
    name: "CLINIQUE SAINTE ELISABETH",
    siret: "78004244600085",
    social_network: "",
    stars: 4.4,
    url: "https://labonneboite.pole-emploi.fr/78004244600085/details?rome_code=M1607&utm_medium=web&utm_source=api__emploi_store_dev&utm_campaign=api__emploi_store_dev__limmersionfacile",
    website: "",
  },
  {
    address:
      "Service des ressources humaines, 5 RUE DE L ABBE GREGOIRE, 57050 METZ",
    alternance: false,
    boosted: false,
    city: "METZ",
    contact_mode: "Se présenter spontanément",
    distance: 3.1,
    headcount_text: "200 à 249 salariés",
    lat: 49.1473,
    lon: 6.17483,
    matched_rome_code: "M1607",
    matched_rome_label: "Secrétariat",
    matched_rome_slug: "secretariat",
    naf: "4939A",
    naf_text: "Transports routiers réguliers de voyageurs",
    name: "KEOLIS 3 FRONTIERES",
    siret: "57204202600060",
    social_network: "",
    stars: 4.5,
    url: "https://labonneboite.pole-emploi.fr/57204202600060/details?rome_code=M1607&utm_medium=web&utm_source=api__emploi_store_dev&utm_campaign=api__emploi_store_dev__limmersionfacile",
    website: "",
  },
  {
    address: "13 RUE DU FOUR, 54700 PONT-A-MOUSSON",
    alternance: false,
    boosted: false,
    city: "PONT-A-MOUSSON",
    contact_mode: "Envoyer un CV et une lettre de motivation",
    distance: 25.8,
    headcount_text: "1 ou 2 salariés",
    lat: 48.9004,
    lon: 6.05571,
    matched_rome_code: "M1607",
    matched_rome_label: "Secrétariat",
    matched_rome_slug: "secretariat",
    naf: "7830Z",
    naf_text: "Autre mise à disposition de ressources humaines",
    name: "SOLIDARITES SERVICES",
    siret: "41356562300027",
    social_network: "",
    stars: 4.4,
    url: "https://labonneboite.pole-emploi.fr/41356562300027/details?rome_code=M1607&utm_medium=web&utm_source=api__emploi_store_dev&utm_campaign=api__emploi_store_dev__limmersionfacile",
    website: "",
  },
  {
    address:
      "Service des ressources humaines, 13 RUE DE LA MARNE, 57700 HAYANGE",
    alternance: false,
    boosted: false,
    city: "HAYANGE",
    contact_mode: "Envoyer un CV et une lettre de motivation",
    distance: 25.1,
    headcount_text: "50 à 99 salariés",
    lat: 49.3323,
    lon: 6.06118,
    matched_rome_code: "M1607",
    matched_rome_label: "Secrétariat",
    matched_rome_slug: "secretariat",
    naf: "8413Z",
    naf_text: "Administration publique (tutelle) des activités économiques",
    name: "AGENCE LOCALE POUR L EMPLOI HAYANGE",
    siret: "13000548104020",
    social_network: "",
    stars: 4.4,
    url: "https://labonneboite.pole-emploi.fr/13000548104020/details?rome_code=M1607&utm_medium=web&utm_source=api__emploi_store_dev&utm_campaign=api__emploi_store_dev__limmersionfacile",
    website: "",
  },
  {
    address: "Service des ressources humaines,  RUE DE VERDUN, 57190 FLORANGE",
    alternance: true,
    boosted: false,
    city: "FLORANGE",
    contact_mode: "Envoyer un CV et une lettre de motivation",
    distance: 22.9,
    headcount_text: "100 à 199 salariés",
    lat: 49.3204,
    lon: 6.11007,
    matched_rome_code: "M1607",
    matched_rome_label: "Secrétariat",
    matched_rome_slug: "secretariat",
    naf: "3312Z",
    naf_text: "Réparation de machines et équipements mécaniques",
    name: "HARSCO METALS & MINERALS FRANCE",
    siret: "47991852600050",
    social_network: "",
    stars: 4.3,
    url: "https://labonneboite.pole-emploi.fr/47991852600050/details?rome_code=M1607&utm_medium=web&utm_source=api__emploi_store_dev&utm_campaign=api__emploi_store_dev__limmersionfacile",
    website: "",
  },
  {
    address:
      "Service des ressources humaines, 97 RUE CLAUDE BERNARD, 57070 METZ",
    alternance: false,
    boosted: false,
    city: "METZ",
    contact_mode: "Envoyez votre candidature par mail",
    distance: 2.6,
    headcount_text: "250 à 499 salariés",
    lat: 49.115,
    lon: 6.21096,
    matched_rome_code: "M1607",
    matched_rome_label: "Secrétariat",
    matched_rome_slug: "secretariat",
    naf: "8610Z",
    naf_text: "Activités hospitalières",
    name: "HOPITAL CLAUDE BERNARD",
    siret: "36680076100012",
    social_network: "",
    stars: 4.5,
    url: "https://labonneboite.pole-emploi.fr/36680076100012/details?rome_code=M1607&utm_medium=web&utm_source=api__emploi_store_dev&utm_campaign=api__emploi_store_dev__limmersionfacile",
    website: "",
  },
  {
    address:
      "Service des ressources humaines, 1 RUE ANDRE MAGINOT, 57365 FLEVY",
    alternance: false,
    boosted: false,
    city: "FLEVY",
    contact_mode: "Envoyer un CV et une lettre de motivation",
    distance: 14.1,
    headcount_text: "100 à 199 salariés",
    lat: 49.2403,
    lon: 6.23391,
    matched_rome_code: "M1607",
    matched_rome_label: "Secrétariat",
    matched_rome_slug: "secretariat",
    naf: "5210B",
    naf_text: "Entreposage et stockage non frigorifique",
    name: "KUEHNE+NAGEL",
    siret: "33358346601894",
    social_network: "",
    stars: 4.2,
    url: "https://labonneboite.pole-emploi.fr/33358346601894/details?rome_code=M1607&utm_medium=web&utm_source=api__emploi_store_dev&utm_campaign=api__emploi_store_dev__limmersionfacile",
    website: "",
  },
  {
    address:
      "Service des ressources humaines,  AVENUE MARGUERITE PUHL DEMANGE, 54150 BRIEY",
    alternance: true,
    boosted: false,
    city: "BRIEY",
    contact_mode: "Se présenter spontanément",
    distance: 23,
    headcount_text: "50 à 99 salariés",
    lat: 49.2574,
    lon: 5.94006,
    matched_rome_code: "M1607",
    matched_rome_label: "Secrétariat",
    matched_rome_slug: "secretariat",
    naf: "4711F",
    naf_text: "Hypermarchés",
    name: "SUPER U",
    siret: "41167129000038",
    social_network: "",
    stars: 4.3,
    url: "https://labonneboite.pole-emploi.fr/41167129000038/details?rome_code=M1607&utm_medium=web&utm_source=api__emploi_store_dev&utm_campaign=api__emploi_store_dev__limmersionfacile",
    website: "",
  },
  {
    address:
      "Service des ressources humaines, 2 RUE SAINT VINCENT, 57140 WOIPPY",
    alternance: false,
    boosted: false,
    city: "WOIPPY",
    contact_mode: "Se présenter spontanément",
    distance: 5.8,
    headcount_text: "20 à 49 salariés",
    lat: 49.1688,
    lon: 6.15139,
    matched_rome_code: "M1607",
    matched_rome_label: "Secrétariat",
    matched_rome_slug: "secretariat",
    naf: "4774Z",
    naf_text:
      "Commerce de détail d'articles médicaux et orthopédiques en magasin spécialisé",
    name: "ELIVIE",
    siret: "33395438600707",
    social_network: "",
    stars: 4.5,
    url: "https://labonneboite.pole-emploi.fr/33395438600707/details?rome_code=M1607&utm_medium=web&utm_source=api__emploi_store_dev&utm_campaign=api__emploi_store_dev__limmersionfacile",
    website: "",
  },
  {
    address: "18 RUE DE STOXEY, 57070 METZ",
    alternance: true,
    boosted: false,
    city: "METZ",
    contact_mode: "Envoyer un CV et une lettre de motivation",
    distance: 1.5,
    headcount_text: "0 salarié",
    lat: 49.1205,
    lon: 6.19598,
    matched_rome_code: "M1607",
    matched_rome_label: "Secrétariat",
    matched_rome_slug: "secretariat",
    naf: "8790B",
    naf_text:
      "Hébergement social pour adultes et familles en difficultés et autre hébergement social",
    name: "AIEM",
    siret: "77561872100143",
    social_network: "",
    stars: 4.3,
    url: "https://labonneboite.pole-emploi.fr/77561872100143/details?rome_code=M1607&utm_medium=web&utm_source=api__emploi_store_dev&utm_campaign=api__emploi_store_dev__limmersionfacile",
    website: "",
  },
];
