export const fakeCompaniesLaPlateFormeDeLInclusion = [
  {
    cree_le: "2019-12-05T15:37:56.609000+01:00",
    mis_a_jour_le: "2021-07-12T14:21:37.608631+02:00",
    siret: "24570135400111",
    type: "ACI",
    raison_sociale: "COMMUNAUTE DE COMMUNES DE L'ARC MOSELLAN",
    enseigne: "Chantier d'insertion de l'Arc Mosellan (CCAM)",
    site_web: "http://www.arcmosellan.fr",
    description: "",
    bloque_candidatures: false,
    addresse_ligne_1: "8 Rue du Moulin",
    addresse_ligne_2: "",
    code_postal: "57920",
    ville: "Buding",
    departement: "57",
    postes: [
      {
        id: 7871,
        rome: "Revalorisation de produits industriels (K2304)",
        cree_le: "2020-10-19T08:55:31.660775+02:00",
        mis_a_jour_le: "2021-09-28T10:12:29.069542+02:00",
        recrutement_ouvert: "True",
        description:
          "Accueil des usagers de déchetteries, trie des produits/matériels voués à l'enfouissement pour réemploi, nettoyage, contrôle et/ou remise en état du produit/matériel, mise en œuvre du circuit de \"seconde vie\" des produits/matériels.\r\nLe chantier d'insertion vous permettra en parallèle d'une activité de production d’être accompagné dans vos démarches de recherche de formation et d'emploi.",
        appellation_modifiee: "",
      },
      {
        id: 7616,
        rome: "Manutention manuelle de charges (N1105)",
        cree_le: "2020-10-13T15:08:56.543309+02:00",
        mis_a_jour_le: "",
        recrutement_ouvert: "True",
        description:
          "Préparation, livraison, montage, entretien de matériel événementiel : tentes, chapiteaux, scènes, tables, bancs...\r\nLe chantier d'insertion vous permettra en parallèle d'une activité de production d’être accompagné dans vos démarches de recherche de formation et d'emploi.",
        appellation_modifiee: "",
      },
      {
        id: 6159,
        rome: "Aménagement et entretien des espaces verts (A1203)",
        cree_le: "2020-09-24T11:30:35.498673+02:00",
        mis_a_jour_le: "2020-10-13T15:00:53.580016+02:00",
        recrutement_ouvert: "True",
        description:
          "Entretien des espaces verts, des espaces naturels, des pistes cyclables et espaces communautaires.\r\nLe chantier d'insertion vous permettra en parallèle d'une activité de production d’être accompagné dans vos démarches de recherche de formation et d'emploi.",
        appellation_modifiee: "",
      },
    ],
  },
  {
    cree_le: "2019-12-05T15:37:56.609000+01:00",
    mis_a_jour_le: "2020-10-08T17:29:24.928558+02:00",
    siret: "78000505400041",
    type: "ACI",
    raison_sociale:
      "CENTRE D'ANIMATION SOCIALE, SPORTIVE ET D'INSERTION SOLIDAIRE",
    enseigne: "CASSIS",
    site_web: "",
    description: "",
    bloque_candidatures: false,
    addresse_ligne_1: "11 Rue de Champagne",
    addresse_ligne_2: "",
    code_postal: "57070",
    ville: "Metz",
    departement: "57",
    postes: [
      {
        id: 14974,
        rome: "Accueil et renseignements (M1601)",
        cree_le: "2021-02-15T14:44:19.049381+01:00",
        mis_a_jour_le: "2021-07-13T14:38:38.543571+02:00",
        recrutement_ouvert: "False",
        description:
          "Accompagné(e) par notre service administratif et comptable ,l'agent administratif assure l'accueil physique , téléphonique et l'orientation des usagers et de tous les interlocuteurs externes. Il ou elle transfère les communications aux différents services demandés. Il ou elle renseigne et inscrit les usagers aux différentes activités sociales et sportives proposées dans notre structure. En lien avec la Direction et le service comptable, l'agent administratif et d'accueil recueille et transmet les listes d'adhésions et d'inscriptions aux différentes activités proposées.\r\nConnaissance des logiciels Word et Excel, aisance relationnel, sens de la communication fortement souhaité.\r\nPersonnes souhaitant se professionnaliser dans les métiers de l'accueil en vue d'une insertion professionnelle durable.\r\nPublic éligible à l'IAE ,CDDI de 20 à 30h/hebdomadaire",
        appellation_modifiee: "Agent administratif et d'accueil",
      },
      {
        id: 14970,
        rome: "Nettoyage de locaux (K2204)",
        cree_le: "2021-02-15T14:13:42.990947+01:00",
        mis_a_jour_le: "2021-08-10T09:45:30.248078+02:00",
        recrutement_ouvert: "False",
        description:
          "Au sein d'une équipe encadrée par des salariés permanents, les agents d'entretien interviennent pour le nettoyage de nos locaux sur plusieurs sites ainsi que pour des prestations de nettoyage de communs ,bureaux, appartements de notre clientèle variée (Syndic de copropriété,bailleurs, cabinets médicaux..).Occasionnellement quelques agents d'entretien des locaux sont amenés également à assurer l'aide en restauration collective pendant les centres aérés ainsi que le lavage des vêtements sportifs .\r\nPersonnes souhaitant se professionnaliser dans l'entretien des locaux et en techniques de nettoyage.\r\nPublic éligible à l'IAE,CDDI de 20 à 35h/hebdomadaire.",
        appellation_modifiee: "Agent d'entretien des locaux",
      },
      {
        id: 14967,
        rome: "Maintenance des bâtiments et des locaux (I1203)",
        cree_le: "2021-02-15T13:36:56.195207+01:00",
        mis_a_jour_le: "2021-08-10T09:45:30.252886+02:00",
        recrutement_ouvert: "False",
        description:
          "Au sein d'une équipe encadrée par des salariés permanents, les agents polyvalents interviennent sur des prestations de débarras d'encombrants, de ramassage de papiers, de débarras d'appartements, de nettoyage haute pression, d'entretien d'espaces verts.de petite maçonnerie et d'entretien dans le domaine du second œuvre. Ils participent activement à une réponse rapide, de qualité et sécurisée pour toutes les commandes d'intervention de notre clientèle(Bailleurs, syndics de copropriété, entreprises ,particuliers, associations..) Le territoire d'intervention est situé sur la commune de Metz et environs avec des chantiers occasionnels liés aux marchés publics sur le secteur de Saint Avold et Bitche. Les agents polyvalents sont amenés à conduire nos véhicules de chantiers.\r\nConditions de travail en intérieur et extérieur, polyvalence, motivation pour les différents métiers de l'entretien du bâtiment. Manutention et port de charges lourdes.\r\n,CDDI de 20 à 35h/hebdomadaire.",
        appellation_modifiee: "Agent polyvalent",
      },
      {
        id: 7194,
        rome: "Animation de loisirs auprès d'enfants ou d'adolescents (G1203)",
        cree_le: "2020-10-08T10:58:32.440283+02:00",
        mis_a_jour_le: "2021-02-17T11:28:03.524391+01:00",
        recrutement_ouvert: "True",
        description:
          "Au sein d'une équipe de professionnels permanents et diplômés ,assurer l'animation en accueil collectif de mineurs. Assurer l'animation et l'accueil d'enfants lors des activités périscolaires, Mercredis récréatifs et Vacances scolaires.\r\nCritères Exigés: BAFA obtenu ou en cours. Pas d'incompatibilité judiciaire avec l'accueil de mineurs. \r\nPremière expérience en Animation auprès d'enfants fortement souhaitée. Eligibilité à l'IAE.\r\nCDDI de 20 à 35h/hebdomadaire",
        appellation_modifiee:
          "Animateur/Animatrice d'activités périscolaires et en centre aéré",
      },
      {
        id: 7192,
        rome: "Formation professionnelle (K2111)",
        cree_le: "2020-10-08T10:35:46.963915+02:00",
        mis_a_jour_le: "2021-09-09T13:59:21.667780+02:00",
        recrutement_ouvert: "False",
        description:
          "Encadré(e) par notre réfèrent formation, assurer l'animation de cours de Français d'un groupe de 10 à 12 personnes en FLE,remise à niveau et remédiation à l'illettrisme. Bon niveau en Français écrit et oral exigé. Bonne qualité relationnelle et pédagogique. Bonne pratique informatique et connaissance de WORD. \r\nAutonomie et à la fois sens du travail d'équipe. Eligibilité à l'IAE.CDDI de 20 à 30h/hebdomadaire.",
        appellation_modifiee:
          "Animateur / Animatrice de formation Alphabétisation,FLE,remise à niveau en langue française",
      },
      {
        id: 14968,
        rome: "Éducation en activités sportives (G1204)",
        cree_le: "2021-02-15T13:36:56.207788+01:00",
        mis_a_jour_le: "2021-02-17T11:28:03.543612+01:00",
        recrutement_ouvert: "False",
        description:
          "Au sein du club sportif de la structure et encadrés par un salarié permanent qualifié, les animateurs sportifs animent et accompagnent les usagers jeunes, adultes et senior lors de rencontres sportives de Football en intérieur et en extérieur en amical et en championnat. Ils animent les entraînements régulièrement et accompagnent les joueurs licenciés dans tous les déplacements sportifs. Certains animateurs sportifs sont amenés à conduire des véhicules de transport de personnes de la structure pour les rencontres et entraînements. Il peuvent également après formation de la ligue de football participer à l'arbitrage de Matches.\r\nFair-play exigé, aptitudes pédagogiques, motivation pour le sport collectif et bonne connaissance et pratique du Football.\r\nCertificat fédéral de football 1 et/ou BAFA souhaité. Pas d'incompatibilité judiciaire avec l'accueil de mineurs.\r\n,CDDI DE 20h à 35h/Hebdomadaire.",
        appellation_modifiee: "Animateur sportif",
      },
      {
        id: 14966,
        rome: "Réalisation de vêtements sur mesure ou en petite série (B1803)",
        cree_le: "2021-02-15T13:36:56.183290+01:00",
        mis_a_jour_le: "2021-02-17T11:28:03.552590+01:00",
        recrutement_ouvert: "False",
        description:
          "Au sein d'un petit atelier couture, réalisation de petite confection en tissus (Tuniques, tabliers...) ,de masques et d'équipement pour la collectivité.\r\nCAP couture souhaité ou bonne pratique amateur de la couture et de la retouche \r\nPersonnes souhaitant se professionnaliser en couture et confection ou souhaitant faire évoluer le projet professionnel à l'aide d'une activité support.\r\nCDDI de 20 à 35h/hebdomadaire.",
        appellation_modifiee:
          "Couturière, Réalisation de vêtements sur mesure ou en petite série.",
      },
      {
        id: 15117,
        rome: "Gardiennage de locaux (K2501)",
        cree_le: "2021-02-17T12:02:38.916227+01:00",
        mis_a_jour_le: "2021-02-17T12:26:20.855999+01:00",
        recrutement_ouvert: "False",
        description:
          "En lien avec les différents responsables de Pôles, le concierge assure l'ouverture et la fermeture des différents sites d'activité de notre structure (Centre social, équipements sportifs intérieurs et extérieurs).Il participe également à la mise à disposition des salles et aux états des lieux lors des locations évènementielles d'usagers. Le concierge participe à la veille sécuritaire et à l'état des locaux et équipements, Il rend compte aux responsables de pôles et à la Direction de toute observation et évènement. Polyvalent, il peut être amener à effectuer des petites interventions techniques et réparations mais aussi à se déplacer en utilisant un de nos véhicules.\r\nSens des responsabilités, sens de la communication, rigueur, réactivité et polyvalence fortement souhaité.\r\nToute personne souhaitant se professionnaliser et se former dans le domaine du gardiennage et de la conciergerie en vue d'une insertion durable.\r\nCDDI de 26 à 35h/hebdomadaire.",
        appellation_modifiee: "Concierge",
      },
      {
        id: 7357,
        rome: "Médiation sociale et facilitation de la vie en société (K1204)",
        cree_le: "2020-10-09T13:17:07.427488+02:00",
        mis_a_jour_le: "2021-06-22T15:15:08.274510+02:00",
        recrutement_ouvert: "False",
        description:
          "En lien avec les multiples activités de notre structure, une des missions consiste à l'information des usagers, à la médiation et l'aide à l'utilisation des services postaux en lien avec quelques sites messins de la Poste. Une autre mission consiste à assurer des permanences d'écrivain public dans notre structure avec l'accueil ,l'écoute ,l'information et une aide rédactionnelle dans les diverses demandes des usagers. Pour ces deux missions, il est nécessaire d'avoir un bon niveau d'expression à l'oral et à l'ecrit,une bonne qualité rédactionnelle et une large connaissance des différentes démarches administratives et des formulaires(Logement ,impôts ,CAF ,CPAM ,MDPH...).Nécessité également, d'une capacité d'écoute ,d'adaptation et d' un sens de la communication. Bonne pratique des logiciels informatiques de base Word et Excel.\r\nCDDI de 20h/Hebdomadaire",
        appellation_modifiee:
          "Médiateur /Médiatrice des usagers et écrivain public",
      },
      {
        id: 15119,
        rome: "Vente en alimentation (D1106)",
        cree_le: "2021-02-17T12:26:20.819020+01:00",
        mis_a_jour_le: "2021-06-22T15:15:08.284385+02:00",
        recrutement_ouvert: "False",
        description:
          "Encadré(e) par du personnel permanent ,le ou la vendeur(se) en épicerie solidaire propose et vend dans notre épicerie agréée des denrées alimentaires et produits divers à un public aux faibles ressources. Il ou elle assure l'accueil et le flux de la clientèle. Il ou elle veille au réassort et la rotation des rayons et de la réserve et veille aux conditions sanitaires (conservation et date de péremption des produits).Il ou elle peut encaisser les ventes et peut être amener à clôturer et transmettre la recette du jour à notre service comptable. Le ou la vendeur(se) en épicerie solidaire peut participer à des ventes évènementielles comme des bourses aux vêtements et jouets. Polyvalent(e) il ou elle est amené(e) à utiliser le véhicule dédié à l'épicerie pour aller chercher la marchandise à la banque alimentaire et chez d'autres fournisseurs.\r\nBonne capacité relationnelle, sens commercial, rigueur. Poste nécessitant de la manutention répétitive de charges.\r\nCDDI de 26h/hebdomadaire.",
        appellation_modifiee: "Vendeur, vendeuse en épicerie solidaire.",
      },
    ],
  },
  {
    cree_le: "2019-12-05T15:37:56.609000+01:00",
    mis_a_jour_le: "2020-10-22T18:02:06.059896+02:00",
    siret: "78331234100044",
    type: "ACI",
    raison_sociale: "ASSOC ARELIA SAUVOY ATELIER BORNY",
    enseigne: "ARELIA METZ-BORNY",
    site_web: "http://www.arelia-asso.fr",
    description:
      "Activités : Espaces verts, bâtiment, maintenance et manutention.",
    bloque_candidatures: false,
    addresse_ligne_1: "8 Rue du Maine",
    addresse_ligne_2: "",
    code_postal: "57070",
    ville: "Metz",
    departement: "57",
    postes: [
      {
        id: 3478,
        rome: "Nettoyage de locaux (K2204)",
        cree_le: "2020-07-21T11:51:41.907393+02:00",
        mis_a_jour_le: "2021-09-13T17:16:20.964331+02:00",
        recrutement_ouvert: "True",
        description:
          "Activités de nettoyage d'espaces publics et privatifs : bureaux, sanitaires, communs d'immeubles, extérieurs.\r\nMaîtrise de la langue française écrite et orale (fiches de suivi, contact clientèle…)\r\nPermis B apprécié.\r\nDurée du contrat initial : 4 mois\r\nDurée hebdomadaire : 26h00 \r\nHoraires de travail : 3 jours de 8h00 à 15h30 et 1 jour de 8h à 13h du lundi au vendredi\r\nUn projet professionnel sera travaillé en parallèle dans le cadre d’un accompagnement socioprofessionnel.",
        appellation_modifiee:
          "Agent / Agente d'entretien de locaux / 26h hebdo",
      },
      {
        id: 3477,
        rome: "Peinture en bâtiment (F1606)",
        cree_le: "2020-07-21T11:51:41.895062+02:00",
        mis_a_jour_le: "2021-09-13T17:16:20.970635+02:00",
        recrutement_ouvert: "True",
        description:
          "La candidat doit avoir validé un projet professionnel dans le secteur du 2nd œuvre via une expérience ou une formation.\r\nCe projet professionnel sera travaillé en parallèle dans le cadre d’un accompagnement socioprofessionnel. \r\nActivités principales : \r\nPeinture intérieure, pose de revêtements muraux, de papier peint, \r\nPose de revêtements de sol\r\nPose de cloisons en plaque de plâtre\r\nPeinture de façade\r\nMaçonnerie\r\nMenuiserie\r\n\r\nDurée hebdomadaire : 28h00\r\nAmplitude horaire : 8h-17h\r\nDurée du contrat initial : 4 mois",
        appellation_modifiee:
          "Ouvrier Polyvalent / Ouvrière Ployvalente du Bâtiment / 26 heures hebdo",
      },
      {
        id: 4161,
        rome: "Conduite et livraison par tournées sur courte distance (N4105)",
        cree_le: "2020-08-07T14:49:08.625202+02:00",
        mis_a_jour_le: "2021-09-13T17:16:20.977085+02:00",
        recrutement_ouvert: "True",
        description:
          " PERMIS B obligatoire\r\nLes missions : \r\n•\tPréparer le camion pour les différentes collectes et effectuer les collectes chez nos clients\r\n•\tRemonter les informations nécessaires au bon déroulement et garantir la satisfaction des clients\r\n•\tContrôler le contenu des bacs\r\n•\tDéchargement et pesée des bacs\r\n•\tVider les bacs pleins sur la table de tri\r\n•\tEcarter les déchets recyclables autre que papier (cartons, bouteilles en plastique, canettes, gobelets, films en plastique)\r\n•\tSéparer manuellement les papiers admis sur la table de tri, en les répartissant dans les différents bacs imprimeurs\r\n•\tMaintenir la propreté des sols et abords du dépôt,\r\n•\tCompacter des cartons (à l’aide du compacteur),\r\n•\tProcéder à la destruction des papiers confidentiels (à l’aide du broyeur).\r\n\r\nProfil recherché :\r\n•\tEtre titulaire du permis B\r\n•\tTravail en équipe,\r\n•\tBonne condition physique et aisance gestuelle,\r\n•\tCompréhension et respect des consignes,\r\n•\tRespect des règles de sécurité,\r\n•\tOrganiser, Rigoureux, \r\n\r\nUn projet professionnel sera travaillé en parallèle dans le cadre d’un accompagnement socioprofessionnel. \r\n\r\nDurée du contrat initial : 4 mois\r\nDurée hebdomadaire: 20 Heures du lundi au vendredi par 1/2 journée de 4h00 du Lundi au Vendredi\r\n",
        appellation_modifiee:
          "Chauffeu(se)-collecteur(se)-Trieur(se) Elise / 20 h hebdo",
      },
      {
        id: 3473,
        rome: "Aménagement et entretien des espaces verts (A1203)",
        cree_le: "2020-07-21T11:42:33.586678+02:00",
        mis_a_jour_le: "2021-03-25T10:34:52.948043+01:00",
        recrutement_ouvert: "False",
        description:
          "Activités principales : Entretien et nettoyage des espaces extérieurs ; Débroussaillage; Tonte; Taille de haies, Entretien de massifs, Plantations ...\r\nLe candidat :\r\n \tEst résistant aux aléas climatiques.\r\n \tEst résistant à l'effort physique.\r\n \tEst capable de porter des charges (ex: un souffleur; débroussailleur)\r\n\r\nUn projet professionnel sera travaillé en parallèle dans le cadre d’un accompagnement socioprofessionnel. \r\n\r\nDurée du contrat initial : 4 mois\r\nDurée hebdomadaire: 20 Heures du lundi au vendredi\r\nAmplitude horaire 8h - 17h selon planning (2 ou 3 jours par semaine)\r\n",
        appellation_modifiee: "",
      },
      {
        id: 19845,
        rome: "Secrétariat (M1607)",
        cree_le: "2021-06-14T15:15:00.458106+02:00",
        mis_a_jour_le: "2021-09-14T13:58:40.067117+02:00",
        recrutement_ouvert: "False",
        description:
          "Au sein de notre chantier Elise ( tri et collecte de déchets bureau) , vous apporterez un appui logistique : éditions des bons de livraison, planning des tournées, gestion des avis de passage, contact clientèle.\r\nVous aurez en charge également\r\nLa réception, rédaction et transmission des courriers et e-mails\r\nLe tri, l’organisation et le classement de documents et dossiers (papier et informatique)\r\nVous devez maîtrisez les logiciels Word, Excel et les outils de communication (Internet, messagerie, ...) \r\n\r\nCe poste demande :\r\n•\tEsprit d'initiative\r\n•\tFacilités d'adaptation\r\n•\tFacilités de communication, de travail en équipe\r\n•\tRigueur, sens de l'organisation\r\n\r\nVous devez être titulaire d'un diplôme de niveau IV ou V avec expérience dans le secteur du secrétariat. de minimum 6 mois.\r\n\r\nContrat initial : 4 mois\r\n30 h hebdomadaire du Lundi au Vendredi\r\n\r\nMerci de joindre votre CV à la candidature",
        appellation_modifiee: "Secretaire adminsitrative / 20h hbedo",
      },
    ],
  },
  {
    cree_le: "2019-12-05T15:37:56.609000+01:00",
    mis_a_jour_le: "2020-10-08T17:29:40.320879+02:00",
    siret: "20006765000016",
    type: "ACI",
    raison_sociale: "COMMUNAUTE DE COM HOUVE PAYS BOULAGEOIS",
    enseigne: "Communaute de com houve pays boulageois",
    site_web: "",
    description: "",
    bloque_candidatures: false,
    addresse_ligne_1: "29 Rue de Sarrelouis",
    addresse_ligne_2: "",
    code_postal: "57220",
    ville: "Boulay-Moselle",
    departement: "57",
    postes: [
      {
        id: 12201,
        rome: "Maintenance des bâtiments et des locaux (I1203)",
        cree_le: "2020-12-15T15:34:13.086820+01:00",
        mis_a_jour_le: "2021-06-25T14:54:08.601918+02:00",
        recrutement_ouvert: "True",
        description:
          "Le salarié effectue la maintenance et l'entretien des locaux et espaces à usage collectif (locaux communaux, établissements hospitaliers, maisons de retraite, immeubles, écoles, locaux d'entreprises,...) selon les règles de sécurité, et l'entretien des espaces verts (tonte, élagage, débroussaillage etc...)\r\n\r\nLieu de travail : Boulay et territoire de la CCHPB.\r\n\r\nActivité : Entretien des espaces verts, peinture, petite maçonnerie, manutention, pose de carrelage, isolation etc...\r\n\r\nCompétences : Sous la responsabilité d'un encadrant technique, assurer une maintenance de premier niveau en bricolage, réparation, Préparer un support à enduire, Appliquer des gammes de peintures, vernis, enduits ou laques, Entretenir un espace extérieur, Suivre l'état des stocks, Définir des besoins en approvisionnement, Entretenir le matériel\r\n\r\nModalités : CDDI temps partiel de 4 mois renouvelable jusqu'à 2 ans maximum, base 26h/semaine, Salaire : SMIC\r\n\r\nQualités requises : ponctuel, volontaire, bonne condition physique\r\n\r\nConditions d'accès : Éligible à un contrat aidé, pas de diplôme particulier, un CAP/BEP dans des spécialités du bâtiment second œuvre (peinture, plomberie, électricité,...) est un plus. Habiter dans une commune de la Communauté de Communes de la Houve et du Pays Boulageois.\r\n\r\n",
        appellation_modifiee:
          "maintenance des locaux et entretien des espaces verts",
      },
      {
        id: 12187,
        rome: "Conduite de transport en commun sur route (N4103)",
        cree_le: "2020-12-15T14:10:40.622674+01:00",
        mis_a_jour_le: "2021-09-21T10:38:49.843120+02:00",
        recrutement_ouvert: "True",
        description:
          "Le chauffeur réalise le transport en commun de personnes, selon la règlementation routière, les règles de sécurité des biens et des personnes et les impératifs de délai et de qualité. Il travaille au sein du Service SOLI'BUS de la Communauté de communes de la Houve et du Pays Boulageois dont le bureau est à BOULAY.\r\nLe service fonctionne 24h/24 et 7j/7, le chauffeur travail donc sur postes.\r\n\r\nMoyens : minibus 9 places équipés de GPS et téléphones portables\r\n\r\nActivité : Prépare les véhicules, repère le parcours et prévoir les aléas, Accueille, renseigne les passagers et les assiste si besoin, Conduis les passagers selon un parcours prédéfini, Renseigne les documents de bord d'un véhicule, Contrôle l'état de fonctionnement du véhicule et effectue le nettoyage, Déclenche les mesures d'urgence en cas d'incident\r\n\r\nModalités : CDDI temps partiel de 4 mois, renouvelables jusqu'à 2 ans maximum, base 26h/semaine, Salaire : SMIC\r\nQualités requises : Ponctualité, Rigueur, Sens des responsabilités, Discrétion, Capacités relationnelles, autonomie, Organisation et méthodologie, Disponibilité, Respect du secret professionnel, Aptitude à rendre compte\r\n\r\nCondition d’accès : être éligible à un contrat aidé, Accessible sans diplôme ni expérience professionnelle d'accès, être titulaire du permis de conduire européen en cours de validité depuis au moins 3 ans sans accident responsable. Habiter dans une commune de la Communauté de Communes de la Houve et du Pays Boulageois ou une une commune proche (maximum 30 km de Boulay)\r\n",
        appellation_modifiee:
          "Chauffeur dans un service de transport à la demande ",
      },
      {
        id: 12191,
        rome: "Secrétariat (M1607)",
        cree_le: "2020-12-15T14:34:54.601977+01:00",
        mis_a_jour_le: "2021-09-21T10:38:49.849730+02:00",
        recrutement_ouvert: "True",
        description:
          "La secrétaire exécute des travaux administratifs courants (vérification de documents, frappe et mise en forme des courriers préétablis, suivi de dossier administratif, ...) selon l'organisation de la structure ou du service. Elle peut être en charge des activités de reprographie et d'archivage. Elle peut réaliser l'accueil de la structure. \r\n\r\n\r\nLieu de travail : Service SOLI’BUS à BOULAY\r\n\r\nActivité : Constitue des dossiers administratifs, Gère la planification du Transport à la demande, Assure l'accueil téléphonique et physique, Encaissement, Numérise les documents\r\n\r\nCompétences : Maitrise de l'outil informatique : Word, Excel, Bonne connaissance du français, Gestion administrative, Méthode de classement et d'archivage \r\n\r\nModalités : CDDI temps partiel de 4 mois renouvelable jusqu'à 2 ans maximum, base 26h/semaine, Salaire : SMIC\r\n\r\nQualités requises : Rigueur, Sens des responsabilités, Discrétion, Capacités relationnelles, Autonomie, Organisation et méthodologie, Disponibilité, Respect du secret professionnel, Aptitude à rendre compte, \r\n\r\nConditions d'accès : Éligible à un contrat aidé, Diplôme de fin d'études secondaires à Bac dans le secteur du tertiaire, Accessible avec expérience professionnelle, sans diplôme particulier. Habiter dans une commune de la Communauté de Communes de la Houve et du Pays Boulageois ou une une commune proche (maximum 30 km de Boulay)",
        appellation_modifiee:
          "Secrétaire au sein d'un service de transport à la demande",
      },
    ],
  },
  {
    cree_le: "2019-12-05T15:37:56.609000+01:00",
    mis_a_jour_le: "2021-02-09T15:55:21.222819+01:00",
    siret: "78001523600018",
    type: "ACI",
    raison_sociale: "ASSOC EMMAUS",
    enseigne: "Association Emmaüs Peltre et Thionville",
    site_web: "",
    description:
      "La Communauté Emmaüs de Peltre et Thionville est une association \"Loi 1908\" à but non lucratif créée en 1957.\r\nNous y accueillions des personnes en grandes difficultés.\r\n43 Compagnes et Compagnons vivent et travaillent à la Communauté : après un accident de parcours, ces hommes et ces femmes \"cabossés\" par la vie, retrouvent ici, par l'activité et la vie communautaire, leur dignité. C'est une véritable alternative à la vie sociale et professionnelle classique, qui fonctionne sans subvention publique !\r\n\r\nLa Communauté porte également des ateliers et chantiers d'insertion conventionnés dont l'objectif est de favoriser l'insertion sociale et professionnelle de personnes en difficultés.\r\n\r\nLes ateliers et chantiers se décomposent de la façon suivante :\r\n\r\n- Chantier palettes : Agent / Agente de collecte, tri et réparation de palettes\r\n- Chantier textiles : Agent / Agente de tri - aide vendeur / vendeuse\r\n- Chauffeur / Chauffeuse coursier Peltre\r\n- Chauffeur / Chauffeuse manutentionnaire Peltre et Thionville\r\n- Agent / Agente d'entretien Peltre et Thionville\r\n- Agent / Agente administratif / administrative Peltre",
    bloque_candidatures: false,
    addresse_ligne_1: "Route de Strasbourg",
    addresse_ligne_2: "",
    code_postal: "57245",
    ville: "Peltre",
    departement: "57",
    postes: [
      {
        id: 18082,
        rome: "Opérations manuelles d'assemblage, tri ou emballage (H3302)",
        cree_le: "2021-05-03T16:27:21.375153+02:00",
        mis_a_jour_le: "2021-09-27T16:38:09.515567+02:00",
        recrutement_ouvert: "True",
        description:
          "L'agent / agente de tri, aide vendeur / vendeuse opère un contrôle et un rangement des produits en tenant compte des critères relatifs à l'état qualitatif. Il ou elle assure l'accueil des clients, la vente et le bon fonctionnement de l'espace textile et accessoire du magasin.\r\nLe poste se situe sur le magasin de THIONVILLE",
        appellation_modifiee:
          "Agent / Agente de tri / aide vendeur / vendeuse ( THIONVILLE )",
      },
      {
        id: 9407,
        rome: "Opérations manuelles d'assemblage, tri ou emballage (H3302)",
        cree_le: "2020-11-13T09:19:34.311876+01:00",
        mis_a_jour_le: "2021-05-25T14:21:30.836356+02:00",
        recrutement_ouvert: "True",
        description:
          "L'agent / agente de tri textile, aide vendeur / vendeuse opère un contrôle et un rangement des textiles en tenant compte des critères relatifs à l'état qualitatif du produit. Il ou elle assure l'accueil des clients, la vente et le bon fonctionnement de l'espace textile et accessoire du magasin.\r\nLe poste se situe à PELTRE. \r\nPour les personnes ne possédant pas de moyen de locomotion, nous organisons une natte à l'arrêt METTIS situé à la foire exposition de Grigy. ",
        appellation_modifiee:
          "Agent / Agente de tri textile, aide vendeur / vendeuse ( PELTRE )",
      },
      {
        id: 14855,
        rome: "Nettoyage de locaux (K2204)",
        cree_le: "2021-02-11T11:25:52.047498+01:00",
        mis_a_jour_le: "2021-05-03T16:33:41.603796+02:00",
        recrutement_ouvert: "True",
        description:
          "Agent / agente d'entretien des locaux sur notre magasin de Thionville",
        appellation_modifiee: "Agent / agente d'entretien ( THIONVILLE )",
      },
      {
        id: 18083,
        rome: "Conduite et livraison par tournées sur courte distance (N4105)",
        cree_le: "2021-05-03T16:31:24.050012+02:00",
        mis_a_jour_le: "2021-09-27T16:38:09.521841+02:00",
        recrutement_ouvert: "True",
        description:
          "Le chauffeur manutentionnaire conduit un véhicule léger, participe à l'enlèvement et à la livraison de marchandises à domicile, assure le déchargement du camion aux emplacements prévus à cet effet.\r\nLe poste est à pourvoir sur notre magasin de THIONVILLE",
        appellation_modifiee: "Chauffeur manutentionnaire ( THIONVILLE )",
      },
      {
        id: 9406,
        rome: "Conduite et livraison par tournées sur courte distance (N4105)",
        cree_le: "2020-11-13T09:11:24.432836+01:00",
        mis_a_jour_le: "2021-09-27T16:38:09.525403+02:00",
        recrutement_ouvert: "True",
        description:
          "Le chauffeur manutentionnaire conduit un véhicule léger, participe à l'enlèvement et à la livraison de marchandises à domicile, assure le déchargement du camion aux emplacements prévus à cet effet.\r\nLe poste se situe à PELTRE.",
        appellation_modifiee: "Chauffeur manutentionnaire ( PELTRE )",
      },
      {
        id: 14503,
        rome: "Revalorisation de produits industriels (K2304)",
        cree_le: "2021-02-02T15:01:38.529924+01:00",
        mis_a_jour_le: "2021-09-27T16:38:09.528849+02:00",
        recrutement_ouvert: "True",
        description:
          "L'agent / agente collecte des palettes en bois auprès d'entreprises partenaires, qui seront triées et revalorisées à la communauté.\r\nLe poste se situe à PELTRE.",
        appellation_modifiee:
          "Agent / Agente de collecte, Tri et réparation de palettes ( PELTRE )",
      },
    ],
  },
  {
    cree_le: "2020-12-14T14:53:43.850925+01:00",
    mis_a_jour_le: "",
    siret: "48942466300040",
    type: "EA",
    raison_sociale: "Ea Ingecap Sarl",
    enseigne: "Ea ingecap sarl",
    site_web: "",
    description: "",
    bloque_candidatures: false,
    addresse_ligne_1: "2 Rue Augustin Fresnel",
    addresse_ligne_2: "",
    code_postal: "57070",
    ville: "Metz",
    departement: "57",
    postes: [],
  },
  {
    cree_le: "2019-12-05T15:37:56.609000+01:00",
    mis_a_jour_le: "2021-04-12T10:49:29.053586+02:00",
    siret: "20007058900011",
    type: "ACI",
    raison_sociale: "COMMUNAUTE DE COMMUNES SEILLE ET GRAND COURONNE",
    enseigne: "Chantier d'Insertion Espaces Verts",
    site_web: "http://www.territoire-smgc.fr/",
    description:
      "Le Chantier d'Insertion est porté depuis 1991 par la Communauté de Communes Seille et Grand Couronné, actuellement composée de 42 communes.\r\n\r\nLe chantier propose différents travaux au sein de la collectivité et pour les communes du territoire, tels que l’entretien des espaces verts, la valorisation du petit patrimoine, la réfection de bâtiments, l'entretien de sentiers de randonnées, l’installation du matériel d’exposition et de spectacle...\r\n\r\nL'équipe est composée de deux encadrants techniques et d'une accompagnatrice socio-professionnelle.",
    bloque_candidatures: false,
    addresse_ligne_1: "Communauté de Communes Seille et Grand Couronné",
    addresse_ligne_2: "23 route de Pont-à-Mousson",
    code_postal: "54610",
    ville: "NOMENY",
    departement: "54",
    postes: [
      {
        id: 2443,
        rome: "Aménagement et entretien des espaces verts (A1203)",
        cree_le: "2020-06-19T13:27:10.405900+02:00",
        mis_a_jour_le: "2021-03-18T11:39:01.557177+01:00",
        recrutement_ouvert: "True",
        description:
          "Vous serez chargé de l'entretien des espaces verts, des bâtiments et de divers travaux de second-œuvre.\r\n\r\nVous serez accompagné pour acquérir des compétences vous permettant de : \r\n- Assurer une maintenance de premier niveau\r\n- Entretenir des équipements\r\n- Entretenir un espace extérieur\r\n- Préparer les sols et les plantations\r\n- Réaliser des petits ouvrages de maçonnerie\r\n- Sécuriser le chantier et son environnement (signalisation, ...)\r\n- Tailler les arbres selon l'orientation de croissance ou la forme recherchée et supprimer les branches indésirables\r\n\r\nLes contrats proposés sont à 26h/semaine.",
        appellation_modifiee: "Agent Polyvalent d'Entretien ",
      },
    ],
  },
  {
    cree_le: "2019-12-05T15:37:56.609000+01:00",
    mis_a_jour_le: "2021-06-29T11:14:39.634062+02:00",
    siret: "43404758500030",
    type: "ACI",
    raison_sociale: "ASSOCIATION METZ-POLE-SERVICES",
    enseigne: "METZ POLE SERVICES Chantier d'Insertion",
    site_web: "",
    description: "",
    bloque_candidatures: false,
    addresse_ligne_1: "5 Rue d'Anjou",
    addresse_ligne_2: "",
    code_postal: "57070",
    ville: "Metz",
    departement: "57",
    postes: [
      {
        id: 20533,
        rome: "Accueil et renseignements (M1601)",
        cree_le: "2021-06-29T11:22:03.650065+02:00",
        mis_a_jour_le: "2021-09-15T16:44:30.480331+02:00",
        recrutement_ouvert: "False",
        description:
          "Accueil physique et téléphonique\r\nGestion des rdv\r\nPoste à temps complet du lundi au vendredi",
        appellation_modifiee: "",
      },
      {
        id: 2173,
        rome: "Nettoyage de locaux (K2204)",
        cree_le: "2020-06-10T10:37:59.964936+02:00",
        mis_a_jour_le: "",
        recrutement_ouvert: "True",
        description: "Nettoyage de communs d'immeubles\r\nNettoyage de bureaux",
        appellation_modifiee: "",
      },
      {
        id: 2174,
        rome: "Nettoyage des espaces urbains (K2303)",
        cree_le: "2020-06-10T10:37:59.975923+02:00",
        mis_a_jour_le: "",
        recrutement_ouvert: "True",
        description:
          "Nettoyage urbain à la pince\r\nSorties de containers\r\nEspaces verts\r\nDébarras d'encombrants",
        appellation_modifiee: "",
      },
    ],
  },
  {
    cree_le: "2021-09-14T11:15:50.591262+02:00",
    mis_a_jour_le: "2021-09-14T11:15:52.074368+02:00",
    siret: "78000469300021",
    type: "ACI",
    raison_sociale: "ASS DEP EDUCATION POPULAIRE PLEIN AIR",
    enseigne: "Ass dep education populaire plein air",
    site_web: "",
    description: "",
    bloque_candidatures: false,
    addresse_ligne_1: "34 Avenue Charlemagne",
    addresse_ligne_2: "",
    code_postal: "57640",
    ville: "Vigy",
    departement: "57",
    postes: [],
  },
  {
    cree_le: "2021-09-20T18:08:46.283185+02:00",
    mis_a_jour_le: "2021-09-20T18:08:46.713178+02:00",
    siret: "90153460200015",
    type: "EI",
    raison_sociale: "ASFED 57",
    enseigne: "Asfed 57",
    site_web: "",
    description: "",
    bloque_candidatures: false,
    addresse_ligne_1: "9 Rue Claude Chappe",
    addresse_ligne_2: "",
    code_postal: "57070",
    ville: "Metz",
    departement: "57",
    postes: [],
  },
  {
    cree_le: "2019-12-05T15:38:51.416000+01:00",
    mis_a_jour_le: "2020-03-10T14:22:36.035000+01:00",
    siret: "79245742600015",
    type: "GEIQ",
    raison_sociale: "GEIQ BTP LORRAINE",
    enseigne: "Geiq btp lorraine",
    site_web: "",
    description: "",
    bloque_candidatures: false,
    addresse_ligne_1: "3 Rue Jean Antoine Chaptal",
    addresse_ligne_2: "",
    code_postal: "57078",
    ville: "Metz",
    departement: "57",
    postes: [
      {
        id: 2758,
        rome: "Maintenance électrique (I1309)",
        cree_le: "2020-07-01T15:04:42.480736+02:00",
        mis_a_jour_le: "2020-09-22T12:33:17.855754+02:00",
        recrutement_ouvert: "False",
        description:
          "Le poste: Sous la responsabilité de votre chef et en binôme avec un électricien confirmé vous réaliserez des travaux électriques dans des bâtiments en construction.\r\nProfil recherché:\r\n- Prérequis : Ponctualité, dynamisme, respect des consignes de sécurité, réactivité, autonomie\r\n- Avoir une bonne condition physique\r\n- Ne pas avoir de problème de daltonisme\r\n- Bon savoir-être\r\n- Des connaissances en électricité\r\n- Permis B et véhicule\r\nLieu de travail: Chantier à Dieulouard (54)\r\nRémunération : SMIC",
        appellation_modifiee: "Aide électricien / électricienne ",
      },
      {
        id: 3171,
        rome: "Réalisation de structures métalliques (H2911)",
        cree_le: "2020-07-10T14:27:53.955399+02:00",
        mis_a_jour_le: "",
        recrutement_ouvert: "True",
        description:
          "Le poste: Dans le cadre d’un contrat de professionnalisation, vous travaillerez dans l’atelier de constructions métalliques de l’entreprise. Vous aurez pour missions d’assembler et fixer les éléments des structures selon les plans et les directives de montage (Nomenclature).\r\nProfil recherché:\r\n- Prérequis : Ponctualité, dynamisme, autonomie, sens de l’organisation, dextérité manuelle, minutie, précision, soucis du détail\r\n- Compétences requises : lecture de plan, techniques d’assemblage, de soudage, de pointage\r\nLieu de travail: Atelier de DIEUE SUR MEUSE\r\nFormation : Programme de formation défini en fonction du profil\r\nRémunération : 6,59 à 10,15€ de l'heure (% SMIC selon profil)",
        appellation_modifiee: "Assembleur (H/F)",
      },
      {
        id: 17555,
        rome: "Pose de canalisations (F1705)",
        cree_le: "2021-04-20T10:30:58.378873+02:00",
        mis_a_jour_le: "",
        recrutement_ouvert: "True",
        description:
          "Dans le cadre d’un contrat de professionnalisation de 6 mois, vous participerez aux travaux relatifs à l’installation des réseaux de transport et de distribution d’eau potable et à la réalisation de réseaux d’assainissement. Vous effectuerez l’installation et le réglage des canalisations, ainsi que quelques travaux de petite maçonnerie (pose de bordure, …) Vous suivrez une formation par alternance pour acquérir les techniques du métier de canalisateur.\r\nProfil recherché:\r\n- Compétences personnelles : volontaire, goût du travail en extérieur et en équipe.\r\n- Savoir être requis : ponctualité, assiduité, respect des consignes de sécurité, respect de la hiérarchie\r\n- Mobilité : Permis B (véhicule) de préférence, être en capacité de se rendre sur chantier ou au dépôt à Morhange.\r\nLieu de travail: Sur différents chantiers de Lorraine, principalement en Moselle. \r\nRémunération : 10.26€brut/h + paniers et déplacements en chantier.\r\n",
        appellation_modifiee: "Canalisateur/canalisatrice",
      },
      {
        id: 3070,
        rome: "Conduite d'engins de terrassement et de carrière (F1302)",
        cree_le: "2020-07-08T13:44:31.586579+02:00",
        mis_a_jour_le: "2020-07-20T10:45:24.091456+02:00",
        recrutement_ouvert: "True",
        description:
          "Le poste : \r\nCe job se trouvera au cœur d’une exploitation de carrière, votre mission consistera à conduire et manipuler une dragline, selon les règles de sécurité en vigueur. \r\nVous pouvez transportez des matériaux, minerais ou des déblais sur des emplacements déterminés.Vous suivrez également, en parallèle, une formation qualifiante par alternance (période en chantier alternée par des périodes de formation) pour valider le titre professionnel de conduite d’engins. Vous serez formé aux travaux imposés par la chargeuse, en pelle, la maîtrise du tombereau\r\net tractopelle ainsi que tout le package sécurité nécessaire.\r\nVos missions : \r\n\tConduire, manipuler différents types d’engins lourds de chantier destinés au creusement, au terrassement, au nivellement ou à l’extraction selon les règles de sécurité\r\n\tTransportez des matériaux, minerais ou des déblais sur des emplacements déterminés.\r\nExpérience : 2 à 5 ans souhaitées \r\nLieu de travail : Lunéville\r\nFormation : Le lieu de formation sera le Centre Raymond Bard de Faulquemont (formation, hébergement, restauration pris en charge intégralement par le GEIQ + aide aux frais de transport à hauteur de 50 %).\r\nRémunération : 10,15 à 11€ de l'heure + paniers\r\n",
        appellation_modifiee:
          "Conducteur d'engins de terrassement et de carrière (H/F) ",
      },
      {
        id: 3078,
        rome: "Conduite de travaux du BTP et de travaux paysagers (F1201)",
        cree_le: "2020-07-08T14:27:58.021752+02:00",
        mis_a_jour_le: "",
        recrutement_ouvert: "True",
        description:
          "Le poste : Le conducteur de travaux est chargé de diriger les travaux de construction. Il participe aux réunions préparatoires avec les ingénieurs d’études, il détermine des tâches sur le chantier. Il motive les hommes, contrôle le travail réalisé et corrige les erreurs. Ses principales préoccupations sont la sécurité de ses ouvriers et la qualité du travail final. \r\n\r\nProfil recherché :\r\n-\tCompétences personnelles : volontaire, goût du travail en extérieur et avoir le sens relationnel\r\n- Compétences générales : force de proposition, faire preuves d’ingéniosité et de débrouillardise, avoir suffisamment de charisme et d’autorité \r\n-\tPermis B (véhicule) de préférence\r\n\r\nLieu de travail : Saint-Michel-Sur-Meurthe (88)\r\n\r\nFormation : Vous suivrez un BTS en alternance \r\n\r\nRémunération : % du SMIC selon âge et année \r\n",
        appellation_modifiee: "Conducteur de travaux menuiserie alu / acier",
      },
      {
        id: 5850,
        rome: "Maçonnerie (F1703)",
        cree_le: "2020-09-22T12:31:13.857591+02:00",
        mis_a_jour_le: "",
        recrutement_ouvert: "True",
        description:
          "Le Groupement d'Employeurs pour l'Insertion et la Qualification (GEIQ) BTP Lorraine recrute un apprenti maçon (H/F) pour une de ses entreprises adhérentes, spécialisée dans le Bâtiment, sur BAUDRECOURT (57).\r\nLe poste : Dans le cadre de votre contrat d’apprentissage et sous la responsabilité de votre maitre d’apprentissage, vous intégrerez une petite entreprise familiale et une équipe jeune. Vous participerez aux missions de maçonnerie traditionnelle : petites maçonneries, travaux de rénovation et d’embellissement, taille de pierre.\r\nProfil recherché:\r\n- Prérequis : Ponctualité, dynamisme, respect des consignes de sécurité, réactivité, autonomie, goût du travail en extérieur\r\n- Avoir pour projet de se former au métier de maçon\r\n- Véhicule ou deux-roues\r\nFormation : CAP ou BP maçon selon vos diplômes déjà obtenus\r\nRémunération : Grille rémunération des apprentis du bâtiment + paniers + déplacements",
        appellation_modifiee: "Maçon traditionnel",
      },
      {
        id: 2789,
        rome: "Maçonnerie (F1703)",
        cree_le: "2020-07-01T15:56:51.697038+02:00",
        mis_a_jour_le: "2020-07-08T13:44:31.596098+02:00",
        recrutement_ouvert: "True",
        description:
          "Le poste: \r\nVous aimez le travail d’équipe et en extérieur, et souhaitez réaliser des ouvrages ? Alors n’hésitez plus et postulez dès maintenant au poste de maçon coffreur bancheur ! Sous la responsabilité du chef d’équipe, vous participerez aux missions de maçonnerie traditionnelle, de coffrage et de banchage sur des chantiers de construction (logement, bâtiments industriels, magasins, …). Vous serez amené à travailler sur du dallage, des coffrages traditionnels et avec des banches, de la maçonnerie traditionnelle et de la finition. \r\n\r\n\r\nL’entreprise: Le Groupement d'Employeurs pour l'Insertion et la Qualification (GEIQ) BTP Lorraine recrute pour une de ses entreprises adhérentes de METZ, un maçon coffreur bancheur (H/F).\r\n\r\nProfil recherché:\r\n-\tPrérequis : Ponctualité, dynamisme, respect des consignes de sécurité, réactivité, autonomie, goût du travail en extérieur \r\n-\tAvoir une bonne condition physique \r\n\r\nLieu de travail: Nancy et alentours\r\n\r\nRémunération :SMIC + paniers et déplacements en chantier.\r\n",
        appellation_modifiee: "Maçon coffreur bancheur ",
      },
      {
        id: 2792,
        rome: "Construction de routes et voies (F1702)",
        cree_le: "2020-07-01T16:00:15.296779+02:00",
        mis_a_jour_le: "",
        recrutement_ouvert: "True",
        description:
          "L’entreprise: Le Groupement d'Employeurs pour l'Insertion et la Qualification (GEIQ) BTP Lorraine recrute pour une de ses entreprises adhérentes des Vosges, spécialisée dans les travaux publics.\r\n\r\nLe poste: Le maçon VRD participe à la construction et à l’entretien des réseaux de voiries (routes, parking, pistes cyclables, …). Il réalise également la pose d’éléments de voiries (bordures, dalles, pavés, trottoirs, caniveaux, mobiliers urbains, …).\r\n\r\nVous pourrez être amené à travailler dans l’équipe de régleurs manuel d’enrobés. \r\nLe régleur exécute la finition, par épandage et réglage, de la couche d’enrobé. L’activité se déroule en extérieur, à plusieurs ouvriers : on répand l’enrobé chaud (entre 80 degrés et 160 degrés) apporté par un engin (le finisseur)à l’aide de pelles, râteaux ou de balais de table vibrants.\r\n\r\nProfil recherché:\r\n-\tMotivé, volontaire, goût du travail en extérieur et en équipe. Avoir une bonne condition physique \r\n-\tPermis B (véhicule) de préférence\r\n\r\nLieu de travail: Vittel\r\n\r\nFormation : A définir selon votre profil\r\n\r\nRémunération : % du SMIC selon la grille de rémunération des contrats de professionnalisation\r\n",
        appellation_modifiee:
          "Maçon / Maçonne Voiries et Réseaux Divers - VRD - ",
      },
      {
        id: 4054,
        rome: "Réalisation de menuiserie bois et tonnellerie (H2206)",
        cree_le: "2020-08-04T16:33:51.861547+02:00",
        mis_a_jour_le: "2020-09-22T12:33:17.867244+02:00",
        recrutement_ouvert: "False",
        description:
          "L’entreprise: Le Groupement d'Employeurs Lorraine recrute pour une de ses entreprises adhérentes d’Ars sur Moselle (57), spécialisée dans la menuiserie, un menuisier poseur bois en contrat à durée déterminée (H/F).\r\nLe poste: En binôme avec un menuisier poseur dans un premier temps, puis en autonomie, vous réaliserez des travaux de menuiserie intérieurs et extérieurs aussi bien pour des particuliers que des professionnels.\r\nProfil recherché:\r\n- Prérequis : Ponctualité, autonomie, dynamisme, respect des consignes de sécurité, réactivité\r\n- Des connaissances en menuiserie\r\n- Permis B et véhicule\r\nLieu de travail: Déplacements quotidiens sur différents chantiers\r\nRémunération : selon profil",
        appellation_modifiee: "Menuisier Poseur Bois ",
      },
      {
        id: 15997,
        rome: "Maintenance des bâtiments et des locaux (I1203)",
        cree_le: "2021-03-10T15:57:37.534618+01:00",
        mis_a_jour_le: "2021-09-14T11:09:43.711634+02:00",
        recrutement_ouvert: "False",
        description:
          "Le GE Lorraine recrute un Employé polyvalent du bâtiment (H/F) pour une de ses entreprises adhérentes, leader français des travaux de gros œuvre.\r\n\r\nLe poste: Vous êtes dynamique, aimez le travail d’équipe et en extérieur ? Vous avez la volonté d’intégrer une grande entreprise ? Rejoignez-nous. \r\nDans le cadre d’un CDD vous interviendrez sur un chantier de construction neuve. Après une formation de quelques jours, vous réaliserez les planchers et le bétonnage. Vous serez donc en charge de l’étaiement et du ferraillage. D’autres missions pourront vous être confiées.\r\nA l’issue du CDD, vous aurez la possibilité de suivre un contrat de professionnalisation dans la même entreprise pour vous former au métier d’Agent d’entretien du bâtiment. \r\nProfil recherché:\r\n-\tSavoir être requis : ponctualité, assiduité, respect des consignes de sécurité, respect de la hiérarchie, dynamisme\r\n-\tGoût pour le travail en extérieur\r\n",
        appellation_modifiee: "Employé(e) polyvalent du bâtiment",
      },
    ],
  },
  {
    cree_le: "2020-04-24T15:32:40.623877+02:00",
    mis_a_jour_le: "2020-10-08T17:29:14.413264+02:00",
    siret: "79098920600012",
    type: "EI",
    raison_sociale: "ASSOCIATION EST ACCOMPAGNEMENT",
    enseigne: "Association est accompagnement",
    site_web: "",
    description: "",
    bloque_candidatures: false,
    addresse_ligne_1: "44 AVENUE DES DEUX FONTAINES",
    addresse_ligne_2: "",
    code_postal: "57050",
    ville: "Metz",
    departement: "57",
    postes: [
      {
        id: 2607,
        rome: "Montage d'agencements (F1604)",
        cree_le: "2020-06-26T11:31:35.574137+02:00",
        mis_a_jour_le: "",
        recrutement_ouvert: "True",
        description:
          "-connaissances du métier de plaquiste (mural et plafond)\r\n-pose de panneaux préfabriqués\r\n-montage des cloisons des sols, des doublages en panneaux ou des faux plafonds\r\n-mise en place des huisseries des des encadrements et des montants\r\n-jointure et renforcement de la structure des panneaux\r\n-correction éventuel de équerrage et l'aplomb des murs\r\nlecture des plans\r\n-maniement d'outils tel que équerre, niveau, perceuse\r\n-prise de mesures, traçage, collage et application d'enduits\r\n- connaissances des règles d’hygiène et de sécurité\r\n-port de charges lourdes\r\n- attention aux allergies",
        appellation_modifiee: "",
      },
    ],
  },
  {
    cree_le: "2019-12-05T15:37:56.609000+01:00",
    mis_a_jour_le: "2020-10-08T17:29:19.556446+02:00",
    siret: "21570463600012",
    type: "ACI",
    raison_sociale: "COM DE METZ",
    enseigne: "Com de metz",
    site_web: "",
    description: "",
    bloque_candidatures: false,
    addresse_ligne_1: "1 place d armes",
    addresse_ligne_2: "",
    code_postal: "57000",
    ville: "Metz",
    departement: "57",
    postes: [
      {
        id: 4170,
        rome: "Accueil et renseignements (M1601)",
        cree_le: "2020-08-10T09:28:25.686005+02:00",
        mis_a_jour_le: "2021-09-13T08:51:07.954030+02:00",
        recrutement_ouvert: "False",
        description:
          "Rangement et classement de documents et de stock de livres\r\nEntretien des documents\r\nAccueil du public ( prêts et retour des documents)\r\nPlusieurs lieux d'activité possibles au cours de la même journée, ce qui peut induire des déplacements\r\nStation debout prolongée\r\nCDDI de 6 mois de 26h semaine renouvelable",
        appellation_modifiee: "Agent d'accueil et de rangement en médiathèque",
      },
      {
        id: 22712,
        rome: "Information sociale (K1205)",
        cree_le: "2021-09-14T16:03:09.821131+02:00",
        mis_a_jour_le: "2021-09-23T11:35:09.261516+02:00",
        recrutement_ouvert: "False",
        description:
          "Aide à l'accueil des demandeurs d'emploi\r\nRédaction de CV\r\nAppui des demandeurs d'emploi aux outils numériques\r\nRéalisation d'outils graphiques/aide graphiste\r\nAppui administratif",
        appellation_modifiee: "Agent d'accueil Emploi",
      },
      {
        id: 4518,
        rome: "Nettoyage des espaces urbains (K2303)",
        cree_le: "2020-08-25T09:30:03.236730+02:00",
        mis_a_jour_le: "2021-08-25T15:27:38.933097+02:00",
        recrutement_ouvert: "False",
        description:
          "Balayer les rues, \r\nUtiliser un souffleur, ramasser les feuilles\r\nDésherber\r\nDéneiger, Sabler ou saler en hiver\r\nprérequis: bonne condition physique, port de charge, travail en extérieur et par tous les temps, savoir lire un plan\r\nCDDI de 6 mois renouvelable de 26h semaine, prise de poste du matin à 6h ou d'aprés-midi à 13h ",
        appellation_modifiee: "Agent propreté urbaine",
      },
      {
        id: 4476,
        rome: "Nettoyage de locaux (K2204)",
        cree_le: "2020-08-21T11:57:29.318084+02:00",
        mis_a_jour_le: "2021-09-02T07:56:12.133979+02:00",
        recrutement_ouvert: "False",
        description:
          "Aspirer et laver les sols\r\nDépoussiérer les bureaux \r\nVider et laver les poubelles \r\nEffectuer le tri sélectif des corbeilles à papier et poubelles \r\nVérifier et approvisionner les distributeurs essuie-mains, papier WC et savon \r\nNettoyer les sanitaires et les douches\r\nprérequis: bonne condition physique, travail seul ou en équipe\r\nCDDI 6 mois renouvelable de 26h semaine\r\ndu lundi au jeudi 7h-12h30 et vendredi 8h-12h\r\n ",
        appellation_modifiee: "",
      },
      {
        id: 4517,
        rome: "Nettoyage de locaux (K2204)",
        cree_le: "2020-08-25T09:01:27.770222+02:00",
        mis_a_jour_le: "2021-09-02T07:56:12.143052+02:00",
        recrutement_ouvert: "False",
        description:
          "Aspirer et Laver les sols\r\nDépoussiérer les bureaux et les étagères \r\nVider et laver les poubelles \r\nEffectuer un tri sélectif des corbeilles à papier et poubelles \r\nVérifier et approvisionner les distributeurs essuie-mains, papier WC et savon \r\nNettoyer les sanitaires\r\nprérequis: bonne condition physique,port de charge, travail seul ou en équipe\r\nCDDI de 6 mois renouvelable de 26h semaine prise de poste à 7h le matin\r\n",
        appellation_modifiee: "Agent d'entretien en Bibliothèques-Médiathèques",
      },
      {
        id: 4529,
        rome: "Nettoyage de locaux (K2204)",
        cree_le: "2020-08-25T11:18:48.906772+02:00",
        mis_a_jour_le: "2021-09-02T07:56:12.149929+02:00",
        recrutement_ouvert: "False",
        description:
          "Accueillir le public dans les locaux\r\nRenseigner et diriger les usagers\r\nFaire respecter le règlement intérieur aux usagers \r\nEntretenir et nettoyer selon les normes d’hygiène \r\nGérer la location des équipements (serviettes, maillots,…)\r\nprérequis: bonne condition physique: station debout prolongée; travail en milieu chloré et humide avec température élevée ( de 24° à 30°). \r\nCDDI 6 mois renouvelable de 26h semaine",
        appellation_modifiee: "Agent de vestiaires en piscine",
      },
      {
        id: 17462,
        rome: "Personnel polyvalent en restauration (G1603)",
        cree_le: "2021-04-15T16:46:15.955828+02:00",
        mis_a_jour_le: "2021-05-11T09:56:01.957583+02:00",
        recrutement_ouvert: "False",
        description:
          "Réceptionner, ranger et distribuer les produits - Accueillir les enfants - Servir les repas en respectant les règles d'hygiène - Participer à la plonge - Entretenir les locaux et le matériel utilisé en respectant les procédures du plan de nettoyage et de désinfection.\r\nTravail en équipe - Connaissance des règles de sécurité - Station debout prolongée - Port de charge et travail en milieu humide\r\nCDDI 6 mois renouvelable de 26h semaine",
        appellation_modifiee: "Agent de service en restauration scolaire",
      },
      {
        id: 17459,
        rome: "Magasinage et préparation de commandes (N1103)",
        cree_le: "2021-04-15T16:35:39.928123+02:00",
        mis_a_jour_le: "2021-05-25T14:22:36.510361+02:00",
        recrutement_ouvert: "False",
        description:
          "Réceptionner les produits: décharger, trier, contrôler\r\nSignaler les anomalies - stocker, classer et ranger les produits\r\nPréparer les commandes: déstocker, étiqueter et emballer. Expédier les commandes: préparer les documents administratifs. Charger les produits\r\nStation debout et port de charge - Sens de l'organisation et utilisation de l'outil informatique\r\nCDDI de 6 mois renouvelable, de 26h semaine",
        appellation_modifiee: "Magasinier en restauration scolaire",
      },
      {
        id: 2713,
        rome: "Aménagement et entretien des espaces verts (A1203)",
        cree_le: "2020-06-30T15:50:03.504742+02:00",
        mis_a_jour_le: "2021-03-30T16:34:36.608957+02:00",
        recrutement_ouvert: "False",
        description:
          "Entretien des allées des cimetières : balayage, ratissage, désherbage manuel, utilisation du souffleur, ramassage des feuilles, passage de la tondeuse, utilisation du débroussailleur, collecte des poubelles et évacuation des déchets, déneigement et salage en hiver\r\nprérequis : bonne condition physique travail en extérieur, port de charge\r\nCDDI 6 mois renouvelable de 26 heures semaine prise de poste 7h30 du matin",
        appellation_modifiee:
          "Agent d'entretien des espaces verts dans les cimetières",
      },
    ],
  },
  {
    cree_le: "2019-12-05T15:37:56.609000+01:00",
    mis_a_jour_le: "2020-10-08T17:29:19.566780+02:00",
    siret: "21570751400018",
    type: "ACI",
    raison_sociale: "COM DE WOIPPY",
    enseigne: "Com de woippy",
    site_web: "",
    description: "",
    bloque_candidatures: false,
    addresse_ligne_1: "1 Place de l'Hotel de Ville",
    addresse_ligne_2: "",
    code_postal: "57140",
    ville: "Woippy",
    departement: "57",
    postes: [
      {
        id: 2584,
        rome: "Entretien et surveillance du tracé routier (I1202)",
        cree_le: "2020-06-25T14:12:06.285031+02:00",
        mis_a_jour_le: "2021-08-11T13:39:05.687862+02:00",
        recrutement_ouvert: "False",
        description:
          "Nettoyage des espaces publics extérieurs \r\nramassage des papiers\r\nbalayage ",
        appellation_modifiee: "",
      },
      {
        id: 2582,
        rome: "Entretien des espaces naturels (A1202)",
        cree_le: "2020-06-25T13:59:39.928459+02:00",
        mis_a_jour_le: "2021-08-11T13:39:05.692928+02:00",
        recrutement_ouvert: "True",
        description:
          "- Entretien des espaces naturels de la commune \r\n- Tonte débroussaillage, ramassage des feuilles et des papiers \r\n- Désherbage \r\n20h / semaine contrats de 6 mois renouvelables",
        appellation_modifiee: "",
      },
      {
        id: 2585,
        rome: "Nettoyage de locaux (K2204)",
        cree_le: "2020-06-25T14:12:06.295718+02:00",
        mis_a_jour_le: "2021-03-12T11:15:33.023870+01:00",
        recrutement_ouvert: "False",
        description:
          "nettoyage des locaux communaux \r\ndépoussiérer, nettoyer les sols et les sanitaires",
        appellation_modifiee: "",
      },
      {
        id: 2586,
        rome: "Assistance auprès d'enfants (K1303)",
        cree_le: "2020-06-25T14:12:06.305765+02:00",
        mis_a_jour_le: "2021-08-12T16:42:58.455518+02:00",
        recrutement_ouvert: "True",
        description:
          "surveillance des enfants durant la classe\r\naccompagnement des enfants lors des sorties et à la cantine \r\nnettoyage des locaux",
        appellation_modifiee: "",
      },
    ],
  },
  {
    cree_le: "2019-12-05T15:37:56.609000+01:00",
    mis_a_jour_le: "2021-04-08T12:26:10.137233+02:00",
    siret: "26570170600011",
    type: "ACI",
    raison_sociale: "CCAS HAYANGE",
    enseigne: "Ccas hayange",
    site_web: "",
    description: "",
    bloque_candidatures: false,
    addresse_ligne_1: "Pl Resistance de la Deportation",
    addresse_ligne_2: "",
    code_postal: "57700",
    ville: "Hayange",
    departement: "57",
    postes: [
      {
        id: 16474,
        rome: "Entretien et surveillance du tracé routier (I1202)",
        cree_le: "2021-03-23T09:32:51.595324+01:00",
        mis_a_jour_le: "",
        recrutement_ouvert: "True",
        description:
          "- Balayage de la voie publique\r\n-\tRemplacement des sacs des poubelles de rue\r\n-\tNettoyage après les marchés\r\n-\tRepérage des dépôts sauvages ou des dégradations de l'espace public\r\n-\tRenforcer les agents d'entretien de la voirie \r\n- Manutention de matériel\r\n- Entretien des espaces verts\r\n- Réalisation de petits travaux de peinture\r\n- Distributions",
        appellation_modifiee: "Agent polyvalent de la voirie",
      },
    ],
  },
  {
    cree_le: "2019-12-05T15:37:56.609000+01:00",
    mis_a_jour_le: "2021-02-23T11:18:59.381221+01:00",
    siret: "31988472200038",
    type: "ACI",
    raison_sociale: "ASSOC INTERVENTION SOCIALE DE LA FENSCH",
    enseigne: "Assoc intervention sociale de la fensch",
    site_web: "",
    description: "",
    bloque_candidatures: false,
    addresse_ligne_1: "4 Avenue Jean Mermoz",
    addresse_ligne_2: "",
    code_postal: "57290",
    ville: "Fameck",
    departement: "57",
    postes: [],
  },
  {
    cree_le: "2019-12-05T15:37:56.609000+01:00",
    mis_a_jour_le: "2020-10-08T17:29:19.707404+02:00",
    siret: "33213934400011",
    type: "ACI",
    raison_sociale: "CARREFOUR SOCIAL ET CULTUREL LE CREUSET",
    enseigne: "Carrefour social et culturel le creuset",
    site_web: "",
    description: "",
    bloque_candidatures: false,
    addresse_ligne_1: "11 Rue du Stade",
    addresse_ligne_2: "",
    code_postal: "57270",
    ville: "Uckange",
    departement: "57",
    postes: [
      {
        id: 1855,
        rome: "Nettoyage de locaux (K2204)",
        cree_le: "2020-05-22T11:16:41.649794+02:00",
        mis_a_jour_le: "",
        recrutement_ouvert: "True",
        description:
          "L'agent est chargé de mettre en œuvre des protocoles de nettoyage dans différents espaces d'accueil du public. Il tiendra compte des spécificités de chaque équipements et s'appuiera sur des techniques et outils de nettoyage professionnels (cuisine de collectivité - espaces éducatifs pour la petite enfance et l'enfance - bureau...)",
        appellation_modifiee: "",
      },
      {
        id: 1856,
        rome: "Intervention socioculturelle (K1206)",
        cree_le: "2020-05-22T11:16:41.659422+02:00",
        mis_a_jour_le: "",
        recrutement_ouvert: "True",
        description:
          "Accueil et encadrement d'enfants de 3 à 11 ans durant les temps périscolaires (avant, le midi et après l'école) et extrascolaires (vacances scolaires). Au sein d'une équipe éducative, l'animateur/animatrice sera chargé(e) de mettre en place des animations collectives qui permettent l'éveil et le développement de l'enfant dans le respect du projet éducatif et pédagogique de l'association. ",
        appellation_modifiee: "ANIMATEUR/ANIMATRICE D'ACTIVITES PERISCOLAIRE",
      },
      {
        id: 20654,
        rome: "Aide en puériculture (J1304)",
        cree_le: "2021-07-01T16:16:47.368394+02:00",
        mis_a_jour_le: "2021-08-03T14:09:20.725455+02:00",
        recrutement_ouvert: "True",
        description:
          "Sous l'autorité de la directrice, l'aide auxiliaire de puériculture évoluera dans une structure multi accueil (crèche-halte garderie) au sein d'une équipe éducative. Il/Elle propose des activités d'éveil et veillera à la sécurité des enfants et à l'hygiène de l'environnement. La personne sélectionnée sera chargée de répondre aux besoins fondamentaux de l'enfant (alimentation, sommeil, propreté).\r\nFormation et accompagnement dans le cadre du contrat.\r\nVous devez être éligible à l'IAE et être inscrit sur la plateforme dédiée si tel est la cas. Merci de vérifier auprès de votre conseiller avant de postuler sans quoi votre candidature ne pourra être acceptée.\r\n\r\n",
        appellation_modifiee: "AIDE AUXILIAIRE DE PUERICULTURE ",
      },
    ],
  },
  {
    cree_le: "2019-12-05T15:37:56.609000+01:00",
    mis_a_jour_le: "2020-10-08T17:29:19.741708+02:00",
    siret: "26540098600088",
    type: "ACI",
    raison_sociale: "CENTRE COMMUNAL D' ACTION SOCIALE PONT A MOUSSON",
    enseigne: "Centre communal d' action sociale pont a mousson",
    site_web: "",
    description: "",
    bloque_candidatures: false,
    addresse_ligne_1: "6 Rue Philippe de Gueldre",
    addresse_ligne_2: "",
    code_postal: "54700",
    ville: "Pont-à-Mousson",
    departement: "54",
    postes: [
      {
        id: 2577,
        rome: "Nettoyage de locaux (K2204)",
        cree_le: "2020-06-25T11:57:27.534967+02:00",
        mis_a_jour_le: "2021-08-19T12:18:01.706372+02:00",
        recrutement_ouvert: "True",
        description:
          "Le permis B est exigé pour ce poste, les agents (travaillent en binôme) effectuent des travaux de dépoussiérage, balayage, nettoyage des entrées et cages d'escaliers, entretien des baies vitrées. Les informations sur des anomalies ou dysfonctionnements doivent être répercutées à l'encadrant. Trois sites d'immeubles sont entretenus d'où la nécessité de permis B pour conduire le véhicule de service qui achemine le personnel. Les horaires de travail sont de 7 h 15 à 11 h 15, c'est-à-dire 20 heures par semaine. Dès l'entrée sur le chantier, un accompagnement sera effectué aussi sur le budget (dettes, retard factures, huissier..), le logement, la santé. Un contrat d'engagement permettra de donner du sens à une recherche d'emploi par la formation. Les agents seront accompagnés jusqu'à l'organisme de formation et/ou l'entreprise.",
        appellation_modifiee: "agent d'entretien des locaux",
      },
      {
        id: 2575,
        rome: "Aménagement et entretien des espaces verts (A1203)",
        cree_le: "2020-06-25T11:36:36.701816+02:00",
        mis_a_jour_le: "2021-08-19T12:18:01.711697+02:00",
        recrutement_ouvert: "True",
        description:
          "Les agents du chantier d'insertion porté par le CCAS de pont-à-Mousson exécutent des travaux d'entretien de la Ville de pont-à-Mousson : tonte, taille des haies, débroussaillage des espaces naturels verts correspondants à des superficies importantes, ce qui nécessite une bonne condition physique car beaucoup de distance à parcourir. Le travail est effectué par tous les temps que comporte le climat : pluie, soleil, neige, brouillard. Les agents sont dotés d'un équipement de protection individuelle, deux encadrants accompagnent les salariés pour apprendre les gestes professionnels, orienter vers une insertion professionnelle. Les agents peuvent effectuer des travaux de rénovation d'appartement selon leurs compétences ou souhaitant acquérir des compétences dans ce domaine. Le temps de travail est de 20 heures par semaine alternativement une semaine le matin et l'autre semaine l'après midi.\r\nLes agents sont accompagnés socialement (logement, budget, dettes, santé, mobilité) et professionnellement par une accompagnatrice socio professionnelle, à l'entrée sur le chantier ils signeront un contrat d'engagement sur l'accompagnement dont ils ont besoin en terme social (recherche de logement, de permis de conduire, de démarches administratives, de santé, de budget) et de terme professionnel (accèder à un emploi par la formation). Ils acceptent de faire des démarches pour accéder à un emploi plus stable sur un temps de parcours à définir.",
        appellation_modifiee: "agent polyvalent espaces verts et bâtiment",
      },
    ],
  },
  {
    cree_le: "2019-12-05T15:37:56.609000+01:00",
    mis_a_jour_le: "2021-01-26T11:35:29.848770+01:00",
    siret: "34072358400090",
    type: "ACI",
    raison_sociale: "SOLIDARITES NATIONALES ET INTERNATIONALES",
    enseigne: "Solidarités Nationales et Internationales",
    site_web: "https://sni-pam.fr",
    description:
      "Notre objet social\r\nOrganiser et participer à toute action de solidarité.\r\n\r\nNotre zone d’intervention\r\nLe Val de Lorraine.\r\n\r\nNos activités\r\nL’ACCUEIL SOCIAL ET LES AIDES D’URGENCE\r\n•\tUne section « surendettement » depuis août 2002 avec service de gestion de la dette (compte séparé) et accompagnement au montage et au suivi des dossiers.\r\n•\tUn partenariat étroit avec l’association départementale des consommateurs.\r\n•\tDistribution de colis alimentaires, toute l’année depuis 1989, deux fois par mois, avec la Banque Alimentaire.\r\n•\tDons de meubles, de vaisselle et de vêtements.\r\n\r\nL’INSERTION SOCIO-PROFESSIONNELLE\r\n•\tUne aide à la recherche d’emploi pour toute personne dans son parcours d’insertion : constitution de CV, rédaction de lettres de motivation, consultation d’offres d’emploi, contacts avec les entreprises, et utilisation des outils de recherche d’emploi.\r\n•\tL’accueil de personnes en chantiers extérieurs (5 postes en simultané pour des détenus en aménagement de peine)\r\n•\tAction Chrysalide : Accompagnement des mono-parents dans leur insertion professionnelle et dans leur recherche de mode de garde d'enfants en partenariat avec le Conseil Départemental 54 et la Mission Locale du Val de Lorraine.\r\n \r\nLES CHANTIERS D’INSERTION PAR L’ACTIVITE ECONOMIQUE\r\n POUR DES PERSONNES EN DIFFICULTE\r\n•\tDes jardins de la solidarité : ouverts à Blénod en 1993 et à Dieulouard en 1994, désormais installés à Jézainville (10 salariés en insertion). La production maraîchère est vendue sous forme de cartes-légumes et donnée à la distribution alimentaire. En développement, l’activité d’entretien des espaces verts et travaux d’hiver emploie 8 salariés sur les 10.\r\n•\tUn atelier Second œuvre : créé en 1995 à Dieulouard (10 salariés en insertion), l’ancien chantier Bois a été fermé en 2017. Le chantier continue sur des activités de second œuvre du bâtiment : peinture, pose de carrelage, placoplâtre, petite menuiserie, travaux de rénovation…\r\n•\tFrip’fouille : un chantier autour de la couture, de la récupération de vêtements depuis 1995 (10 salariés en insertion). Le tri des vêtements permet la mise en vente d’habits et objets de seconde main, le reliquat est vendu au poids. Des prestations de retouche et de repassage sont également proposées aux particuliers.\r\n•\tSolidarités meubles : un service de débarras et d’enlèvement d’objets, de reconditionnement et de mise en vente (15 salariés en insertion). Ce chantier est relié à une salle des ventes de meubles, d’électroménager, de bibelots, de livres et de vêtements ouverte à tout public (création en 1990-statut chantier d’insertion en 2002). Le chantier assure aussi les déménagements sociaux.\r\n•\tMénages Services : depuis mars 2007 réalise le ménage et l’entretien des parties communes des bâtiments de Meurthe et Moselle Habitat avec une équipe de 20 salariés en insertion, ainsi que d’autres prestations : enlèvements d’hétérogènes, maintenance de premier niveau en installation d’éclairage, nettoyage industriel. Entretien de locaux de chantier dans le cadre de clauses d’insertion des marchés publics.\r\n\r\nUN SECTEUR ANIMATION\r\n•\tDes activités éducatives périscolaires pour des enfants du primaire depuis 1988.\r\n•\tDes animations de quartier toute l’année depuis septembre 2002, pour les jeunes de 11 à 17 ans.\r\n•\tLe soutien au montage de projets de jeunes (ex : chantiers humanitaires, mini-camps...)\r\n•\tDes loisirs de proximité, vacances familiales pour familles à petit budget depuis 1998.\r\n•\tDes animations grand public destinées à faire découvrir les pratiques de Solidarité Internationale (Semaine de la Solidarité Internationale, Marché de Noël...)\r\n\r\nDES ACTIONS A L’INTERNATIONAL\r\n•\tAide au développement de communes au nord du Sénégal dans les secteurs de l’accès à l’eau, de la santé, de l’éducation et de l’aide aux groupements féminins par la mise en place de jardins sahéliens (culture goutte à goutte). \r\n•\tOrganisation et accompagnement de chantiers de jeunes (selon les recommandations du Ministère des Affaires Etrangères).\r\n\r\nNos partenaires\r\n Le Fonds Social Européen\r\nLa Préfecture - La DIRECCTE\r\nLa DDCS\r\nLe Conseil Régional Grand Est\r\nLe Conseil Départemental de Meurthe-et-Moselle\r\nPôle Emploi\r\nLa Communauté de Communes \r\nDu Bassin de Pont-à-Mousson \r\nLa Caisse d’Allocations Familiales\r\nLa Caisse Primaire d’Assurance Maladie\r\nLes Communes et les CCAS de Pont-à-Mousson, Blénod et Dieulouard, \r\nMécénat de la Caisse d’Epargne\r\nLa Résidence Sociale de Procheville\r\nId’ées Intérim\r\nLes Services Pénitentiaires\r\nLa Mission locale du Val de Lorraine et de Laxou\r\nLa MTEF Le PLIE du Val de Lorraine\r\nSolidarité Laïque\r\nLa ligue de l’enseignement 54",
    bloque_candidatures: false,
    addresse_ligne_1: "13 Rue du Four",
    addresse_ligne_2: "",
    code_postal: "54700",
    ville: "Pont-à-Mousson",
    departement: "54",
    postes: [
      {
        id: 23165,
        rome: "Nettoyage de locaux (K2204)",
        cree_le: "2021-09-27T10:56:26.854596+02:00",
        mis_a_jour_le: "",
        recrutement_ouvert: "True",
        description:
          "Dans le cadre d'un contrat d'insertion par l'IAE, pour l'activité Ménages Services, vous serez chargé de : \r\nNettoyage des entrées et des montées d'escaliers du parc HLM Pompey et alentours\r\nUtilisation du chariot de nettoyage, lessivage et décapage des parties communes\r\nPoste réservé au public éligible à l'insertion et résidant sur le territoire du Val de Lorraine\r\nPermis B souhaité. \r\nPort de charge répétée. Montées et descentes d'escaliers.\r\nCDDI 4 mois - 20 Heures Hebdo. SMIC horaire",
        appellation_modifiee:
          "Agent/Agente de propreté Parc HLM - Pompey et alentours",
      },
      {
        id: 14079,
        rome: "Maintenance des bâtiments et des locaux (I1203)",
        cree_le: "2021-01-26T11:10:21.598268+01:00",
        mis_a_jour_le: "2021-03-03T11:31:10.637670+01:00",
        recrutement_ouvert: "True",
        description:
          "Dans le cadre d'un contrat d'insertion par l'IAE, pour l'activité Petits Travaux et Finitions, \r\nVous réalisez divers travaux de rénovation intérieure (peinture, pose de papier peint, de revêtements de sol et de plaques d'isolation. Travaux de maçonnerie.\r\nPoste réservé au public éligible à l'insertion et résidant sur le territoire du Val de Lorraine\r\nPermis B . Port de charges lourdes.\r\nCDDI 4 mois - 24 Heures Hebdo. SMIC horaire",
        appellation_modifiee:
          "Agent/Agente d'entretien en second oeuvre - Pont-à-Mousson",
      },
      {
        id: 23167,
        rome: "Nettoyage de locaux (K2204)",
        cree_le: "2021-09-27T10:59:19.650526+02:00",
        mis_a_jour_le: "",
        recrutement_ouvert: "True",
        description:
          "Dans le cadre d'un contrat d'insertion par l'IAE, pour l'activité Ménages Services, vous serez chargé de : \r\nvous effectuez le ramassage des hétérogènes et autres déchets dans les espaces extérieurs du parc HLM et leur dépôt en déchetterie\r\nPoste réservé au public éligible à l'insertion et résidant sur le territoire du Val de Lorraine\r\nPermis B . Port de charges lourdes.\r\nCDDI 4 mois - 20 Heures Hebdo. SMIC horaire",
        appellation_modifiee:
          "Agent/Agente de collecte des hétérogènes - Pompey et alentours",
      },
      {
        id: 14062,
        rome: "Nettoyage de locaux (K2204)",
        cree_le: "2021-01-26T10:25:35.367173+01:00",
        mis_a_jour_le: "2021-09-27T07:45:32.432045+02:00",
        recrutement_ouvert: "False",
        description:
          "Dans le cadre d'un contrat d'insertion par l'IAE, pour l'activité Ménages Services, vous serez chargé de : \r\nvous effectuez le ramassage des hétérogènes et autres déchets dans les espaces extérieurs du parc HLM et leur dépôt en déchetterie\r\nPoste réservé au public éligible à l'insertion et résidant sur le territoire du Val de Lorraine\r\nPermis B . Port de charges lourdes.\r\nCDDI 4 mois - 20 Heures Hebdo. SMIC horaire",
        appellation_modifiee:
          "Agent/Agente de collecte des hétérogènes - Pont-à-Mousson",
      },
      {
        id: 14060,
        rome: "Nettoyage de locaux (K2204)",
        cree_le: "2021-01-26T10:16:06.137016+01:00",
        mis_a_jour_le: "2021-09-07T11:54:38.218356+02:00",
        recrutement_ouvert: "False",
        description:
          "Dans le cadre d'un contrat d'insertion par l'IAE, pour l'activité Ménages Services, vous serez chargé de : \r\nNettoyage des entrées et des montées d'escaliers du parc HLM Pont-à-Mousson - Dieulouard\r\nUtilisation du chariot de nettoyage, lessivage et décapage des parties communes\r\nPoste réservé au public éligible à l'insertion et résidant sur le territoire du Val de Lorraine\r\nPermis B souhaité. \r\nPort de charge répétée. Montées et descentes d'escaliers.\r\nCDDI 4 mois - 20 Heures Hebdo. SMIC horaire\r\n",
        appellation_modifiee:
          "Agent/Agente de propreté Parc HLM - Pont-à-Mousson - Dieulouard",
      },
      {
        id: 14084,
        rome: "Nettoyage de locaux (K2204)",
        cree_le: "2021-01-26T11:31:29.416566+01:00",
        mis_a_jour_le: "2021-01-28T11:45:31.958504+01:00",
        recrutement_ouvert: "False",
        description:
          "Dans le cadre d'un contrat d'insertion par l'IAE, pour la salle des ventes, vous serez chargé de : \r\nNettoyage des locaux (salle des ventes, bureaux, sanitaires, espace de pause...).\r\nPoste réservé au public éligible à l'insertion et résidant sur le territoire du Val de Lorraine\r\nPort de charge répétée. Montées et descentes d'escaliers.\r\nCDDI 4 mois - 20 Heures Hebdo. SMIC horaire",
        appellation_modifiee:
          "Agent/Agente de propreté et d'hygiène - Pont-à-Mousson",
      },
      {
        id: 14067,
        rome: "Revalorisation de produits industriels (K2304)",
        cree_le: "2021-01-26T10:38:46.507153+01:00",
        mis_a_jour_le: "2021-09-23T15:35:47.629130+02:00",
        recrutement_ouvert: "True",
        description:
          "Dans le cadre d'un contrat d'insertion par l'IAE, pour le magasin Frip'Fouille, vous serez chargé de : \r\nréaliser le tri de vêtements, valorisation pour mise en vente, conditionnement et rangement de l'espace de vente\r\nStation debout prolongée, manipulation et transport des sacs (10kg) en montant et en descendant des escaliers\r\nPoste réservé au public éligible à l'insertion et résidant sur le territoire du Val de Lorraine\r\nCDDI 4 mois - 20 Heures Hebdo. SMIC horaire",
        appellation_modifiee: "Agent/Agente de tri de textile - Pont-à-Mousson",
      },
      {
        id: 14076,
        rome: "Revalorisation de produits industriels (K2304)",
        cree_le: "2021-01-26T11:06:37.723975+01:00",
        mis_a_jour_le: "2021-09-08T08:07:16.426200+02:00",
        recrutement_ouvert: "False",
        description:
          "Dans le cadre d'un contrat d'insertion par l'IAE, pour l'activité Solidarités Meubles, \r\nVous effectuez l'accueil, le conseil et l'orientation des usagers sur les sites des déchetteries de Pont-à-Mousson et de Dieulouard.\r\nPoste réservé au public éligible à l'insertion et résidant sur le territoire du Val de Lorraine\r\nPort de charges.\r\nVous travaillez les samedis et dimanches matin et vous devez pouvoir vous rendre sur les deux sites par vos propres moyens.\r\nDes qualités relationnelles sont requises pour ce poste.\r\nCDDI 4 mois - 20 Heures Hebdo. SMIC horaire",
        appellation_modifiee:
          "Agent/Agente de déchetterie - Pont-à-Mousson - Dieulouard",
      },
      {
        id: 14065,
        rome: "Conduite et livraison par tournées sur courte distance (N4105)",
        cree_le: "2021-01-26T10:31:31.899235+01:00",
        mis_a_jour_le: "2021-09-16T13:55:08.171138+02:00",
        recrutement_ouvert: "False",
        description:
          "Dans le cadre d'un contrat d'insertion par l'IAE, pour l'activité Solidarités Meubles, \r\nVous effectuez les enlèvements et les livraisons de mobiliers ainsi que les débarras et les déménagements\r\nVous réalisez le montage et le démontage de meubles et l'agencement de la salle des ventes et des zones de stockage\r\nPoste réservé au public éligible à l'insertion et résidant sur le territoire du Val de Lorraine\r\nPermis B . Port de charges lourdes.\r\nCDDI 4 mois - 20 Heures Hebdo. SMIC horaire",
        appellation_modifiee:
          "Chauffeur-Livreur/ Chauffeuse-livreuse Manutentionnaire - Pont-à-Mousson",
      },
      {
        id: 14068,
        rome: "Courses et livraisons express (N4104)",
        cree_le: "2021-01-26T10:42:39.233414+01:00",
        mis_a_jour_le: "2021-09-16T15:14:36.803862+02:00",
        recrutement_ouvert: "True",
        description:
          "Dans le cadre d'un contrat d'insertion par l'IAE, vous effectuez le tri et la distribution du courrier auprès de particuliers et de structures de la ville de Pont-à-Mousson. La tournée s'effectue à vélo.\r\nVous êtes capable d'organiser votre tournée de manière optimale, vous savez lire un plan et vous connaissez les rues de Pont-à-Mousson.\r\nSavoir lire, écrire et compter\r\nPoste réservé au public éligible à l'insertion et résidant sur le territoire du Val de Lorraine\r\nCDDI 4 mois - 20 Heures Hebdo. SMIC horaire",
        appellation_modifiee: "Coursier/ Coursière à vélo - Pont-à-Mousson",
      },
      {
        id: 19792,
        rome: "Encadrement technique en insertion professionnelle (K1203)",
        cree_le: "2021-06-11T10:50:00.415914+02:00",
        mis_a_jour_le: "2021-08-16T09:44:24.939156+02:00",
        recrutement_ouvert: "False",
        description:
          "Poste à pourvoir dans le cadre d'un parcours d'insertion par l'activité économique et résider sur le territoire du Val de Lorraine. Vérifier votre éligibilité auprès de votre conseiller Pôle Emploi. \r\nSous la responsabilité de l'encadrante technique d'insertion, vous\r\n- participez avec l'équipe à l'activité de production de Solidarités Meubles et du magasin Frip'Fouille\r\n- aidez à la mise en œuvre et à l'exécution des consignes données par l'encadrante\r\n- assurez le contrôle, l'ouverture et la fermeture des caisses, ainsi que l'ouverture et la fermeture du magasin\r\n- et établissez des devis d'enlèvement de meubles ou de débarras de maison pour les particuliers.\r\nEn l'absence de l'encadrante, vous supervisez et encadrez une équipe de 30 salariés en insertion.\r\nPort de charges lourdes et répétitif. Station debout prolongée.\r\nUne expérience en vente/commerce est appréciée. Bonnes aptitudes à l'encadrement d'équipe.\r\nPermis B exigé. Travail réparti du lundi au samedi avec deux jours de repos par semaine.\r\nCDDI de 28 heures par semaine. SMIC Horaire.",
        appellation_modifiee:
          "Assistant/assistante encadrant technique d'insertion H/F",
      },
      {
        id: 17619,
        rome: "Saisie de données (M1606)",
        cree_le: "2021-04-21T13:33:55.168280+02:00",
        mis_a_jour_le: "2021-09-09T08:24:13.421547+02:00",
        recrutement_ouvert: "False",
        description:
          "Dans le cadre d'un contrat d'insertion par l'IAE, pour la salle des ventes, vous serez chargé de : \r\nMise en vente de produits en ligne\r\nSaisie informatique\r\nBonne connaissance de l'outil informatique, EXEL, WORD",
        appellation_modifiee: "Vente en ligne et saisie informatique",
      },
      {
        id: 14070,
        rome: "Revalorisation de produits industriels (K2304)",
        cree_le: "2021-01-26T10:47:40.630470+01:00",
        mis_a_jour_le: "2021-07-28T13:17:01.781214+02:00",
        recrutement_ouvert: "False",
        description:
          "Dans le cadre d'un contrat d'insertion par l'IAE, pour la salle des ventes, vous serez chargé de : \r\nréaliser le tri des objets (vaisselle, bibelot...), leur nettoyage, et leur valorisation pour mise en vente, conditionnement et rangement de l'espace de vente\r\nStation debout prolongée, manipulation et transport des marchandises (20kg) en montant et en descendant des escaliers\r\nPoste réservé au public éligible à l'insertion et résidant sur le territoire du Val de Lorraine\r\nCDDI 4 mois - 20 Heures Hebdo. SMIC horaire",
        appellation_modifiee: "Agent/Agente de tri - Pont-à-Mousson",
      },
      {
        id: 14081,
        rome: "Horticulture et maraîchage (A1414)",
        cree_le: "2021-01-26T11:14:12.859574+01:00",
        mis_a_jour_le: "2021-09-08T08:07:16.446974+02:00",
        recrutement_ouvert: "False",
        description:
          "Dans le cadre d'un contrat d'insertion par l'IAE, pour les Jardins de la Solidarité à Jézainville, vous serez chargé de : \r\nCulture de légumes sur site, récolte, entretien du jardin.\r\nVous serez chargé de préparer les paniers de légumes destinés à la vente.\r\nPoste réservé au public éligible à l'insertion et résidant sur le territoire du Val de Lorraine\r\nCDDI 4 mois - 20 Heures Hebdo. SMIC horaire",
        appellation_modifiee: "Maraîcher/Maraîchère - Jézainville",
      },
      {
        id: 14082,
        rome: "Aménagement et entretien des espaces verts (A1203)",
        cree_le: "2021-01-26T11:20:41.663854+01:00",
        mis_a_jour_le: "2021-09-08T15:05:04.244836+02:00",
        recrutement_ouvert: "False",
        description:
          "Dans le cadre d'un contrat d'insertion par l'IAE, pour les Jardins de la Solidarité à Jézainville, vous serez chargé de : \r\nréaliser l'entretien des espaces verts (tonte, débroussaillage, taille de haies...) pour une clientèle constituée de particuliers, entreprises et collectivités. Entretien des machines et nettoyage de chantiers.\r\nVous savez manier les outils.\r\nQualités relationnelles requises.\r\nPermis B souhaité.\r\nPoste réservé au public éligible à l'insertion et résidant sur le territoire du Val de Lorraine\r\nCDDI 4 mois - 20 Heures Hebdo. SMIC horaire",
        appellation_modifiee:
          "Ouvrier/Ouvrière d'entretien des espaces verts - Jézainville",
      },
      {
        id: 14072,
        rome: "Revalorisation de produits industriels (K2304)",
        cree_le: "2021-01-26T10:59:31.227308+01:00",
        mis_a_jour_le: "2021-08-16T07:56:40.589779+02:00",
        recrutement_ouvert: "False",
        description:
          "Dans le cadre d'un contrat d'insertion par l'IAE, pour la salle des ventes, vous serez chargé de : \r\nréaliser le tri des livres, leur valorisation pour mise en vente, conditionnement et rangement de l'espace de vente.\r\nVous organisez et vous animez le rayon livres.\r\nSavoir lire, écrire et compter.\r\nIntérêt pour la littérature\r\nStation debout prolongée, manipulation et transport des marchandises (20kg) en montant et en descendant des escaliers\r\nPoste réservé au public éligible à l'insertion et résidant sur le territoire du Val de Lorraine\r\nCDDI 4 mois - 20 Heures Hebdo. SMIC horaire",
        appellation_modifiee: "Agent/Agente de tri de livres - Pont-à-Mousson",
      },
      {
        id: 14054,
        rome: "Vente en habillement et accessoires de la personne (D1214)",
        cree_le: "2021-01-26T09:35:19.863674+01:00",
        mis_a_jour_le: "2021-08-11T12:08:29.898440+02:00",
        recrutement_ouvert: "False",
        description:
          "Dans le cadre d'un contrat d'insertion par l'IAE, pour le magasin Frip'Fouille, vous serez chargé de : \r\nAccueil, conseil client, encaissement et rangement de l'espace de vente\r\nSavoir lire, écrire et compter\r\nPoste réservé au public éligible à l'insertion et résidant sur le territoire du Val de Lorraine\r\nCDDI 4 mois - 20 Heures Hebdo. SMIC horaire",
        appellation_modifiee:
          "Vendeur/Vendeuse en prêt-à-porter - Pont-à-Mousson",
      },
      {
        id: 14064,
        rome: "Vente en décoration et équipement du foyer (D1212)",
        cree_le: "2021-01-26T10:27:59.186355+01:00",
        mis_a_jour_le: "2021-06-03T15:24:40.207236+02:00",
        recrutement_ouvert: "False",
        description:
          "Dans le cadre d'un contrat d'insertion par l'IAE, pour la salle des ventes, vous serez chargé de : \r\nAccueil physique et téléphonique, conseil client, encaissement et rangement de l'espace de vente\r\nSavoir lire, écrire et compter\r\nPoste réservé au public éligible à l'insertion et résidant sur le territoire du Val de Lorraine\r\nCDDI 4 mois - 20 Heures Hebdo. SMIC horaire",
        appellation_modifiee:
          "Vendeur/Vendeuse en équipements du foyer - Pont-à-Mousson",
      },
    ],
  },
  {
    cree_le: "2019-12-05T15:37:56.609000+01:00",
    mis_a_jour_le: "2021-07-12T11:31:01.334088+02:00",
    siret: "34394583800039",
    type: "AI",
    raison_sociale: "ASSOC FENSCH COUP DE MAIN",
    enseigne: "A.I. FENSCH COUP DE MAIN",
    site_web: "http://www.fenschcoupdemain.fr",
    description:
      "Fensch Coup De main met à disposition, auprès de particuliers, d’associations, de collectivités et d’entreprises, les personnes qu’elle embauche et qui connaissent des difficultés particulières d’insertion sociale et professionnelle.\r\nElle propose aux personnes éloignées de l’emploi un accompagnement socioprofessionnel individualisé afin de favoriser un retour vers l’emploi durable.",
    bloque_candidatures: false,
    addresse_ligne_1: "5 Place Nicolas Schneider",
    addresse_ligne_2: "",
    code_postal: "57700",
    ville: "Hayange",
    departement: "57",
    postes: [
      {
        id: 22543,
        rome: "Encadrement technique en insertion professionnelle (K1203)",
        cree_le: "2021-09-09T09:11:34.340944+02:00",
        mis_a_jour_le: "",
        recrutement_ouvert: "True",
        description:
          "FENSCH COUP DE MAIN : Insertion par l’activité économique\r\nVous serez chargé d’accompagner les salariés en insertion par l’activité économique dans leur parcours socio-professionnel\r\n•\tRéaliser des entretiens individuels\r\n•\tÉtablir un bilan social\r\n•\tDéfinir des objectifs et les étapes du parcours d’insertion\r\n•\tAssurer le suivi en situation de travail et proposer des axes d’orientation\r\n\r\nCDD 6 mois puis CDI\r\n35 heures hebdomadaires Salaire : Selon grille indiciaire\r\n\r\nPROFIL SOUHAITE\r\nDiplôme ou expérience dans le domaine de l’insertion Professionnelle \r\nDébutant accepté\r\n\r\nPermis de conduire\r\nTravail en partenariat, en équipe et en autonomie\r\n",
        appellation_modifiee: "",
      },
      {
        id: 2203,
        rome: "Comptabilité (M1203)",
        cree_le: "2020-06-12T11:05:40.683902+02:00",
        mis_a_jour_le: "2021-09-09T09:06:21.776231+02:00",
        recrutement_ouvert: "False",
        description:
          "Mission :\r\n\r\nL’agent comptable assure la comptabilité de l’ensemble de l’association et la gestion des salaires en respectant les procédures internes et les normes comptables françaises.\r\n\r\nPrincipales activités :\r\n•\tÉtablir les fiches de paie du personnel, les déclarations fiscales et sociales.\r\n•\tÉtablir la DSN et déversement des données à la direction du travail\r\n•\tÉtablir et suivre le traitement des factures clients et fournisseurs.\r\n•\tEncaissement des règlements clients et dépôt en banques\r\n•\tRelancer les clients qui n’ont pas payé leurs factures.\r\n•\tDéclarations annuelles des attestations fiscales\r\n•\tSuivi et pointage des mouvements des comptes bancaires avec justificatifs et remise au cabinet comptable\r\n•\tEnregistrer les opérations comptables dans les livres comptables.\r\n•\tÉlaborer les documents de synthèse : comptes de résultat, balances de comptes, bilans comptables, etc., qui seront vérifiés par l'expert-comptable. \r\n•\tDresser un état mensuel de la situation comptable de l’entreprise.\r\n•\tÉlaborer un budget prévisionnel\r\n•\tDéclarations des IJ CPAM \r\n\r\nCompétences spécifiques liées à la fonction : \r\n\r\n•\tConnaissances \r\nMaîtrise des outils bureautiques\r\nConnaissance de l’IAE\r\n\r\n•\tCompétences humaines\r\nEtre organisé, rigoureux\r\nS’assurer de l'application des règles, normes et procédures en matière de comptabilité\r\nConnaissance des principes et de la réglementation comptable\r\n\r\n•\tCompétences métier\r\nRespect du devoir de réserve et du principe de discrétion professionnelle.\r\nMinutie, ordre et réactivité ainsi que précision et organisation\r\n",
        appellation_modifiee: "Agent comptable",
      },
      {
        id: 5430,
        rome: "Services domestiques (K1304)",
        cree_le: "2020-09-17T08:22:57.323940+02:00",
        mis_a_jour_le: "",
        recrutement_ouvert: "True",
        description: "",
        appellation_modifiee: "",
      },
      {
        id: 5550,
        rome: "Assistance auprès d'adultes (K1302)",
        cree_le: "2020-09-17T14:13:58.694806+02:00",
        mis_a_jour_le: "",
        recrutement_ouvert: "True",
        description:
          " Il exerce auprès des personnes fragiles, dépendantes ou en difficulté sociale. Il intervient auprès des familles, enfants, personnes âgées, personnes malades ou personnes handicapées.",
        appellation_modifiee: "",
      },
      {
        id: 20007,
        rome: "Aménagement et entretien des espaces verts (A1203)",
        cree_le: "2021-06-17T10:25:52.220038+02:00",
        mis_a_jour_le: "",
        recrutement_ouvert: "True",
        description:
          "Permis B obligatoire\r\nZone d'intervention : Val De Fensch\r\nTâches principales : Tonte, taille, débroussaillage, bêchage\r\nSavoir utiliser : motobineuse, motoculteur, taille haie, souffleur, karcher, tondeuse, débroussailleuse \r\nExpérience souhaitée",
        appellation_modifiee: "",
      },
    ],
  },
];
