import { SearchImmersionResultDto } from "src/../../shared/src";

export default [
  {
    naf: "5610C",
    name: "ANTOINE EBERSCHWEILER",
    rome: "G1601",
    siret: "88348840500019",
    address: {
      city: "Bois-d'Arcy",
      postcode: "78390",
      departmentCode: "78",
      streetNumberAndAddress: "Avenue Paul Vaillant Couturier",
    },
    website: "https://veganescape.fr/",
    nafLabel: "Restaurants et services de restauration mobile",
    position: { lat: 48.7994111, lon: 2.0196881 },
    romeLabel: "Management du personnel de cuisine",
    distance_m: 23022.95436875,
    contactMode: "EMAIL",
    customizedName: "VEGAN escape",
    appellationLabels: ["Chef cuisinier / cuisinière"],
    voluntaryToImmersion: true,
    additionalInformation:
      "Service de restauration à emporter et en livraison. Le meilleur de la street food en version végétale 😋",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "",
  },
  {
    naf: "4722Z",
    name: "LAURENT CHARTRAIN",
    rome: "D1106",
    siret: "48341917200018",
    address: {
      city: "LA FERTE-ALAIS",
      postcode: "91590",
      departmentCode: "91",
      streetNumberAndAddress: "37 RUE NOTRE DAME",
    },
    website: "",
    nafLabel:
      "Commerce de détail de viandes et de produits à base de viande en magasin spécialisé",
    position: { lat: 48.482747, lon: 2.347021 },
    romeLabel: "Vente en alimentation",
    distance_m: 41875.54174014,
    contactMode: "EMAIL",
    appellationLabels: ["Vendeur / Vendeuse en boucherie-charcuterie"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "3-5",
  },
  {
    naf: "8899B",
    name: "AADSP NORD EST VAL D OISE",
    rome: "K1302",
    siret: "78864748500010",
    address: {
      city: "SARCELLES",
      postcode: "95200",
      departmentCode: "95",
      streetNumberAndAddress: "18 AV DU HUIT MAI 1945",
    },
    website: "",
    nafLabel: "Autre action sociale sans hébergement n.c.a.",
    position: { lat: 48.977571, lon: 2.372547 },
    romeLabel: "Assistance auprès d'adultes",
    distance_m: 13747.89083352,
    contactMode: "EMAIL",
    appellationLabels: ["Assistant / Assistante de vie"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "20-49",
  },
  {
    naf: "8710A",
    name: "SNC VILLA LECOURBE",
    rome: "C1401",
    siret: "45059294400026",
    address: {
      city: "PARIS 15",
      postcode: "75015",
      departmentCode: "75",
      streetNumberAndAddress: "286 RUE LECOURBE",
    },
    website: "",
    nafLabel: "Hébergement médicalisé",
    position: { lat: 48.838265, lon: 2.287877 },
    romeLabel: "Gestion en banque et assurance",
    distance_m: 3291.34977462,
    contactMode: "EMAIL",
    appellationLabels: ["Agent / Agente d'accueil de prestations sociales"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "50-99",
  },
  {
    naf: "6920Z",
    name: "ADEXCO",
    rome: "M1203",
    siret: "33995226900027",
    address: {
      city: "PARIS 20",
      postcode: "75020",
      departmentCode: "75",
      streetNumberAndAddress: "55 RUE PIXERECOURT",
    },
    website: "",
    nafLabel: "Activités comptables",
    position: { lat: 48.873197, lon: 2.395921 },
    romeLabel: "Comptabilité",
    distance_m: 5790.11100579,
    contactMode: "EMAIL",
    appellationLabels: ["Comptable service paie", "Comptable unique"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "20-49",
  },
  {
    naf: "8810A",
    name: "AUXI'LIFE 91",
    rome: "K1302",
    siret: "48858103400045",
    address: {
      city: "Évry",
      postcode: "91000",
      departmentCode: "91",
      streetNumberAndAddress: "32 Allée Jean Rostand",
    },
    website: "https://www.auxilife.fr/",
    nafLabel:
      "Action sociale sans hébergement pour personnes âgées et pour personnes handicapées",
    position: { lat: 48.6252849, lon: 2.4315101 },
    romeLabel: "Assistance auprès d'adultes",
    distance_m: 27240.98144628,
    contactMode: "EMAIL",
    appellationLabels: ["Auxiliaire de Vie Sociale -AVS-"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "20-49",
  },
  {
    naf: "4321A",
    name: "INNOVATIVE & SMART BUILDINGS",
    rome: "I1309",
    siret: "82771969100012",
    address: {
      city: "Clichy",
      postcode: "92110",
      departmentCode: "92",
      streetNumberAndAddress: "7 Rue André Citroën",
    },
    website: "",
    nafLabel: "Installation électrique",
    position: { lat: 48.906743, lon: 2.316583 },
    romeLabel: "Maintenance électrique",
    distance_m: 5327.64762562,
    contactMode: "EMAIL",
    appellationLabels: [
      "Électricien de maintenance itinérant / Électricienne de maintenance itinérante",
    ],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "3-5",
  },
  {
    naf: "4711B",
    name: "3K ROSNY",
    rome: "D1106",
    siret: "84818553400015",
    address: {
      city: "Rosny-sous-Bois",
      postcode: "93110",
      departmentCode: "93",
      streetNumberAndAddress: "Boulevard de la Boissière",
    },
    website: "",
    nafLabel:
      "Commerce de détail en magasin non spécialisé à prédominance alimentaire",
    position: { lat: 48.873611, lon: 2.47053 },
    romeLabel: "Vente en alimentation",
    distance_m: 11161.78248917,
    contactMode: "PHONE",
    appellationLabels: ["Vendeur / Vendeuse en boucherie"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "3-5",
  },
  {
    naf: "1071C",
    name: "BOULANGERIE MANGIN",
    rome: "D1104",
    siret: "83303844100014",
    address: {
      city: "AUNEAU-BLEURY-SAINT-SYMPHORIEN",
      postcode: "28700",
      departmentCode: "28",
      streetNumberAndAddress: "4 RUE DE CHARTRES",
    },
    website: "",
    nafLabel: "Fabrication de pain et de pâtisserie fraîche",
    position: { lat: 48.462513, lon: 1.772643 },
    romeLabel: "Pâtisserie, confiserie, chocolaterie et glacerie",
    distance_m: 59741.11585261,
    contactMode: "IN_PERSON",
    appellationLabels: ["Pâtissier / Pâtissière"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "3-5",
  },
  {
    naf: "8559A",
    name: "PROMEO ASSOCIATION DE FORMATION POUR LE DEVELOPPEMENT DE L EMPLOI DE PICARDIE - PROMEO AFDE PICARDIE",
    rome: "H2503",
    siret: "39131533000087",
    address: {
      city: "BEAUVAIS",
      postcode: "60000",
      departmentCode: "60",
      streetNumberAndAddress: "240 AV MARCEL DASSAULT",
    },
    website: "",
    nafLabel: "Enseignements divers",
    position: { lat: 49.450541, lon: 2.097888 },
    romeLabel:
      "Pilotage d'unité élémentaire de production mécanique ou de travail des métaux",
    distance_m: 67765.11012539,
    contactMode: "EMAIL",
    customizedName: "PROMEO",
    appellationLabels: [
      "Technicien / Technicienne en pilotage et maintenance de système de production",
    ],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "20-49",
  },
  {
    naf: "1071C",
    name: "LE FOURNIL DE GUILLAUME",
    rome: "D1106",
    siret: "53992525500017",
    address: {
      city: "PARIS 7",
      postcode: "75007",
      departmentCode: "75",
      streetNumberAndAddress: "70 RUE DE SEVRES",
    },
    website: "",
    nafLabel: "Fabrication de pain et de pâtisserie fraîche",
    position: { lat: 48.847764, lon: 2.318916 },
    romeLabel: "Vente en alimentation",
    distance_m: 1240.0344284,
    contactMode: "EMAIL",
    appellationLabels: ["Vendeur / Vendeuse en boulangerie-pâtisserie"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "10-19",
  },
  {
    naf: "8790B",
    name: "COALLIA",
    rome: "M1602",
    siret: "77568030903177",
    address: {
      city: "MELUN",
      postcode: "77000",
      departmentCode: "77",
      streetNumberAndAddress: "2 AV JEAN JAURES",
    },
    website: "",
    nafLabel: "Autres activités d'hébergement social",
    position: { lat: 48.527859, lon: 2.650652 },
    romeLabel: "Opérations administratives",
    distance_m: 44130.76522615,
    contactMode: "EMAIL",
    appellationLabels: ["Agent administratif / Agente administrative"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "2000-4999",
  },
  {
    naf: "5621Z",
    name: "LE BON BOCAL",
    rome: "K1205",
    siret: "82393005200027",
    address: {
      city: "BAILLY-ROMAINVILLIERS",
      postcode: "77700",
      departmentCode: "77",
      streetNumberAndAddress: "16 AV CHRISTIAN DOPPLER",
    },
    website: "",
    nafLabel: "Services des traiteurs",
    position: { lat: 48.842565, lon: 2.799434 },
    romeLabel: "Information sociale",
    distance_m: 35229.57462975,
    contactMode: "EMAIL",
    customizedName: "SAS",
    appellationLabels: ["Interface de communication"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "10-19",
  },
  {
    naf: "8121Z",
    name: "EMMANUEL LISE",
    rome: "E1101",
    siret: "47961513000024",
    address: {
      city: "CLICHY-SOUS-BOIS",
      postcode: "93390",
      departmentCode: "93",
      streetNumberAndAddress: "7 ALL ROMAIN ROLLAND",
    },
    website: "",
    nafLabel: "Nettoyage courant des bâtiments",
    position: { lat: 48.904144, lon: 2.553338 },
    romeLabel: "Animation de site multimédia",
    distance_m: 17835.99589761,
    contactMode: "EMAIL",
    customizedName: "MIRAATHIZONE",
    appellationLabels: ["Community manager"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "",
  },
  {
    naf: "1071B",
    name: "RAPIDO'PIZZA",
    rome: "G1604",
    siret: "49362099100015",
    address: {
      city: "GAILLON",
      postcode: "27600",
      departmentCode: "27",
      streetNumberAndAddress: "85 RUE DU GENERAL DE GAULLE",
    },
    website: "",
    nafLabel: "Fabrication de pain et de pâtisserie fraîche",
    position: { lat: 49.160259, lon: 1.330341 },
    romeLabel: "Fabrication de crêpes ou pizzas",
    distance_m: 79784.07969673,
    contactMode: "EMAIL",
    customizedName: "Rapidopizza",
    appellationLabels: ["Pizzaïolo / Pizzaïola"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "1-2",
  },
  {
    naf: "4722Z",
    name: "BOUCHERIE DE LA PRAIRIE",
    rome: "D1103",
    siret: "45072117000014",
    address: {
      city: "VILLERS-SUR-AUCHY",
      postcode: "60650",
      departmentCode: "60",
      streetNumberAndAddress: "7 RUE DE LA SOURCE",
    },
    website: "",
    nafLabel:
      "Commerce de détail de viandes et de produits à base de viande en magasin spécialisé",
    position: { lat: 49.473729, lon: 1.795282 },
    romeLabel: "Charcuterie - traiteur",
    distance_m: 78358.38211462,
    contactMode: "EMAIL",
    customizedName: "saveurs des prairies",
    appellationLabels: ["Charcutier-traiteur / Charcutière-traiteuse"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "3-5",
  },
  {
    naf: "8710A",
    name: "BOMBON",
    rome: "J1501",
    siret: "48497667500021",
    address: {
      city: "BOMBON",
      postcode: "77720",
      departmentCode: "77",
      streetNumberAndAddress: "CHATEAU DE MONTJAY",
    },
    website: "",
    nafLabel: "Hébergement médicalisé",
    position: { lat: 48.566631, lon: 2.860153 },
    romeLabel: "Soins d'hygiène, de confort du patient",
    distance_m: 51343.36677216,
    contactMode: "EMAIL",
    appellationLabels: ["Aide-soignant / Aide-soignante"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "20-49",
  },
  {
    naf: "7022Z",
    name: "EUROGROUP CONSULTING FRANCE",
    rome: "M1205",
    siret: "32391299800081",
    address: {
      city: "COURBEVOIE",
      postcode: "92400",
      departmentCode: "92",
      streetNumberAndAddress: "25 QUAI DU PRESIDENT PAUL DOUMER",
    },
    website: "",
    nafLabel: "Conseil pour les affaires et autres conseils de gestion",
    position: { lat: 48.891526, lon: 2.257818 },
    romeLabel: "Direction administrative et financière",
    distance_m: 5831.35698835,
    contactMode: "EMAIL",
    appellationLabels: [
      "Adjoint / Adjointe au responsable des services généraux",
    ],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "250-499",
  },
  {
    naf: "7120B",
    name: "EUROVENT CERTITA CERTIFICATION",
    rome: "D1401",
    siret: "51313363700035",
    address: {
      city: "PARIS 9",
      postcode: "75009",
      departmentCode: "75",
      streetNumberAndAddress: "48 RUE DE LA VICTOIRE",
    },
    website: "",
    nafLabel: "Activités de contrôle et analyses techniques",
    position: { lat: 48.875258, lon: 2.335762 },
    romeLabel: "Assistanat commercial",
    distance_m: 2154.93649157,
    contactMode: "EMAIL",
    appellationLabels: [
      "Assistant administratif et commercial / Assistante administrative et commerciale",
    ],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "50-99",
  },
  {
    naf: "4331Z",
    name: "SAVEHO",
    rome: "F1106",
    siret: "53840754500028",
    address: {
      city: "MITRY-MORY",
      postcode: "77290",
      departmentCode: "77",
      streetNumberAndAddress: "9 AV JEAN JAURES",
    },
    website: "",
    nafLabel: "Travaux de plâtrerie",
    position: { lat: 48.954761, lon: 2.600222 },
    romeLabel: "Ingénierie et études du BTP",
    distance_m: 23141.85902379,
    contactMode: "EMAIL",
    appellationLabels: ["Assistant chargé / Assistante chargée d'affaires BTP"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "3-5",
  },
  {
    naf: "6920Z",
    name: "AGC DE SEINE NORMANDIE",
    rome: "M1202",
    siret: "77557386800418",
    address: {
      city: "CROISSY-SUR-SEINE",
      postcode: "78290",
      departmentCode: "78",
      streetNumberAndAddress: "15 ALL DES SABLIERES",
    },
    website: "",
    nafLabel: "Activités comptables",
    position: { lat: 48.875418, lon: 2.125539 },
    romeLabel: "Audit et contrôle comptables et financiers",
    distance_m: 14387.68223823,
    contactMode: "EMAIL",
    customizedName: "Cerfrance Seine Normandie - CROISSY SUR SEINE",
    appellationLabels: ["Collaborateur / Collaboratrice d'expertise comptable"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "500-999",
  },
  {
    naf: "4221Z",
    name: "LAERI T.P",
    rome: "F1202",
    siret: "52420208200011",
    address: {
      city: "Annet-sur-Marne",
      postcode: "77410",
      departmentCode: "77",
      streetNumberAndAddress: "Route de Lagny",
    },
    website: "",
    nafLabel: "Construction de réseaux pour fluides",
    position: { lat: 48.910673, lon: 2.710998 },
    romeLabel: "Direction de chantier du BTP",
    distance_m: 29245.55452604,
    contactMode: "EMAIL",
    customizedName: "SAS",
    appellationLabels: ["Chef de chantier travaux publics"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "20-49",
  },
  {
    naf: "5530Z",
    name: "GESTION PLEIN AIR",
    rome: "G1101",
    siret: "80503618300012",
    address: {
      city: "ANGICOURT",
      postcode: "60940",
      departmentCode: "60",
      streetNumberAndAddress: "CAMPING LA FALOISE",
    },
    website: "",
    nafLabel:
      "Terrains de camping et parcs pour caravanes ou véhicules de loisirs",
    position: { lat: 49.317792, lon: 2.486757 },
    romeLabel: "Accueil touristique",
    distance_m: 52467.81894561,
    contactMode: "EMAIL",
    appellationLabels: ["Hôte / Hôtesse d'accueil tourisme"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "1-2",
  },
  {
    naf: "8730A",
    name: "GROUPEMENT DE COOPERATION SOCIALE ET MEDICO SOCIALE LES EHPAD PUBLICS DU VAL DE MARNE",
    rome: "K1205",
    siret: "13000409600017",
    address: {
      city: "FONTENAY-SOUS-BOIS",
      postcode: "94120",
      departmentCode: "94",
      streetNumberAndAddress: "73 RUE D ESTIENNE D ORVES",
    },
    website: "https://www.gcsms-ehpadpublics94.fr/accueil.aspx",
    nafLabel:
      "Hébergement social pour personnes âgées ou handicapées physiques",
    position: { lat: 48.853456, lon: 2.452594 },
    romeLabel: "Information sociale",
    distance_m: 9745.8623846,
    contactMode: "EMAIL",
    appellationLabels: ["Agent / Agente d'accueil social"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "100-199",
  },
  {
    naf: "1071C",
    name: "MAISON AURELIE RIBAY",
    rome: "D1102",
    siret: "83518647900019",
    address: {
      city: "PARIS 10",
      postcode: "75010",
      departmentCode: "75",
      streetNumberAndAddress: "36 RUE DE DUNKERQUE",
    },
    website: "",
    nafLabel: "Fabrication de pain et de pâtisserie fraîche",
    position: { lat: 48.881063, lon: 2.350239 },
    romeLabel: "Boulangerie - viennoiserie",
    distance_m: 3314.87947474,
    contactMode: "EMAIL",
    customizedName: "SARL",
    appellationLabels: ["Boulanger / Boulangère"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "6-9",
  },
  {
    naf: "6619B",
    name: "LGMH FINANCE",
    rome: "M1604",
    siret: "80816799300035",
    address: {
      city: "PARIS 15",
      postcode: "75015",
      departmentCode: "75",
      streetNumberAndAddress: "12 AV DU MAINE",
    },
    website: "",
    nafLabel:
      "Autres activités auxiliaires de services financiers, hors assurance et caisses de retraite",
    position: { lat: 48.84401, lon: 2.320052 },
    romeLabel: "Assistanat de direction",
    distance_m: 1654.75829511,
    contactMode: "EMAIL",
    appellationLabels: ["Assistant / Assistante de direction"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "",
  },
  {
    naf: "5610C",
    name: "THE L'ARTISTE",
    rome: "G1602",
    siret: "83292597800013",
    address: {
      city: "MAULE",
      postcode: "78580",
      departmentCode: "78",
      streetNumberAndAddress: "1 RUE ST VINCENT",
    },
    website: "",
    nafLabel: "Restaurants et services de restauration mobile",
    position: { lat: 48.910379, lon: 1.849018 },
    romeLabel: "Personnel de cuisine",
    distance_m: 35016.32825768,
    contactMode: "EMAIL",
    appellationLabels: [
      "Commis / Commise de cuisine",
      "Cuisinier / Cuisinière",
    ],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "1-2",
  },
  {
    naf: "4722Z",
    name: "F.L.A.C.",
    rome: "D1103",
    siret: "51434220300023",
    address: {
      city: "GOURNAY-EN-BRAY",
      postcode: "76220",
      departmentCode: "76",
      streetNumberAndAddress: "26 PL NATIONALE",
    },
    website: "",
    nafLabel:
      "Commerce de détail de viandes et de produits à base de viande en magasin spécialisé",
    position: { lat: 49.482367, lon: 1.724441 },
    romeLabel: "Charcuterie - traiteur",
    distance_m: 81817.47555121,
    contactMode: "IN_PERSON",
    appellationLabels: ["Charcutier / Charcutière"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "3-5",
  },
  {
    naf: "4399C",
    name: "2BPRO",
    rome: "F1604",
    siret: "48532005500026",
    address: {
      city: "Goussainville",
      postcode: "95190",
      departmentCode: "95",
      streetNumberAndAddress: "16 Rue Cyprien Samson",
    },
    website: "",
    nafLabel: "Autres travaux de construction spécialisés n.c.a.",
    position: { lat: 49.031051, lon: 2.477379 },
    romeLabel: "Montage d'agencements",
    distance_m: 22347.19382396,
    contactMode: "EMAIL",
    customizedName: "EURL",
    appellationLabels: ["Plaquiste"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "1-2",
  },
  {
    naf: "3314Z",
    name: "SOCIETE D'ELECTROTECHNIQUE INDUSTRIELLE ET DE BOBINAGE",
    rome: "I1310",
    siret: "38056058100064",
    address: {
      city: "Passel",
      postcode: "60400",
      departmentCode: "60",
      streetNumberAndAddress: "4 Avenue du Parc",
    },
    website: "",
    nafLabel: "Réparation d'équipements électriques",
    position: { lat: 49.552164, lon: 2.962872 },
    romeLabel: "Maintenance mécanique industrielle",
    distance_m: 90215.31244327,
    contactMode: "EMAIL",
    appellationLabels: [
      "Mécanicien / Mécanicienne de maintenance industrielle",
    ],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "50-99",
  },
  {
    naf: "1071C",
    name: "CALLIOPE",
    rome: "D1106",
    siret: "79405352000019",
    address: {
      city: "Neuilly-sur-Marne",
      postcode: "93330",
      departmentCode: "93",
      streetNumberAndAddress: "Boulevard du Maréchal Foch",
    },
    website: "https://www.boulangerie-ange.fr/travailler-en-boulangerie/",
    nafLabel: "Fabrication de pain et de pâtisserie fraîche",
    position: { lat: 48.8554797, lon: 2.5265383 },
    romeLabel: "Vente en alimentation",
    distance_m: 15157.74476972,
    contactMode: "EMAIL",
    customizedName: "Boulangerie Ange",
    appellationLabels: ["Vendeur / Vendeuse en boulangerie-pâtisserie"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "20-49",
  },
  {
    naf: "1071C",
    name: "HERVE COELHO",
    rome: "D1102",
    siret: "40182760500015",
    address: {
      city: "CROUY",
      postcode: "02880",
      departmentCode: "02",
      streetNumberAndAddress: "18 RUE DU DEPARTEMENT DE L AIN",
    },
    website: "",
    nafLabel: "Fabrication de pain et de pâtisserie fraîche",
    position: { lat: 49.402791, lon: 3.360101 },
    romeLabel: "Boulangerie - viennoiserie",
    distance_m: 97056.17596896,
    contactMode: "EMAIL",
    appellationLabels: ["Boulanger / Boulangère"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "3-5",
  },
  {
    naf: "7211Z",
    name: "NOVOSTER",
    rome: "J1301",
    siret: "47872201000012",
    address: {
      city: "MAGNY-LES-HAMEAUX",
      postcode: "78114",
      departmentCode: "78",
      streetNumberAndAddress: "1 RUE GUYNEMER",
    },
    website: "",
    nafLabel: "Recherche-développement en biotechnologie",
    position: { lat: 48.756195, lon: 2.070264 },
    romeLabel: "Personnel polyvalent des services hospitaliers",
    distance_m: 21610.88248646,
    contactMode: "EMAIL",
    appellationLabels: [
      "Agent / Agente de stérilisation de service hospitalier",
    ],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "6-9",
  },
  {
    naf: "8810A",
    name: "ADJACENT SERVICES",
    rome: "K1302",
    siret: "79132841200014",
    address: {
      city: "PARIS 18",
      postcode: "75018",
      departmentCode: "75",
      streetNumberAndAddress: "82 RUE DAMREMONT",
    },
    website: "",
    nafLabel:
      "Action sociale sans hébergement pour personnes âgées et pour personnes handicapées",
    position: { lat: 48.892262, lon: 2.335515 },
    romeLabel: "Assistance auprès d'adultes",
    distance_m: 3880.93478605,
    contactMode: "EMAIL",
    customizedName: "ADJACENT Services",
    appellationLabels: ["Assistant / Assistante de vie"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "20-49",
  },
  {
    naf: "1085Z",
    name: "ESPACE SAVEUR",
    rome: "G1602",
    siret: "35152352700023",
    address: {
      city: "RAMBOUILLET",
      postcode: "78120",
      departmentCode: "78",
      streetNumberAndAddress: "1 RUE HYPPOLITE MEGE MOURIES",
    },
    website: "",
    nafLabel: "Fabrication de plats préparés",
    position: { lat: 48.622473, lon: 1.828938 },
    romeLabel: "Personnel de cuisine",
    distance_m: 44675.64059479,
    contactMode: "EMAIL",
    appellationLabels: ["Cuisinier / Cuisinière"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "10-19",
  },
  {
    naf: "4722Z",
    name: "SOUAAD EL HACHIMI",
    rome: "D1101",
    siret: "44209431400014",
    address: {
      city: "HOUILLES",
      postcode: "78800",
      departmentCode: "78",
      streetNumberAndAddress: "38 RUE HOCHE",
    },
    website: "",
    nafLabel:
      "Commerce de détail de viandes et de produits à base de viande en magasin spécialisé",
    position: { lat: 48.924786, lon: 2.182007 },
    romeLabel: "Boucherie",
    distance_m: 12496.23544433,
    contactMode: "EMAIL",
    appellationLabels: ["Aide-boucher / Aide-bouchère", "Boucher / Bouchère"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "6-9",
  },
  {
    naf: "4776Z",
    name: "LA MANUFACTURE DU VEGETAL",
    rome: "D1209",
    siret: "88815638700019",
    address: {
      city: "SARTROUVILLE",
      postcode: "78500",
      departmentCode: "78",
      streetNumberAndAddress: "2 AV JEAN JAURES",
    },
    website: "",
    nafLabel:
      "Commerce de détail de fleurs, plantes, graines, engrais, animaux de compagnie et aliments pour ces animaux en magasin spécialisé",
    position: { lat: 48.94221, lon: 2.162815 },
    romeLabel: "Vente de végétaux",
    distance_m: 14789.68206131,
    contactMode: "EMAIL",
    customizedName: "Monceau Fleurs",
    appellationLabels: ["Fleuriste"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "",
  },
  {
    naf: "4391A",
    name: "ARNAUD AGUER",
    rome: "F1610",
    siret: "85170138300016",
    address: {
      city: "SAINT-REMY-LA-VANNE",
      postcode: "77320",
      departmentCode: "77",
      streetNumberAndAddress: "7 LAUNOY BEAUFORT",
    },
    website: "",
    nafLabel: "Travaux de couverture",
    position: { lat: 48.829823, lon: 3.253815 },
    romeLabel: "Pose et restauration de couvertures",
    distance_m: 68614.3850985,
    contactMode: "EMAIL",
    appellationLabels: ["Couvreur / Couvreuse"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "",
  },
  {
    naf: "4322B",
    name: "INSTALLATION & MAINTENANCE DES FLUIDES ENERGETIQUES",
    rome: "I1308",
    siret: "84086440900015",
    address: {
      city: "Paris 8e Arrondissement",
      postcode: "75008",
      departmentCode: "75",
      streetNumberAndAddress: "66 Avenue des Champs-Élysées",
    },
    website: "https://imfe.fr/",
    nafLabel:
      "Travaux de plomberie et installation de chauffage et de conditionnement d'air",
    position: { lat: 48.870848, lon: 2.305361 },
    romeLabel: "Maintenance d'installation de chauffage",
    distance_m: 1711.23281937,
    contactMode: "EMAIL",
    customizedName: "IMFE",
    appellationLabels: [
      "Dépanneur / Dépanneuse en régulation d'installations de chauffage et de conditionnement d'air",
    ],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: true,
    numberOfEmployeeRange: "1-2",
  },
  {
    naf: "7911Z",
    name: "DAMMARIE EVASION",
    rome: "G1102",
    siret: "39281163400014",
    address: {
      city: "DAMMARIE-LES-LYS",
      postcode: "77190",
      departmentCode: "77",
      streetNumberAndAddress: "544 AV ANDRE AMPERE",
    },
    website: "",
    nafLabel: "Activités des agences de voyage",
    position: { lat: 48.507686, lon: 2.607842 },
    romeLabel: "Promotion du tourisme local",
    distance_m: 44434.28826192,
    contactMode: "EMAIL",
    appellationLabels: ["Agent / Agente de promotion touristique"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "3-5",
  },
  {
    naf: "4120B",
    name: "ENTREPRISE BONNEVIE ET FILS",
    rome: "F1703",
    siret: "77574228100014",
    address: {
      city: "ARNOUVILLE",
      postcode: "95400",
      departmentCode: "95",
      streetNumberAndAddress: "15 AV PIERRE CURIE",
    },
    website: "",
    nafLabel: "Construction de bâtiments résidentiels et non résidentiels",
    position: { lat: 48.985814, lon: 2.421081 },
    romeLabel: "Maçonnerie",
    distance_m: 15939.40225862,
    contactMode: "EMAIL",
    appellationLabels: ["Maçon / Maçonne"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "20-49",
  },
  {
    naf: "9499Z",
    name: "GENERATIONS SOLIDAIRES VAL D'OISE 95",
    rome: "K1801",
    siret: "53936671600022",
    address: {
      city: "Vauréal",
      postcode: "95490",
      departmentCode: "95",
      streetNumberAndAddress: "Place du Cœur Battant",
    },
    website: "www.gsvo95.fr ",
    nafLabel: "Activités des organisations associatives n.c.a.",
    position: { lat: 49.03039, lon: 2.02097166909548 },
    romeLabel: "Conseil en emploi et insertion socioprofessionnelle",
    distance_m: 29046.39434056,
    contactMode: "EMAIL",
    customizedName: "GSVO 95",
    appellationLabels: [
      "Conseiller / Conseillère en insertion professionnelle",
    ],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "1-2",
  },
  {
    naf: "8810A",
    name: "SERVICES DES TROIS FORETS",
    rome: "K1304",
    siret: "45093071400057",
    address: {
      city: "ECOUEN",
      postcode: "95440",
      departmentCode: "95",
      streetNumberAndAddress: "16 RUE DE LA LIBERATION",
    },
    website: "https://services-a-la-personne.3forets.fr/",
    nafLabel:
      "Action sociale sans hébergement pour personnes âgées et pour personnes handicapées",
    position: { lat: 49.022412, lon: 2.374427 },
    romeLabel: "Services domestiques",
    distance_m: 18616.41278558,
    contactMode: "EMAIL",
    customizedName: "3FORETS",
    appellationLabels: [
      "Aide à domicile",
      "Aide ménager / ménagère à domicile",
    ],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "20-49",
  },
  {
    naf: "6201Z",
    name: "ARCYNERJ",
    rome: "D1403",
    siret: "80061113900018",
    address: {
      city: "MEUDON",
      postcode: "92360",
      departmentCode: "92",
      streetNumberAndAddress: "17 RUE JEANNE BRACONNIER",
    },
    website: "",
    nafLabel: "Programmation informatique",
    position: { lat: 48.790068, lon: 2.212193 },
    romeLabel: "Relation commerciale auprès de particuliers",
    distance_m: 11013.01456561,
    contactMode: "EMAIL",
    appellationLabels: [
      "Conseiller commercial / Conseillère commerciale en distribution d'énergie auprès des particuliers",
    ],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "3-5",
  },
  {
    naf: "9609Z",
    name: "VERONIQUE MAIGNIAL",
    rome: "A1501",
    siret: "90500483400016",
    address: {
      city: "Paris",
      postcode: "75015",
      departmentCode: "75",
      streetNumberAndAddress: "192 Rue Saint-Charles",
    },
    website: "",
    nafLabel: "Autres services personnels n.c.a.",
    position: { lat: 48.83984, lon: 2.279444 },
    romeLabel: "Aide aux soins animaux",
    distance_m: 3655.81731867,
    contactMode: "EMAIL",
    appellationLabels: ["Garde d'animaux de compagnie - Pet sitter"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "",
  },
  {
    naf: "7010Z",
    name: "LEADER GROUP",
    rome: "M1502",
    siret: "50953637100016",
    address: {
      city: "EAUBONNE",
      postcode: "95600",
      departmentCode: "95",
      streetNumberAndAddress: "19 RUE DES ALOUETTES",
    },
    website: "",
    nafLabel: "Activités des sièges sociaux",
    position: { lat: 48.979917, lon: 2.280121 },
    romeLabel: "Développement des ressources humaines",
    distance_m: 13773.49948329,
    contactMode: "EMAIL",
    appellationLabels: ["Chargé / Chargée de recrutement"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "20-49",
  },
  {
    naf: "4722Z",
    name: "CG ALLONNE",
    rome: "D1101",
    siret: "53152254800027",
    address: {
      city: "ALLONNE",
      postcode: "60000",
      departmentCode: "60",
      streetNumberAndAddress: "15 RUE PAUL GREBER",
    },
    website: "",
    nafLabel:
      "Commerce de détail de viandes et de produits à base de viande en magasin spécialisé",
    position: { lat: 49.408416, lon: 2.121106 },
    romeLabel: "Boucherie",
    distance_m: 62814.60542584,
    contactMode: "EMAIL",
    customizedName: "BOUCHERIE GRAND FRAIS",
    appellationLabels: ["Boucher / Bouchère"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "10-19",
  },
  {
    naf: "8690A",
    name: "CAP SANTE-AMBULANCES",
    rome: "J1305",
    siret: "37808933800016",
    address: {
      city: "CLAMART",
      postcode: "92140",
      departmentCode: "92",
      streetNumberAndAddress: "7 RUE CONDORCET",
    },
    website: "",
    nafLabel: "Autres activités pour la santé humaine",
    position: { lat: 48.810105, lon: 2.268337 },
    romeLabel: "Conduite de véhicules sanitaires",
    distance_m: 6621.2080964,
    contactMode: "EMAIL",
    appellationLabels: [
      "Ambulancier / Ambulancière",
      "Ambulancier / Ambulancière urgentiste",
      "Auxiliaire ambulancier / ambulancière",
    ],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "20-49",
  },
  {
    naf: "1039B",
    name: "LES DELICES DE L OGRESSE",
    rome: "H3303",
    siret: "83825718600018",
    address: {
      city: "LA COURNEUVE",
      postcode: "93120",
      departmentCode: "93",
      streetNumberAndAddress: "14 IMP SAINT LUCIEN",
    },
    website: "",
    nafLabel: "Autre transformation et conservation de fruits et légumes",
    position: { lat: 48.931812, lon: 2.387912 },
    romeLabel:
      "Préparation de matières et produits industriels (broyage, mélange, ...)",
    distance_m: 9514.80173056,
    contactMode: "EMAIL",
    appellationLabels: [
      "Préparateur / Préparatrice de mélange en industrie alimentaire",
    ],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "1-2",
  },
  {
    naf: "5510Z",
    name: "MINHAL FRANCE SA",
    rome: "G1703",
    siret: "99999028600018",
    address: {
      city: "PARIS 9",
      postcode: "75009",
      departmentCode: "75",
      streetNumberAndAddress: "1 RUE SCRIBE",
    },
    website: "",
    nafLabel: "Hôtels et hébergement similaire",
    position: { lat: 48.870618, lon: 2.329855 },
    romeLabel: "Réception en hôtellerie",
    distance_m: 1489.83636859,
    contactMode: "EMAIL",
    customizedName: "hôtel Scribe",
    appellationLabels: ["Réceptionniste en établissement touristique"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "100-199",
  },
  {
    naf: "5621Z",
    name: "NENE SALUMU TSHITOKO",
    rome: "G1602",
    siret: "84181038500010",
    address: {
      city: "CERGY",
      postcode: "95000",
      departmentCode: "95",
      streetNumberAndAddress: "2 RUE DES LINANDES BEIGES",
    },
    website: "",
    nafLabel: "Services des traiteurs",
    position: { lat: 49.043641, lon: 2.069547 },
    romeLabel: "Personnel de cuisine",
    distance_m: 27545.2789428,
    contactMode: "EMAIL",
    appellationLabels: ["Cuisinier / Cuisinière à domicile"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "",
  },
  {
    naf: "4321A",
    name: "F.T.C.",
    rome: "F1602",
    siret: "81255023400015",
    address: {
      city: "BLANDY",
      postcode: "91150",
      departmentCode: "91",
      streetNumberAndAddress: "2 PL SAINT MAURICE",
    },
    website: "",
    nafLabel: "Installation électrique",
    position: { lat: 48.313476, lon: 2.25554 },
    romeLabel: "Électricité bâtiment",
    distance_m: 60837.35078256,
    contactMode: "EMAIL",
    appellationLabels: ["Électricien / Électricienne de chantier"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "3-5",
  },
  {
    naf: "8710A",
    name: "ASS CHRETIEN INSTITUT SOCIAL SANTE FRAN",
    rome: "J1502",
    siret: "40072026400219",
    address: {
      city: "CHEROY",
      postcode: "89690",
      departmentCode: "89",
      streetNumberAndAddress: "1 RUE DE LA GRANDE MAISON",
    },
    website: "",
    nafLabel: "Hébergement médicalisé",
    position: { lat: 48.20291, lon: 2.996864 },
    romeLabel: "Coordination de services médicaux ou paramédicaux",
    distance_m: 88428.87662176,
    contactMode: "EMAIL",
    customizedName: "EHPAD ABBE CHARRON",
    appellationLabels: ["Infirmier général / Infirmière générale"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "1000-1999",
  },
  {
    naf: "8899B",
    name: "ASS POUR EDUCATION ET READAPTATION",
    rome: "K1203",
    siret: "78084899000013",
    address: {
      city: "TILLY",
      postcode: "27510",
      departmentCode: "27",
      streetNumberAndAddress: "LD CASTEL DES BRUYERES",
    },
    website: "",
    nafLabel: "Autre action sociale sans hébergement n.c.a.",
    position: { lat: 49.130423, lon: 1.51229 },
    romeLabel: "Encadrement technique en insertion professionnelle",
    distance_m: 66376.8762779,
    contactMode: "EMAIL",
    customizedName: "Association APEER",
    appellationLabels: [
      "Moniteur / Monitrice d'atelier en établissement spécialisé",
    ],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "200-249",
  },
  {
    naf: "4724Z",
    name: "MATTHIEU & PAULINE",
    rome: "N1103",
    siret: "81316428200044",
    address: {
      city: "BEZONS",
      postcode: "95870",
      departmentCode: "95",
      streetNumberAndAddress: "7 RUE CHARLES FRANCOIS DAUBIGNY",
    },
    website: "",
    nafLabel:
      "Commerce de détail de pain, pâtisserie et confiserie en magasin spécialisé",
    position: { lat: 48.913722, lon: 2.202103 },
    romeLabel: "Magasinage et préparation de commandes",
    distance_m: 10582.64842471,
    contactMode: "EMAIL",
    appellationLabels: ["Préparateur / Préparatrice de commandes"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "10-19",
  },
  {
    naf: "8810A",
    name: "LOCALE ADMR DE BRAY SEINE",
    rome: "K1304",
    siret: "42098110200031",
    address: {
      city: "BRAY-SUR-SEINE",
      postcode: "77480",
      departmentCode: "77",
      streetNumberAndAddress: "23 GRANDE RUE",
    },
    website: "",
    nafLabel:
      "Action sociale sans hébergement pour personnes âgées et pour personnes handicapées",
    position: { lat: 48.415649, lon: 3.238126 },
    romeLabel: "Services domestiques",
    distance_m: 83712.47192936,
    contactMode: "EMAIL",
    appellationLabels: ["Aide à domicile"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "20-49",
  },
  {
    naf: "8899B",
    name: "ASS POUR EDUCATION ET READAPTATION",
    rome: "K1301",
    siret: "78084899000013",
    address: {
      city: "TILLY",
      postcode: "27510",
      departmentCode: "27",
      streetNumberAndAddress: "LD CASTEL DES BRUYERES",
    },
    website: "",
    nafLabel: "Autre action sociale sans hébergement n.c.a.",
    position: { lat: 49.130423, lon: 1.51229 },
    romeLabel: "Accompagnement médicosocial",
    distance_m: 66376.8762779,
    contactMode: "EMAIL",
    customizedName: "Association APEER",
    appellationLabels: [
      "Accompagnant éducatif et social / Accompagnante éducative et sociale en structure collective",
    ],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "200-249",
  },
  {
    naf: "8790B",
    name: "COALLIA",
    rome: "I1203",
    siret: "77568030900603",
    address: {
      city: "BREUILLET",
      postcode: "91650",
      departmentCode: "91",
      streetNumberAndAddress: "4 RUE DE LA TOURNEE",
    },
    website: "",
    nafLabel: "Autres activités d'hébergement social",
    position: { lat: 48.567104, lon: 2.170952 },
    romeLabel: "Maintenance des bâtiments et des locaux",
    distance_m: 34252.52251499,
    contactMode: "EMAIL",
    appellationLabels: [
      "Agent d'entretien maintenance polyvalent / Agente d'entretien maintenance polyvalente en collectivité",
    ],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "2000-4999",
  },
  {
    naf: "5610A",
    name: "LE CYGNE DE LA CROIX",
    rome: "G1802",
    siret: "34746257400018",
    address: {
      city: "NOGENT-SUR-SEINE",
      postcode: "10400",
      departmentCode: "10",
      streetNumberAndAddress: "22 RUE DES PONTS",
    },
    website: "",
    nafLabel: "Restaurants et services de restauration mobile",
    position: { lat: 48.493751, lon: 3.49959 },
    romeLabel: "Management du service en restauration",
    distance_m: 95887.75722805,
    contactMode: "EMAIL",
    appellationLabels: [
      "Maître d'hôtel sommelier / Maîtresse d'hôtel sommelière",
      "Maître / Maîtresse d'hôtel",
    ],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "10-19",
  },
  {
    naf: "8899B",
    name: "FONDATION PERCE NEIGE",
    rome: "J1501",
    siret: "78504100500212",
    address: {
      city: "MANDRES-LES-ROSES",
      postcode: "94520",
      departmentCode: "94",
      streetNumberAndAddress: "10 RUE LINO VENTURA",
    },
    website: "",
    nafLabel: "Autre action sociale sans hébergement n.c.a.",
    position: { lat: 48.700489, lon: 2.550441 },
    romeLabel: "Soins d'hygiène, de confort du patient",
    distance_m: 24433.96192998,
    contactMode: "EMAIL",
    customizedName: "Maison Perce-Neige de Mandres les Roses ",
    appellationLabels: ["Aide-soignant / Aide-soignante"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "1000-1999",
  },
  {
    naf: "4773Z",
    name: "GABRIELLE DANAN",
    rome: "J1307",
    siret: "35174138400025",
    address: {
      city: "BONNEUIL-SUR-MARNE",
      postcode: "94380",
      departmentCode: "94",
      streetNumberAndAddress: "8 PL DES LIBERTES",
    },
    website: "",
    nafLabel:
      "Commerce de détail de produits pharmaceutiques en magasin spécialisé",
    position: { lat: 48.765047, lon: 2.486249 },
    romeLabel: "Préparation en pharmacie",
    distance_m: 16060.25353084,
    contactMode: "EMAIL",
    customizedName: "PHARMACIE MESSIDOR",
    appellationLabels: ["Préparateur / Préparatrice en pharmacie d'officine"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "3-5",
  },
  {
    naf: "4399A",
    name: "DALSA",
    rome: "F1201",
    siret: "41292358300030",
    address: {
      city: "WISSOUS",
      postcode: "91320",
      departmentCode: "91",
      streetNumberAndAddress: "29 RUE GEORGES COLLIN",
    },
    website: "",
    nafLabel: "Autres travaux de construction spécialisés n.c.a.",
    position: { lat: 48.72724, lon: 2.322041 },
    romeLabel: "Conduite de travaux du BTP et de travaux paysagers",
    distance_m: 14640.97213383,
    contactMode: "EMAIL",
    appellationLabels: ["Conducteur / Conductrice de travaux"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "6-9",
  },
  {
    naf: "4520A",
    name: "VAL' AUTO SERVICES",
    rome: "H2909",
    siret: "53295162100020",
    address: {
      city: "MAISONS-ALFORT",
      postcode: "94700",
      departmentCode: "94",
      streetNumberAndAddress: "225 AV DU GENERAL LECLERC",
    },
    website: "",
    nafLabel: "Entretien et réparation de véhicules automobiles",
    position: { lat: 48.805299, lon: 2.442173 },
    romeLabel: "Montage-assemblage mécanique",
    distance_m: 10766.57520776,
    contactMode: "EMAIL",
    customizedName: "SARL",
    appellationLabels: [
      "Monteur / Monteuse en ligne de fabrication automobile",
    ],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "6-9",
  },
  {
    naf: "4329A",
    name: "ASR AIDE SOLUTION RENOVATION",
    rome: "D1212",
    siret: "49409768600013",
    address: {
      city: "VILLENOY",
      postcode: "77124",
      departmentCode: "77",
      streetNumberAndAddress: "13 RUE THIERS",
    },
    website: "",
    nafLabel: "Autres travaux d'installation",
    position: { lat: 48.942589, lon: 2.864357 },
    romeLabel: "Vente en décoration et équipement du foyer",
    distance_m: 40978.74793987,
    contactMode: "PHONE",
    appellationLabels: [
      "Vendeur / Vendeuse en chauffage-ventilation-isolation",
    ],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "10-19",
  },
  {
    naf: "8130Z",
    name: "JARDIN NATURE MICHEL FOUGNIE",
    rome: "A1203",
    siret: "44265759900027",
    address: {
      city: "VILLE-SAINT-JACQUES",
      postcode: "77130",
      departmentCode: "77",
      streetNumberAndAddress: "2 RUE GRANDE",
    },
    website: "",
    nafLabel: "Services d'aménagement paysager",
    position: { lat: 48.346571, lon: 2.905953 },
    romeLabel: "Aménagement et entretien des espaces verts",
    distance_m: 71504.63337393,
    contactMode: "EMAIL",
    appellationLabels: ["Jardinier / Jardinière paysagiste"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "3-5",
  },
  {
    naf: "8121Z",
    name: "CLEAN INDUSTRIES SERVICES",
    rome: "K2204",
    siret: "39104246200047",
    address: {
      city: "VARENNES-SUR-SEINE",
      postcode: "77130",
      departmentCode: "77",
      streetNumberAndAddress: "8 RUE ALBERT GRAVE",
    },
    website: "",
    nafLabel: "Nettoyage courant des bâtiments",
    position: { lat: 48.375557, lon: 2.931093 },
    romeLabel: "Nettoyage de locaux",
    distance_m: 70132.48602358,
    contactMode: "EMAIL",
    appellationLabels: ["Agent / Agente de nettoyage industriel"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "10-19",
  },
  {
    naf: "5510Z",
    name: "PRADO HOTEL OU HOTEL DU PRADO",
    rome: "K2204",
    siret: "56203299500010",
    address: {
      city: "PARIS 10",
      postcode: "75010",
      departmentCode: "75",
      streetNumberAndAddress: "12 RUE DU FBG SAINT DENIS",
    },
    website: "",
    nafLabel: "Hôtels et hébergement similaire",
    position: { lat: 48.870272, lon: 2.353053 },
    romeLabel: "Nettoyage de locaux",
    distance_m: 2732.95032976,
    contactMode: "EMAIL",
    appellationLabels: ["Agent / Agente de nettoyage industriel"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "6-9",
  },
  {
    naf: "4772A",
    name: "BESSON CHAUSSURES",
    rome: "D1211",
    siret: "30431845401059",
    address: {
      city: "LUISANT",
      postcode: "28600",
      departmentCode: "28",
      streetNumberAndAddress: "RUE JEAN PERRIN",
    },
    website: "",
    nafLabel:
      "Commerce de détail de chaussures et d'articles en cuir en magasin spécialisé",
    position: { lat: 48.417145, lon: 1.454095 },
    romeLabel: "Vente en articles de sport et loisirs",
    distance_m: 80535.86651328,
    contactMode: "IN_PERSON",
    appellationLabels: ["Vendeur / Vendeuse en équipement de sport"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "50-99",
  },
  {
    naf: "4646Z",
    name: "NOVO NORDISK",
    rome: "M1207",
    siret: "45135699200037",
    address: {
      city: "PUTEAUX",
      postcode: "92800",
      departmentCode: "92",
      streetNumberAndAddress: "12 CRS MICHELET",
    },
    website: "",
    nafLabel: "Commerce de gros de produits pharmaceutiques",
    position: { lat: 48.887909, lon: 2.246855 },
    romeLabel: "Trésorerie et financement",
    distance_m: 6263.91153583,
    contactMode: "EMAIL",
    appellationLabels: ["Trésorier adjoint / Trésorière adjointe"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "250-499",
  },
  {
    naf: "4322A",
    name: "MATHIEU THEILLAUD PLOMBERIE CHAUFFAGE",
    rome: "F1603",
    siret: "50869118500021",
    address: {
      city: "SAINT OUEN L'AUMONE",
      postcode: "95310",
      departmentCode: "95",
      streetNumberAndAddress: "82 AV DU CHATEAU",
    },
    website: "",
    nafLabel:
      "Travaux de plomberie et installation de chauffage et de conditionnement d'air",
    position: { lat: 49.055309, lon: 2.13697 },
    romeLabel: "Installation d'équipements sanitaires et thermiques",
    distance_m: 25629.83937814,
    contactMode: "EMAIL",
    appellationLabels: ["Plombier / Plombière chauffagiste"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "1-2",
  },
  {
    naf: "5221Z",
    name: "INDIGO PARK",
    rome: "K2303",
    siret: "32022964405241",
    address: {
      city: "PUTEAUX",
      postcode: "92800",
      departmentCode: "92",
      streetNumberAndAddress: "1 PL DES DEGRES",
    },
    website: "",
    nafLabel: "Services auxiliaires des transports terrestres",
    position: { lat: 48.889807, lon: 2.236448 },
    romeLabel: "Nettoyage des espaces urbains",
    distance_m: 7030.07611947,
    contactMode: "EMAIL",
    appellationLabels: ["Ouvrier / Ouvrière d'entretien propreté"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "1000-1999",
  },
  {
    naf: "9602A",
    name: "FOR MEN",
    rome: "D1202",
    siret: "52475310000030",
    address: {
      city: "CHESSY",
      postcode: "77700",
      departmentCode: "77",
      streetNumberAndAddress: "4 RUE D'ARIANE",
    },
    website: "",
    nafLabel: "Coiffure et soins de beauté",
    position: { lat: 48.8565, lon: 2.772147 },
    romeLabel: "Coiffure",
    distance_m: 33176.63847074,
    contactMode: "EMAIL",
    appellationLabels: ["Coiffeur barbier / Coiffeuse barbière"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "3-5",
  },
  {
    naf: "5610C",
    name: "SO FOOD TOIT",
    rome: "G1602",
    siret: "81303832000012",
    address: {
      city: "PARIS 17",
      postcode: "75017",
      departmentCode: "75",
      streetNumberAndAddress: "22 RUE BROCHANT",
    },
    website: "",
    nafLabel: "Restaurants et services de restauration mobile",
    position: { lat: 48.889238, lon: 2.318583 },
    romeLabel: "Personnel de cuisine",
    distance_m: 3376.61101614,
    contactMode: "EMAIL",
    appellationLabels: ["Cuisinier / Cuisinière"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "1-2",
  },
  {
    naf: "5510Z",
    name: "PRESIDENT WILSON INVEST",
    rome: "G1502",
    siret: "48023162000018",
    address: {
      city: "SAINT-DENIS",
      postcode: "93200",
      departmentCode: "93",
      streetNumberAndAddress: "67 AV DU PRESIDENT WILSON",
    },
    website: "",
    nafLabel: "Hôtels et hébergement similaire",
    position: { lat: 48.904311, lon: 2.35817 },
    romeLabel: "Personnel polyvalent d'hôtellerie",
    distance_m: 5773.68045152,
    contactMode: "EMAIL",
    appellationLabels: [
      "Employé polyvalent / Employée polyvalente d'hôtellerie",
    ],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "1-2",
  },
  {
    naf: "4677Z",
    name: "KAOUKAB",
    rome: "D1401",
    siret: "83291658900019",
    address: {
      city: "PARIS 9",
      postcode: "75009",
      departmentCode: "75",
      streetNumberAndAddress: "17 RUE GERANDO",
    },
    website: "",
    nafLabel: "Commerce de gros de déchets et débris",
    position: { lat: 48.882837, lon: 2.346209 },
    romeLabel: "Assistanat commercial",
    distance_m: 3282.9165328,
    contactMode: "EMAIL",
    appellationLabels: ["Commercial / Commerciale sédentaire"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "",
  },
  {
    naf: "5610C",
    name: "KITOKO COFFEE SAS",
    rome: "G1801",
    siret: "88031186500013",
    address: {
      city: "MOISSY-CRAMAYEL",
      postcode: "77550",
      departmentCode: "77",
      streetNumberAndAddress: "69 RUE DES LOUPS",
    },
    website: "",
    nafLabel: "Restaurants et services de restauration mobile",
    position: { lat: 48.633086, lon: 2.585709 },
    romeLabel: "Café, bar brasserie",
    distance_m: 31816.23540088,
    contactMode: "EMAIL",
    appellationLabels: ["Barista"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "",
  },
  {
    naf: "4511Z",
    name: "COME ET BARDON AUTOMOBILES",
    rome: "N1302",
    siret: "38042931600017",
    address: {
      city: "VIRY-CHATILLON",
      postcode: "91170",
      departmentCode: "91",
      streetNumberAndAddress: "119 AV DU GENERAL DE GAULLE",
    },
    website: "",
    nafLabel: "Commerce de voitures et de véhicules automobiles légers",
    position: { lat: 48.679967, lon: 2.380422 },
    romeLabel: "Direction de site logistique",
    distance_m: 20386.24603221,
    contactMode: "EMAIL",
    appellationLabels: ["Responsable de magasin de pièces de rechange"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "50-99",
  },
  {
    naf: "5821Z",
    name: "TEREBRIS GAMES",
    rome: "M1805",
    siret: "84829119100015",
    address: {
      city: "PALAISEAU",
      postcode: "91120",
      departmentCode: "91",
      streetNumberAndAddress: "17 RUE JULES VERNE",
    },
    website: "",
    nafLabel: "Édition de jeux électroniques",
    position: { lat: 48.714675, lon: 2.26106 },
    romeLabel: "Études et développement informatique",
    distance_m: 16612.82603437,
    contactMode: "EMAIL",
    customizedName: "17 Cours Blaise Pascal, Evry",
    appellationLabels: ["Développeur / Développeuse informatique"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "1-2",
  },
  {
    naf: "4722Z",
    name: "A L ATELIER DU BOUCHER",
    rome: "D1106",
    siret: "85108123200015",
    address: {
      city: "Villemomble",
      postcode: "93250",
      departmentCode: "93",
      streetNumberAndAddress: "10 Grande Rue",
    },
    website: "",
    nafLabel:
      "Commerce de détail de viandes et de produits à base de viande en magasin sp©cialisÃ©",
    position: { lat: 48.884252, lon: 2.508858 },
    romeLabel: "Vente en alimentation",
    distance_m: 14135.86473047,
    contactMode: "PHONE",
    appellationLabels: ["Vendeur / Vendeuse en boucherie"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "",
  },
  {
    naf: "1071C",
    name: "M D M",
    rome: "D1102",
    siret: "80344637600011",
    address: {
      city: "SAINT-OUEN-SUR-SEINE",
      postcode: "93400",
      departmentCode: "93",
      streetNumberAndAddress: "23 RUE DES ROSIERS",
    },
    website: "",
    nafLabel: "Fabrication de pain et de pÃ¢tisserie fraÃ®che",
    position: { lat: 48.90674, lon: 2.335218 },
    romeLabel: "Boulangerie - viennoiserie",
    distance_m: 5436.47093093,
    contactMode: "PHONE",
    customizedName: "sas",
    appellationLabels: ["Boulanger-pÃ¢tissier / BoulangÃ¨re-pÃ¢tissiÃ¨re"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "1-2",
  },
  {
    naf: "9602A",
    name: "MARIE SANON",
    rome: "D1202",
    siret: "53291382900026",
    address: {
      city: "Chelles",
      postcode: "77500",
      departmentCode: "77",
      streetNumberAndAddress: "47 Rue Gambetta",
    },
    website: "",
    nafLabel: "Coiffure et soins de beautÃ©",
    position: { lat: 48.8799864, lon: 2.59367745959596 },
    romeLabel: "Coiffure",
    distance_m: 20211.43831965,
    contactMode: "PHONE",
    appellationLabels: ["Coiffeur / Coiffeuse"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    numberOfEmployeeRange: "3-5",
  },
  {
    naf: "7500Z",
    name: "SEL VETERINAIRE SOPHIE DUVIVIER",
    rome: "A1501",
    siret: "84226372500017",
    address: {
      city: "Draveil",
      postcode: "91210",
      departmentCode: "91",
      streetNumberAndAddress: "22 Rue de Mainville",
    },
    website: "https://www.veterinaire-draveil-91.com/",
    nafLabel: "ActivitÃ©s vÃ©tÃ©rinaires",
    position: { lat: 48.6860722, lon: 2.4128737 },
    romeLabel: "Aide aux soins animaux",
    distance_m: 20393.72809783,
    contactMode: "EMAIL",
    customizedName: "Clinique VÃ©tÃ©rinaire du Centre",
    appellationLabels: [
      "Aide-vÃ©tÃ©rinaire",
      "Auxiliaire de vÃ©tÃ©rinaire",
      "Auxiliaire SpÃ©cialisÃ© / SpÃ©cialisÃ©e VÃ©tÃ©rinaire -ASV-",
      "Auxiliaire VÃ©tÃ©rinaire QualifiÃ© / QualifiÃ©e -AVQ-",
    ],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "1-2",
  },
  {
    naf: "8121Z",
    name: "SERVICES GAGNANTS",
    rome: "K1302",
    siret: "50741359900030",
    address: {
      city: "ORSAY",
      postcode: "91400",
      departmentCode: "91",
      streetNumberAndAddress: "24 RUE ARCHANGE",
    },
    website: "",
    nafLabel: "Nettoyage courant des bÃ¢timents",
    position: { lat: 48.697111, lon: 2.18526 },
    romeLabel: "Assistance auprÃ¨s d'adultes",
    distance_m: 20537.54979221,
    contactMode: "EMAIL",
    customizedName: "APEF ORSAY",
    appellationLabels: ["Assistant / Assistante de vie"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "50-99",
  },
  {
    naf: "4334Z",
    name: "GREG BAT",
    rome: "F1606",
    siret: "51396628300022",
    address: {
      city: "CHELLES",
      postcode: "77500",
      departmentCode: "77",
      streetNumberAndAddress: "108 AV DU MARECHAL FOCH",
    },
    website: "",
    nafLabel: "Travaux de peinture et vitrerie",
    position: { lat: 48.866851, lon: 2.570643 },
    romeLabel: "Peinture en bÃ¢timent",
    distance_m: 18408.65096618,
    contactMode: "EMAIL",
    appellationLabels: ["Peintre en bÃ¢timent"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "1-2",
  },
  {
    naf: "4331Z",
    name: "ILII GHEORGHIU",
    rome: "F1604",
    siret: "91459995600010",
    address: {
      city: "MEAUX",
      postcode: "77100",
      departmentCode: "77",
      streetNumberAndAddress: "5 CHE DE BOULEURS",
    },
    website: "",
    nafLabel: "Travaux de plÃ¢trerie",
    position: { lat: 48.963501, lon: 2.899872 },
    romeLabel: "Montage d'agencements",
    distance_m: 44065.97992219,
    contactMode: "EMAIL",
    appellationLabels: ["Plaquiste enduiseur / enduiseuse"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "",
  },
  {
    naf: "5610A",
    name: "AR2S",
    rome: "G1602",
    siret: "80493235800018",
    address: {
      city: "CHARTRES",
      postcode: "28000",
      departmentCode: "28",
      streetNumberAndAddress: "24 RUE NOEL BALLAY",
    },
    website: "",
    nafLabel: "Restaurants et services de restauration mobile",
    position: { lat: 48.445284, lon: 1.485757 },
    romeLabel: "Personnel de cuisine",
    distance_m: 76771.84612562,
    contactMode: "IN_PERSON",
    appellationLabels: ["Cuisinier / CuisiniÃ¨re"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "1-2",
  },
  {
    naf: "5621Z",
    name: "LA TABLE DE CANA",
    rome: "G1601",
    siret: "34358659000030",
    address: {
      city: "ANTONY",
      postcode: "92160",
      departmentCode: "92",
      streetNumberAndAddress: "5 AV MAURICE RAVEL",
    },
    website: "",
    nafLabel: "Services des traiteurs",
    position: { lat: 48.738015, lon: 2.311686 },
    romeLabel: "Management du personnel de cuisine",
    distance_m: 13456.00870633,
    contactMode: "EMAIL",
    appellationLabels: ["Chef cuisinier / cuisiniÃ¨re"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "50-99",
  },
  {
    naf: "9602B",
    name: "ANAIS BOURGOIS",
    rome: "D1208",
    siret: "75023968300014",
    address: {
      city: "CHARLY-SUR-MARNE",
      postcode: "02310",
      departmentCode: "02",
      streetNumberAndAddress: "84 RUE EMILE MORLOT",
    },
    website: "",
    nafLabel: "Coiffure et soins de beautÃ©",
    position: { lat: 48.976808, lon: 3.285038 },
    romeLabel: "Soins esthÃ©tiques et corporels",
    distance_m: 71931.5720474,
    contactMode: "PHONE",
    appellationLabels: ["EsthÃ©ticien / EsthÃ©ticienne"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "1-2",
  },
  {
    naf: "4322B",
    name: "ITS-SERVICES",
    rome: "F1603",
    siret: "80316271800016",
    address: {
      city: "LA BONNEVILLE-SUR-ITON",
      postcode: "27190",
      departmentCode: "27",
      streetNumberAndAddress: "21 RUE JEAN MARECHAL",
    },
    website: "",
    nafLabel:
      "Travaux de plomberie et installation de chauffage et de conditionnement d'air",
    position: { lat: 48.990676, lon: 1.037611 },
    romeLabel: "Installation d'Ã©quipements sanitaires et thermiques",
    distance_m: 95113.53679184,
    contactMode: "IN_PERSON",
    appellationLabels: ["Chauffagiste"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "3-5",
  },
  {
    naf: "4322A",
    name: "AREVANE",
    rome: "F1604",
    siret: "52384168200025",
    address: {
      city: "Nogent-sur-Oise",
      postcode: "60180",
      departmentCode: "60",
      streetNumberAndAddress: "35 Rue Voltaire",
    },
    website: "",
    nafLabel:
      "Travaux de plomberie et installation de chauffage et de conditionnement d'air",
    position: { lat: 49.27332, lon: 2.470298 },
    romeLabel: "Montage d'agencements",
    distance_m: 47379.02926555,
    contactMode: "EMAIL",
    customizedName: "enerjeco",
    appellationLabels: ["Plaquiste"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "1-2",
  },
  {
    naf: "8810A",
    name: "SERVICES ET CO",
    rome: "K1302",
    siret: "50291066400049",
    address: {
      city: "MILLY-LA-FORET",
      postcode: "91490",
      departmentCode: "91",
      streetNumberAndAddress: "7 RUE CAMP ROMAIN",
    },
    website: "",
    nafLabel:
      "Action sociale sans hÃ©bergement pour personnes Ã¢gÃ©es et pour personnes handicapÃ©es",
    position: { lat: 48.397856, lon: 2.424511 },
    romeLabel: "Assistance auprÃ¨s d'adultes",
    distance_m: 51843.29685732,
    contactMode: "EMAIL",
    customizedName: "TOUT A DOM SERVICES MILLY LA FORET",
    appellationLabels: ["Auxiliaire de vie"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "20-49",
  },
  {
    naf: "4711D",
    name: "SA PRIMA",
    rome: "D1401",
    siret: "67365004000011",
    address: {
      city: "EVREUX",
      postcode: "27000",
      departmentCode: "27",
      streetNumberAndAddress: "4 PL DE LA REPUBLIQUE",
    },
    website: "",
    nafLabel:
      "Commerce de dÃ©tail en magasin non spÃ©cialisÃ© Ã  prÃ©dominance alimentaire",
    position: { lat: 49.025885, lon: 1.157616 },
    romeLabel: "Assistanat commercial",
    distance_m: 87155.32110353,
    contactMode: "EMAIL",
    appellationLabels: [
      "EmployÃ© commercial / EmployÃ©e commerciale sÃ©dentaire",
    ],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "50-99",
  },
  {
    naf: "5610A",
    name: "GABIN",
    rome: "G1602",
    siret: "82812973400020",
    address: {
      city: "ASNIERES-SUR-SEINE",
      postcode: "92600",
      departmentCode: "92",
      streetNumberAndAddress: "29 RUE EUGENIE EBOUE",
    },
    website: "",
    nafLabel: "Restaurants et services de restauration mobile",
    position: { lat: 48.918976, lon: 2.318132 },
    romeLabel: "Personnel de cuisine",
    distance_m: 6683.48381228,
    contactMode: "EMAIL",
    appellationLabels: ["Commis / Commise de cuisine"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "6-9",
  },
  {
    naf: "8810A",
    name: "AD SENIORS 91 NORD",
    rome: "K1302",
    siret: "80957262100021",
    address: {
      city: "VIRY-CHATILLON",
      postcode: "91170",
      departmentCode: "91",
      streetNumberAndAddress: "80 AV DU GENERAL DE GAULLE",
    },
    website: "",
    nafLabel:
      "Action sociale sans hÃ©bergement pour personnes Ã¢gÃ©es et pour personnes handicapÃ©es",
    position: { lat: 48.676931, lon: 2.384467 },
    romeLabel: "Assistance auprÃ¨s d'adultes",
    distance_m: 20781.66207013,
    contactMode: "EMAIL",
    appellationLabels: [
      "Assistant / Assistante de vie auprÃ¨s de personnes Ã¢gÃ©es",
      "Assistant / Assistante de vie auprÃ¨s de personnes handicapÃ©es",
    ],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "10-19",
  },
  {
    naf: "5510Z",
    name: "HOTEL DE BELLEVUE",
    rome: "G1803",
    siret: "56205849500036",
    address: {
      city: "PARIS 18",
      postcode: "75018",
      departmentCode: "75",
      streetNumberAndAddress: "67 RUE PHILIPPE DE GIRARD",
    },
    website: "",
    nafLabel: "HÃ´tels et hÃ©bergement similaire",
    position: { lat: 48.886652, lon: 2.360934 },
    romeLabel: "Service en restauration",
    distance_m: 4304.7709682,
    contactMode: "EMAIL",
    appellationLabels: ["Serveur / Serveuse petit dÃ©jeuner"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "10-19",
  },
  {
    naf: "7022Z",
    name: "INFOCONSEIL",
    rome: "K1601",
    siret: "79208308100010",
    address: {
      city: "CROISSY-BEAUBOURG",
      postcode: "77183",
      departmentCode: "77",
      streetNumberAndAddress: "46 RUE DES VIEILLES VIGNES",
    },
    website: "",
    nafLabel: "Conseil pour les affaires et autres conseils de gestion",
    position: { lat: 48.814772, lon: 2.637392 },
    romeLabel: "Gestion de l'information et de la documentation",
    distance_m: 23807.96065929,
    contactMode: "EMAIL",
    customizedName: "INFOCONSEIL",
    appellationLabels: ["ChargÃ© / ChargÃ©e des ressources documentaires"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "3-5",
  },
  {
    naf: "8810A",
    name: "LE SERVICE A VOTRE PORTE",
    rome: "K1304",
    siret: "53431697100017",
    address: {
      city: "PONTAULT-COMBAULT",
      postcode: "77340",
      departmentCode: "77",
      streetNumberAndAddress: "30 AV DU GENERAL DE GAULLE",
    },
    website: "",
    nafLabel:
      "Action sociale sans hÃ©bergement pour personnes Ã¢gÃ©es et pour personnes handicapÃ©es",
    position: { lat: 48.803933, lon: 2.616058 },
    romeLabel: "Services domestiques",
    distance_m: 22576.12882262,
    contactMode: "EMAIL",
    customizedName: "TOUT A DOM SERVICES",
    appellationLabels: ["Aide mÃ©nager / mÃ©nagÃ¨re Ã  domicile"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "20-49",
  },
  {
    naf: "7022Z",
    name: "V@HA CONSULTING",
    rome: "D1401",
    siret: "48901006600012",
    address: {
      city: "ASNIERES-SUR-SEINE",
      postcode: "92600",
      departmentCode: "92",
      streetNumberAndAddress: "3 RUE DU ROCHER",
    },
    website: "",
    nafLabel: "Conseil pour les affaires et autres conseils de gestion",
    position: { lat: 48.909095, lon: 2.269501 },
    romeLabel: "Assistanat commercial",
    distance_m: 6701.54928899,
    contactMode: "EMAIL",
    appellationLabels: [
      "Collaborateur commercial / Collaboratrice commerciale",
    ],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "1-2",
  },
  {
    naf: "4939B",
    name: "DEBRAS VOYAGES",
    rome: "N4103",
    siret: "32951869000022",
    address: {
      city: "Montainville",
      postcode: "78124",
      departmentCode: "78",
      streetNumberAndAddress: "Les Closeaux",
    },
    website: "",
    nafLabel: "Autres transports terrestres de voyageurs n.c.a.",
    position: { lat: 48.875883, lon: 1.874207 },
    romeLabel: "Conduite de transport en commun sur route",
    distance_m: 32763.41707777,
    contactMode: "EMAIL",
    appellationLabels: ["Conducteur / Conductrice de car"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "10-19",
  },
  {
    naf: "5610C",
    name: "NADEGE GARNIER",
    rome: "G1602",
    siret: "42345431300028",
    address: {
      city: "PANTIN",
      postcode: "93500",
      departmentCode: "93",
      streetNumberAndAddress: "35 RUE JACQUART",
    },
    website: "",
    nafLabel: "Restaurants et services de restauration mobile",
    position: { lat: 48.89213, lon: 2.420006 },
    romeLabel: "Personnel de cuisine",
    distance_m: 8211.93107887,
    contactMode: "PHONE",
    appellationLabels: ["Commis / Commise de cuisine"],
    voluntaryToImmersion: true,
    additionalInformation: "",
    fitForDisabledWorkers: false,
    numberOfEmployeeRange: "",
  },
] as SearchImmersionResultDto[];
