export enum EstablishementCallToAction {
  MODIFY_ESTABLISHEMENT = "MODIFY_ESTABLISHEMENT",
  NOTHING = "NOTHING",
  REGISTER_ESTABLISHEMENT = "REGISTER_ESTABLISHEMENT",
  BAD_SIRET = "BAD_SIRET",
  MODIFY_ESTABLISHEMENT_REQUEST_NOTIFICATION = "MODIFY_ESTABLISHEMENT_REQUEST_NOTIFICATION",
  UNREGISTERED_SIRET = "UNREGISTERED_SIRET",
  MISSING_ESTABLISHMENT_ON_SIRENE = "MISSING_ESTABLISHMENT_ON_SIRENE",
  CLOSED_ESTABLISHMENT_ON_SIRENE = "CLOSED_ESTABLISHMENT_ON_SIRENE"
}
