export type EstablishementCallToAction =
  | "MODIFY_ESTABLISHEMENT"
  | "NOTHING"
  | "REGISTER_ESTABLISHEMENT"
  | "BAD_SIRET"
  | "MODIFY_ESTABLISHEMENT_REQUEST_NOTIFICATION"
  | "UNREGISTERED_SIRET"
  | "MISSING_ESTABLISHMENT_ON_SIRENE"
  | "CLOSED_ESTABLISHMENT_ON_SIRENE";
