export type EstablishementCallToAction =
  | "MODIFY_ESTABLISHEMENT"
  | "NOTHING"
  | "MODIFY_ESTABLISHEMENT_REQUEST_NOTIFICATION"
  | "ERROR_BAD_SIRET"
  | "ERROR_UNREGISTERED_SIRET"
  | "ERROR_MISSING_ESTABLISHMENT_ON_SIRENE"
  | "ERROR_CLOSED_ESTABLISHMENT_ON_SIRENE"
  | "ERROR_TOO_MANY_REQUESTS_ON_SIRET_API"
  | "ERROR_SIRENE_API_UNAVAILABLE"
  | "ERROR_UNEXPECTED_ERROR";
