name: "Deploy DBT app to nightly"

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
      environment:
        type: string
        required: true
    secrets:
      SCALINGO_API_TOKEN:
        required: true

jobs:
  deploy-dbt:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Create DBT bundle
        run: cd bi && ./build.sh

      - name: Install scalingo CLI
        run: |
          wget -qO- https://cli-dl.scalingo.com/install.sh | bash
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Login to Scalingo
        run: scalingo login --api-token ${{ secrets.SCALINGO_API_TOKEN }}

      - name: Deploy DBT
        run: scalingo --app if-prod-nightly-db --region osc-secnum-fr1 deploy bi/dbt-build.tar.gz ${{ inputs.tag }}
