name: "Trigger deploy review App"

on:
  workflow_dispatch:
    inputs:
      pull_request_number:
        description: "The PR number"
        required: true
        type: number

jobs:
  deploy-review-app:
    uses: ./.github/workflows/review-app-deploy.yml
    with:
      pull_request_id: ${{ inputs.pull_request_number }}
      run_number: ${{ github.run_number }}
    secrets:
      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}

  run-seeds:
    needs: deploy-review-app
    runs-on: ubuntu-latest
    environment: review-app
    steps:
      - name: Install scalingo CLI
        run: |
          wget -qO- https://cli-dl.scalingo.com/install.sh | bash
          echo "$HOME/bin" >> $GITHUB_PATH
      - name: Login to scalingo
        run: scalingo login --api-token ${{ secrets.SCALINGO_API_TOKEN }}
      - name: Run DB seed
        run: scalingo --app if-dev-back-pr${{ inputs.pull_request_number }} run pnpm db:seed

  notify-pr:
    runs-on: ubuntu-latest
    needs: deploy-review-app
    steps:
      - name: Find existing notification
        uses: peter-evans/find-comment@v3
        id: find-comment
        with:
          issue-number: ${{ inputs.pull_request_number }}
          body-regex: Review app:\nhttps:\/\/if-dev-front-pr
      - name: Notify PR about the webapp url
        if: steps.find-comment.outputs.comment-id == ''
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Review app:
            https://if-dev-front-pr${{ inputs.pull_request_number }}.osc-fr1.scalingo.io
