name: "Validation PR"

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - review_requested
      - synchronize
concurrency:
  group: review-app-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  fullcheck:
    uses: ./.github/workflows/fullcheck.yml
    secrets:
      API_KEY_OPEN_CAGE_DATA_GEOCODING: ${{ secrets.API_KEY_OPEN_CAGE_DATA_GEOCODING }}
      API_KEY_OPEN_CAGE_DATA_GEOSEARCH: ${{ secrets.API_KEY_OPEN_CAGE_DATA_GEOSEARCH }}
      IC_ADMIN_PASSWORD: ${{ secrets.IC_ADMIN_PASSWORD }}
      IC_PASSWORD: ${{ secrets.IC_PASSWORD }}
      IC_USERNAME: ${{ secrets.IC_USERNAME }}
      PC_USERNAME: ${{ secrets.PC_USERNAME }}
      PC_PASSWORD: ${{ secrets.PC_PASSWORD }}
      PC_ADMIN_PASSWORD: ${{ secrets.PC_ADMIN_PASSWORD }}
      SIRENE_INSEE_CLIENT_ID: ${{ secrets.SIRENE_INSEE_CLIENT_ID }}
      SIRENE_INSEE_CLIENT_SECRET: ${{ secrets.SIRENE_INSEE_CLIENT_SECRET }}
      SIRENE_INSEE_USERNAME: ${{ secrets.SIRENE_INSEE_USERNAME }}
      SIRENE_INSEE_PASSWORD: ${{ secrets.SIRENE_INSEE_PASSWORD }}
      INCLUSION_CONNECT_CLIENT_SECRET: ${{ secrets.INCLUSION_CONNECT_CLIENT_SECRET }}
      PRO_CONNECT_CLIENT_SECRET: ${{ secrets.PRO_CONNECT_CLIENT_SECRET}}

  verify-migration-order:
    name: "Verify migration order"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 10.9.0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.15.0"
          cache: "pnpm"
      - run: |
          pnpm back verify-migrations-order

  add-deploy-link:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const workflowUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/workflows/review-app-trigger.yml`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `📌 Deploy a review app for this PR:

              ➡️ [Click here to deploy review app](${workflowUrl}?ref=${context.payload.pull_request.head.ref})
            
              When clicking the link above:
              1. Click the "Run workflow" button
              2. Enter this PR number: ${context.issue.number}
              3. Click "Run workflow" to start the deployment`
            });

